### ISSUE TITLE
Add DuplicateRecordFields to default-extensions field 

### ISSUE THREAD

**Issue by alexbiehl** [brendanhay/amazonka#1005]
I am toying around with ghc-9.10.1 in our production code base and it looks like I need to put 

```
package amazonka-sts
    ghc-options: -XDuplicateRecordFields

package amazonka-s3
    ghc-options: -XDuplicateRecordFields

package amazonka-ses
    ghc-options: -XDuplicateRecordFields

package amazonka-sso
    ghc-options: -XDuplicateRecordFields

...
```

into our cabal.project file for the Amazonka packages to build. Would be great if Amazonka provided that out of the box. Other than this issue and an allow-newer to override the base bounds, the above packages build and work just fine.

**Comment by endgame** [comment]
I don't believe this is a problem on current `main` — a generator change went through that put `{-# LANGUAGE DuplicateRecordFields #-}` in the places needed by GHC ≥9.8: https://github.com/brendanhay/amazonka/pull/973

**Comment by ysangkok** [comment]
> Other than this issue and an allow-newer to override the base bounds

You don't need to use `allow-newer`. You can use the revision syntax in Stack to select the version that has no base bound. It looks like `amazonka-core-2.0@rev:2`. You can see the full revision list here: https://hackage.haskell.org/package/amazonka-core-2.0/revisions/

More information on the syntax at https://docs.haskellstack.org/en/stable/topics/package_location/#hackage-packages
