### ISSUE TITLE
GetUser fails when used on account root user

### ISSUE THREAD

**Issue by ryantrinkle** [brendanhay/amazonka#102]
When used with credentials from the root user of an AWS account, GetUser fails with this error:

```
Left (SerializerError "IAM" "unable to find element \"Path\" in nodes [\"UserId\",\"UserName\",\"Arn\",\"CreateDate\",\"PasswordLastUsed\"]")
```

**Comment by brendanhay** [comment]
In that case `Path` seems to be incorrectly marked as required [upstream](https://github.com/boto/botocore/blob/6b3dceab06f8135b627e042cb2d7a60a20b48b9f/botocore/data/iam/2010-05-08/service-2.json#L7968). I'll raise the issue, thanks!

**Comment by deepfire** [comment]
@brendanhay, this is still an issue, as of now:
```
[SerializeError] {
  service = IAM
  status  = 200 OK
  message = unable to find element "Path" in nodes ["PasswordLastUsed","Arn","UserId","CreateDate"]
  body    = Just <GetUserResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <GetUserResult>
    <User>
      <PasswordLastUsed>2017-06-09T12:27:05Z</PasswordLastUsed>
      <Arn>arn:aws:iam::XXXXXXX:root</Arn>
      <UserId>XXXXXXX</UserId>
      <CreateDate>2015-09-28T21:37:56Z</CreateDate>
    </User>
  </GetUserResult>
  <ResponseMetadata>
    <RequestId>0d9e0abe-4d6b-11e7-b65f-699c74be717f</RequestId>
  </ResponseMetadata>
</GetUserResponse>
```

**Comment by endgame** [comment]
If this is still a problem, it could be as easy as refetching/regenerating the IAM service def. If it's hard, I'll punt it to post-2.0 since people haven't been screaming loudly about it.

**Comment by brendanhay** [comment]
Looks like it still hasn't changed upstream - additionally the change to make `Path` optional appears to have been lost at some point. I'll reinstate the change as it appears at cursory interpretation that the service descriptions are trying to describe path as required for a request and optional in a response.
