### ISSUE TITLE
gh-pages project pages not working

### ISSUE THREAD

**Issue by mookerji** [brendanhay/amazonka#106]
It seems that the gh-pages link to service-specific modules isn't working.

This is working: 
http://www.brendanhay.nz/amazonka/

but this is not: 
http://www.brendanhay.nz/amazonka/Network-AWS-SWF.html

The Hackage pages are also fine:
https://hackage.haskell.org/package/amazonka-swf-0.3.4/docs/Network-AWS-SWF.html

Thanks for all the hard work!

**Comment by brendanhay** [comment]
Yeah, it's been noted previously in issue #93

**Comment by mookerji** [comment]
Woops.

**Comment by brendanhay** [comment]
No problem, overly specific issue title for #93!
