### ISSUE TITLE
On bucket with a tags it returns empty tag list

### ISSUE THREAD

**Issue by varosi** [brendanhay/amazonka#112]
On a bucket with one or more tags it returns:
> Right (Right (GetBucketTaggingResponse {_gbtrTagSet = List {list = []}}))

What could be the problem? 
I'm using amazonka 0.3.4 on Windows 8.1 x64

I run something like:
>		env <- getEnv Oregon Discover
>		resp <- runAWST env $ do
>			resp <- send env (getBucketTagging "testbucket")
>			return resp

**Comment by brendanhay** [comment]
Apologies for the horrendous turn-around on this. I'm currently traveling for business and have been unable to sit down and attempt to recreate your issue.

**Comment by brendanhay** [comment]
I've added an example which exercises both `PutBucketTagging` and `GetBucketTagging` for the code in `develop`. It's been test on Linux for a number of regions and appears to be functioning correctly now.

Quite a few updates will be released as part of `1.0` shortly, I'm not certain exactly what was causing your error but if you get a chance to test sometime in the future, feel free to reopen if there is still an issue.
