### ISSUE TITLE
"Flattened" List / unsafeToXML incorrect

### ISSUE THREAD

**Issue by kim** [brendanhay/amazonka#113]
I don't ~~really~~ fully understand the implications of "flattened shapes" yet, especially how `EMap` doesn't seem to require special treatment, but `List` does. However, the definition of [unsafeToXML](https://github.com/brendanhay/amazonka/blob/develop/core/src/Network/AWS/Data/Internal/XML.hs#L120-L123) doesn't do the right thing:

```haskell
import qualified Network.AWS.Data as AWS
import qualified Network.AWS.S3 as S3
:m + Control.Lens
:{
AWS.encodeXML $
    S3.completeMultipartUpload "foo" "bar" "123"
        & S3.cmu1MultipartUpload .~ Just (S3.completedMultipartUpload & S3.cmuParts .~
            [ S3.completedPart & S3.cpETag .~ Just "123" & S3.cpPartNumber .~ Just 1
            , S3.completedPart & S3.cpETag .~ Just "I won't appear" & S3.cpPartNumber .~ Just 2
            ])
:}
>>> "<?xml version=\"1.0\" encoding=\"UTF-8\"?><CompletedMultipartUpload xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Part xmlns=\"\"><CompletedPart><ETag>123</ETag><PartNumber>1</PartNumber></CompletedPart></Part></CompletedMultipartUpload>"
```

As you can see, there is no actual "flattening", instead we only get the head element of the list.

Giving a correct definition of a "flattened" XML representation of `List` is straightforward and even needn't be "unsafe":

```haskell
flattenedList :: (KnownSymbol e, ToXML a) => List e a -> [Node]
flattenedList = map flat . toXML
  where
    flat (NodeElement e) = NodeElement
        e { elementNodes = concatMap flat' (elementNodes e) }
    flat n = n

    flat' (NodeElement e) = elementNodes e
    flat' n = [n] -- perhaps just '[]' would suffice
```

Note that the return type needs to be `[Node]`, not `Node`. Also note that this would probably require a typeclass
```haskell 
class ToXML a => Flattened a where
    flatten :: a -> [Node]
``` 
or similar to be sufficiently polymorphic for code generation purposes.

Unfortunately, the type change gets me a bit into trouble with the codegen [template](https://github.com/brendanhay/amazonka/blob/develop/gen/templates/_include/xml-to.ede). The following would work, but not be very pretty:

```diff
@ -11,12 +11,12 @@ instance ToXML {{ type.name }} where
   {% if type.contents | empty %}
     toXML = const (nodes "{{ type.name }}" [])
   {% else %}
-    toXML {{ type.name }}{..} = nodes "{{ type.name }}"
+    toXML {{ type.name }}{..} = nodes "{{ type.name }}" $ concat
     {% for field in type.contents %}
       {% if field.value.flattened && !(field.value.protocol == "ec2") %}
-        {% include "list.ede" %} {{ "unsafeToXML" | justifyLeft(type.contentPad) }}     {{ field.value.name }}
+        {% include "list.ede" %} {{ "flatten" | justifyLeft(type.contentPad) }} {{ field.value.name }}
       {% else %}
-        {% include "list.ede" %} "{{ field.value.locationName | concat("\"") | justifyLeft(type.contentPad) }} =@ {{ field.value.name }}
+        {% include "list.ede" %} ["{{ field.value.locationName | concat("\"") | justifyLeft(type.contentPad) }} =@ {{ field.value.name }}]
       {% endif %}
     {% endfor %}
         ]
```

### Questions

* would this still be an issue on the new AST branch? (and how far is that from being usable?)
* could most/some of the above be avoided by giving a `ToXML` instance for `List` which _always_ flattens?

**Comment by kim** [comment]
I now realise that the flattening could potentially be defined on just `[Node]` as the domain (as a Traversal, if you'd prefer)

**Comment by brendanhay** [comment]
A brief aside about how the (new) generator deals with flattening, it will essentially render chained serialisation operators in the case of non-flattened lists, such as: `"parentElement" .@ "memberItem" .@ _fieldAccessor`, where `_fieldAccessor :: [a]`.

In the case of a flattened list it would simply not render the additional containing element.

This additionally results in not having `List/List1 e a` or `E/Map` types, since the operator application is now specific rather than attempting to determine this information by stuffing singletons into types. (Which caused other issues, since parent/member items can be different in input/output scenarios.)

As such the XML serialisation will hopefully become alot simpler.

The ETA on these changes is still a few weeks out due to other commitments, and they will contain breaking changes (to lens naming) FWIW.

**Comment by brendanhay** [comment]
With commit 44facec (and an unrelated one dealing with S3 required fields on `CompletedPart`) the example you made above would serialise something like:

```haskell
encodeXML $ completeMultipartUpload "foo-bucket" "bar-key" "123"
    & comMultipartUpload ?~
        (completedMultipartUpload (completedPart 1 "123" :| [completedPart 2 "456"]))
```

```xml
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<CompleteMultipartUpload xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\">
  <Part>
     <PartNumber>1</PartNumber>
     <ETag>123</ETag>
  </Part>
  <Part>
    <PartNumber>2</PartNumber>
    <ETag>456</ETag>
  </Part>
</CompleteMultipartUpload>
```
