### ISSUE TITLE
Wrongly generated 'ToXMLRoot' instances

### ISSUE THREAD

**Issue by kim** [brendanhay/amazonka#114]
There is no branch in the codegen [template](https://github.com/brendanhay/amazonka/blob/develop/gen/templates/_include/xml-to-root.ede) which would generate a `Nothing`-valued `ToXMLRoot` instance. This is, however, required for _some_ `POST`/`PUT` request types which must not include a request body, for example [CreateMultipartUpload](https://github.com/brendanhay/amazonka/blob/develop/amazonka-s3/gen/Network/AWS/S3/CreateMultipartUpload.hs).

I'm not familiar enough with the "output" JSON format to be able to figure out the correct fix, but _believe_ every `const` case could actually be replaced with `const Nothing`.

**Comment by brendanhay** [comment]
Right. I'm going to create a separate label with things that can/should be addressed by the generator update, as this issue in particular should (in the sense of how things are supposed to work currently) actually select the correct request method `get`, `stream`, etc. and not in fact even render a `ToXML/Root` instance or attempt to send a seralised body.

**Comment by brendanhay** [comment]
The generator now correctly determines whether or not a serialised or empty put/post body exists, and the related `Network.AWS.Request` function to use: [PutBucketCORS](https://github.com/brendanhay/amazonka/blob/feature/ast/amazonka-s3/gen/Network/AWS/S3/PutBucketCORS.hs#L72-L75) vs [CreateMultipartUpload](https://github.com/brendanhay/amazonka/blob/feature/ast/amazonka-s3/gen/Network/AWS/S3/CreateMultipartUpload.hs#L238)
