### ISSUE TITLE
S3 CopyObject put incorrectly sending empty body

### ISSUE THREAD

**Issue by charleso** [brendanhay/amazonka#118]
The call to [put](https://github.com/brendanhay/amazonka/blob/develop/core/src/Network/AWS/Request/S3.hs#L43) in the [CopyObject](https://github.com/brendanhay/amazonka/blob/develop/amazonka-s3/gen/Network/AWS/S3/CopyObject.hs#L532) should not include a body.

Currently it returns the following `InvalidRequest`:

> The request included a body. Requests of this type must not include a non-empty body.

I can't see anything specific in the JSON that might indicate this will happen, except for the fact that there ends up being no XML body to send. By removing `& rqBody .~ toBody (encodeXML x)` from `put` the operation gets a little further.

For reference the java client version:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1522

**Comment by brendanhay** [comment]
The changes under `feature/ast` now correctly select the appropriate (body-less) `Network.AWS.Method` to use: [CopyObject](https://github.com/brendanhay/amazonka/blob/feature/ast/amazonka-s3/gen/Network/AWS/S3/CopyObject.hs#L302)

Fixed by #114.

**Comment by charleso** [comment]
Awesome. What's the plan for `feature/ast` merging to `develop` BTW?

**Comment by brendanhay** [comment]
I'm still working on re-adding the Pagination / Waiters to that branch, and some basic cleanup. Depending on sleep .. I'll probably look at merging in about a week.

It'll probably then stew in `develop` until I gather enough (or no) feedback on the breaking changes to the lens / type naming (via acronym casing).

**Comment by charleso** [comment]
Awesome. Let us know when you do and we can easily upgrade and test it on a branch for our main amazon project/library.

**Comment by brendanhay** [comment]
![raccoon](https://cloud.githubusercontent.com/assets/4493/8148023/c4d904fa-1287-11e5-9390-e9c6f37528cb.jpg)

**Comment by acw** [comment]
Looks like I just ran into this trying to use CreateMultipartUpload. Any idea when the merge is going to happen?

**Comment by brendanhay** [comment]
I recently implemented some basic auto-generation for test harnesses, and would like to have _some_ coverage of simple request/responses for various services before I merge. ETA on that would be next weekend at the earliest due to work commitments + curry-on conference.
