### ISSUE TITLE
amazonka 0.3.5 depends on amazonka-core (==0.3.4.*)

### ISSUE THREAD

**Issue by qxjit** [brendanhay/amazonka#120]
I assume this is meant to be 0.3.5.* instead of 0.3.4.*

**Comment by brendanhay** [comment]
Thanks for reporting this @qxjit, human error on my part.

**Comment by brendanhay** [comment]
I'm going to push `0.3.6` through CI now, and then re-release all libraries under that version in a couple of hours.

**Comment by brendanhay** [comment]
Version [0.3.6](https://hackage.haskell.org/package/amazonka-0.3.6) is now available on Hackage.

**Comment by qxjit** [comment]
Awesome, thank you!
