### ISSUE TITLE
configurable endpoints

### ISSUE THREAD

**Issue by gdoteof** [brendanhay/amazonka#121]
S3 infrastructure has become so popular that many services match the API.

I am the user of one of those services and discovered that the aws URLs are seemingly only configurable at the time the package is built.  It would be nice to be able to specify, perhaps as part of the credentials.

**Comment by brendanhay** [comment]
That's also something I'd like to make use of. I'll investigate adding it shortly.

**Comment by gdoteof** [comment]
Thanks for taking a look.  I've had luck so far with running a DNS to point amazonaws.com to my riakcs cluster.  unfortunately riakcs does not yet support aws4 authentication.  i'm not yet sure if this library supports (or used to support) the older auth mechanism, but this would likely be another thing to add the configurable endpoints.

**Comment by brendanhay** [comment]
Which API are you using with RiakCS specifically, the S3 API? 

Previously `amazonka-*` supported a range of signers, but as new AWS regions have come into existence which have a requirement on using AWS4, I've slowly migrated towards maintaining a smaller set of signers.

I'm open to making the signer selection more configurable (alongside the endpoint selection), but it complicates things somewhat, I'll need to go to the drawing board.

**Comment by brendanhay** [comment]
The endpoints and signers will be configurable in the next major release via something like:

[core/Types.hs](https://github.com/brendanhay/amazonka/blob/fa87a87eef0cbe865732158a9e5f9ef9c57801ae/core/src/Network/AWS/Types.hs#L154)
[amazonka/Trans.hs](https://github.com/brendanhay/amazonka/blob/fa87a87eef0cbe865732158a9e5f9ef9c57801ae/amazonka/src/Control/Monad/Trans/AWS.hs#L148)

To get a different signing algorithm + endpoint, for example, you would create a new `AWSService` instances for a new `Void` service type, choosing the desired signing algorithm, and then pass this service explicitly to `sendWith` and other `*With` variants in `amazonka`:

```
data MyS3

instance AWSService MyS3 where
    type Sg MyS3 = <V2 | V4 signing algirithm>

    service = const $ s3Service { _svcEndpint = <your-endpoint-function> }
```

I'll hopefully also get around even needing to do the above, but this is where it currently stands.

Does that look like it will solve your use-cases?

**Comment by brendanhay** [comment]
The above changes have made it into the `develop` branch. There are currently no examples available of re-configuring a `Service`'s signer and endpoints, but I hope to add some soon.
