### ISSUE TITLE
`restError` does not handle failures around HEAD calls

### ISSUE THREAD

**Issue by nhibberd** [brendanhay/amazonka#125]
When the `receive` function is called in [Network.AWS.Response](https://github.com/brendanhay/amazonka/blob/develop/core/src/Network/AWS/Response.hs) it will attempt to parse using the service handler which will is generated in terms of [restError](https://github.com/brendanhay/amazonka/blob/develop/core/src/Network/AWS/Error.hs#L117). The `restError` will check if it has a  `statusSuccess` (200..400), if that fails (i.e. 404), it will attempt to parse the remaining xml which naturally on a HEAD doesn't exist and you are left with a `SerializerError`.

Ideally the generated S3 service / each operation would provide its own handler for handling different HTTP status codes / exceptions. Or at a minimum the error returned here should be a `ServiceError`, not a `SerializerError`

**Comment by brendanhay** [comment]
I think the best approach in the short term would be to uniformly pass the `HttpMethod` into the response handler, `restError`, in this case, and then deserialise or not as appropriate.

One issue with the service descriptions is that they offer very little in the way of metadata regarding errors, with [this being the HeadObject example](https://github.com/boto/botocore/blob/d5b8349ff4832a152f1a28ef39848430384916ab/botocore/data/s3/2006-03-01/service-2.json#L401). In that case the `NoSuchKey` `"shape"` is referring to the [`_restCode`](https://github.com/brendanhay/amazonka/blob/600f44ac882535a5579d0a7bb7e8ebe271274b99/core/src/Network/AWS/Error.hs#L99), so the errors can be explicitly enumerated per operation, with the same caveats you mentioned for methods, status codes, and so forth. 

There are still plenty of pathological error cases for other services, but hopefully this improves the semantics somewhat.

**Comment by kim** [comment]
+1 for making the HTTP status available for any response (via some optical). I just yesterday realised that using `HeadObject` with a `If-None-Match` header is somewhat pointless as I can't really distinguish a 302 from a 200.

(Btw, 404 being a ServiceError seems incidental atm - it actually throws an error because it attempts to parse the expectedly empty response body. Not sure if this has been reported before.)

**Comment by brendanhay** [comment]
I'm looking at emulating some of the other SDK's error handling, and it seems a `302` for S3 would result universally in an [error](https://github.com/aws/aws-sdk-ruby/blob/17508581a6887fb170e608242165b1ee18ccd9a9/aws-sdk-core/lib/aws-sdk-core/xml/error_handler.rb#L8).

![2928543-524906464-not_sure_if_serious](https://cloud.githubusercontent.com/assets/4493/8350320/b4aa0278-1b24-11e5-8309-660ebb0966f3.jpg)

**Comment by brendanhay** [comment]
So for the Ruby SDK, the status code intervals appear to be:

* `XML` (S3, EC2, etc.): `[300, 600)` is considered parse-able if the response body is present.
* `JSON` (OpsWorks, Kinesis, etc.): `[300, 600)` is considered parse-able if the response body is present.
* `REST` (Lambda, Glacier, etc.): `[300, ∞)` returns the status code verbatim.

In the `XML` and `JSON` cases if the response body is not present, an empty error with the status code is returned, which aligns with @nhibberd's patch above.

**Comment by brendanhay** [comment]
Somewhat separately from the above issue in response to @kim, all responses now contain a [status code](https://github.com/brendanhay/amazonka/blob/fa87a87eef0cbe865732158a9e5f9ef9c57801ae/amazonka-s3/gen/Network/AWS/S3/ListParts.hs#L208) `Int`, which will probably be changed to a `http-types.Status` at some point.

**Comment by brendanhay** [comment]
In response to the original issue from @nhibberd, `feature/ast` has error handling now consistent with the other SDKs in regards to status codes, and empty response bodies:

* Error Handling: [Network.AWS.Error](https://github.com/brendanhay/amazonka/blob/fa87a87eef0cbe865732158a9e5f9ef9c57801ae/core/src/Network/AWS/Error.hs#L295)
* Overrideable Response Parsing/Handling: [core/Types.hs](https://github.com/brendanhay/amazonka/blob/fa87a87eef0cbe865732158a9e5f9ef9c57801ae/core/src/Network/AWS/Types.hs#L156-L157)
* Pass Custom Service: [amazonka/Trans.hs](https://github.com/brendanhay/amazonka/blob/fa87a87eef0cbe865732158a9e5f9ef9c57801ae/amazonka/src/Control/Monad/Trans/AWS.hs#L148)

In addition to this fixtures are generated for all requests/responses, and I'll work through the AWS documentation to add the examples:

* [Test.AWS.Gen.\<Service\>](https://github.com/brendanhay/amazonka/tree/fa87a87eef0cbe865732158a9e5f9ef9c57801ae/test/gen/Test/AWS/Gen)
* [Fixtures](https://github.com/brendanhay/amazonka/tree/fa87a87eef0cbe865732158a9e5f9ef9c57801ae/test/fixture)

**Comment by brendanhay** [comment]
The changes above have now been merged into `develop`, and should correctly handle the empty response error case as defined [here](https://github.com/brendanhay/amazonka/blob/44cfc67152a84df0cfcdec461693e06b995c5e07/core/src/Network/AWS/Error.hs#L133-L134).
