### ISSUE TITLE
DeleteObjects requires Content-MD5 header

### ISSUE THREAD

**Issue by kim** [brendanhay/amazonka#126]
This is not captured in the service definition as far as I can tell. But even if it was, it would make for an awkward API: supposedly, one builds the request structure (without the header), then serialise to XML, MD5 the result and modify the request by adding the header.

Maybe there's a way to just transparently set a `Content-MD5` header for applicable request types?

**Comment by kim** [comment]
Ah lol, I had reported this before #115

Though the awkwardness comments still apply

**Comment by brendanhay** [comment]
Moar info here. Re-opening this and closing #115.

**Comment by brendanhay** [comment]
For `V4` signing a SHA256 is required, maybe the `Content-MD5` could use a similar mechanism if that's what you're getting at? Example [here](https://github.com/brendanhay/amazonka/blob/b8f96d0048bfbad74639df1be3ac5703f1d3b20c/core/src/Network/AWS/Request.hs#L92).

**Comment by kim** [comment]
Right. The question is if it should be opt-in (or opt-out). But since it is [recommended](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html), it might be fair to just have it by default.

**Comment by brendanhay** [comment]
The [Ruby SDK](https://github.com/aws/aws-sdk-ruby/blob/17508581a6887fb170e608242165b1ee18ccd9a9/aws-sdk-core/lib/aws-sdk-core/plugins/s3_md5s.rb#L15) annotates requests where the operation is inclusive in a configured set. Something similar could be achieved by having the `Service` configuration expose a function that will massage and request before sending. The user could then override this if needed via some mechanism like [this experimental attempt](https://github.com/brendanhay/amazonka/blob/a613f175bd9ddb3b9d6740d9fcbea636605d745f/amazonka/src/Network/AWS.hs#L231).

**Comment by brendanhay** [comment]
This should now be fixed via the preceding commits.
