### ISSUE TITLE
signature calculation failure for URLs with "=" in them

### ISSUE THREAD

**Issue by michaelneale** [brendanhay/amazonka#127]
Attempting to upload to something like: 

`s3://bks/a=1/file.txt`

will result in: 
"The request signature we calculated does not match the signature you provided. Check your key and signing method."

It appears that the `=` needs to be url encoded before being put in the header

**Comment by brendanhay** [comment]
Hi @michaelneale,

In order to construct a contrived test-case - When you mention uploading, you are referring to `PutObject` specifically? And in regards to 'being put in the header', you're referring to the `Authorization` header specifically?

**Comment by michaelneale** [comment]
@brendanhay yes, definitely was put - and yes I think it was in the auth header where it hurt (I was using various auth schemes, one of which was using STS tokens, so I am not sure if that affects what ends up in the header - I will check with @nhibberd today as he provided a work around.

**Comment by michaelneale** [comment]
we had to do something like: 
```
encodeKey :: Key -> Text
encodeKey (Key k) =
  let splitEncoded = urlEncode True . encodeUtf8 <$> split (== '/') k
      bsEncoded = BS.intercalate "/" splitEncoded
  in
  decodeUtf8 bsEncoded
```

(assuming that '/' was the delimeter in our case)

**Comment by michaelneale** [comment]
Actually we url encode the whole key before calling _send - so it may be more than just the Authorization header (basically anywhere the s3 key could appear in the header, would need encoding of non token parts).

**Comment by michaelneale** [comment]
Hi @brendanhay - did some more investigation, this is for all verbs - put, get, head etc. all show the same behaviour. 

You can try it by having any key with `=` in the path (like s3://.../yeah=2015/month=07/ for example) and you will see it. I just happened to see it first with put. Strangely by URL encoding the whole key, it won't work, you have to leave the delimiters (/) unencoded (making me think something else encodes them). 

It will generally show up as a 404 or signature failure error of some kind. The key can appear in a header or the query string (which makes me think it is nothing to do with http conventions/restrictions but is at the amazon end). 

Sorry to not have more info - but easiest thing is to try it.

**Comment by brendanhay** [comment]
Thanks, that's perfect.

**Comment by michaelneale** [comment]
Alarmingly, not clear why the delimiters shouldn't be encoded (but other bits should be), but if you find out the theory behind it, would be good to know.

**Comment by brendanhay** [comment]
AFAIK 'it depends on the context' regarding the semantic meaning of a reserved character in the domain according to [RFC3986](https://tools.ietf.org/html/rfc3986), there's some more info [here](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_in_a_URI).

In the case of S3 they actually [recommend](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-key-guidelines) a smaller character set for valid keys and mention that `+` specifically might be lost (space encode/decode). 

Either way I do actually think there is some double encoding of percent-encoded values occurring between `ToPath` and the signing algorithms, so I'll spend some time revisiting that today.

**Comment by michaelneale** [comment]
@brendanhay much appreciated - tearing what little hair I have left out. I note that the offical SDK (based on boto) and the java ones seem to be ok, they seem to handle those specific cases in that amazon link (handy BTW). I am guessing the "/" being the delimiter gets special treatment (it still appears encoded in any query string when it is used, but you can't url encode it at the same time as the "=").

**Comment by brendanhay** [comment]
Thanks. I'm just going to brain dump into this issue as I dig into the other SDKs.

The official Ruby SDK appears to ignore any path encoding if the service is specifically S3 before version 4 signing: 

* [aws-sdk-core/signers/v4.rb](https://github.com/aws/aws-sdk-ruby/blob/cf69bdd2a417bac4824f5ec7324fc6925daaf628/aws-sdk-core/lib/aws-sdk-core/signers/v4.rb#L132)
* [seahorse/util.rb](https://github.com/aws/aws-sdk-ruby/blob/cf69bdd2a417bac4824f5ec7324fc6925daaf628/aws-sdk-core/lib/seahorse/util.rb#L24)

**Comment by brendanhay** [comment]
For Botocore it's natürlich same-same but different! S3 specifically is also not path encoded before signing.

* [botocore/auth.py](https://github.com/boto/botocore/blob/3e0489a1cccf30f0f2f643a0d62fa2f729ee0ffd/botocore/auth.py#L253)
* [botocore/utils.py](https://github.com/boto/botocore/blob/3e0489a1cccf30f0f2f643a0d62fa2f729ee0ffd/botocore/utils.py#L50)
* [python/urllib.py](https://github.com/python-git/python/blob/715a6e5035bb21ac49382772076ec4c630d6e960/Lib/urllib.py#L1181)

**Comment by michaelneale** [comment]
Hrm [comments in python](https://github.com/python-git/python/blob/715a6e5035bb21ac49382772076ec4c630d6e960/Lib/urllib.py#L1196) seem interesting, they specifically mark "/" as safe, as it is intended for the path component (which seems to be the case here). First thing I have seen that kinda makes sense.

**Comment by brendanhay** [comment]
Right. While I think now the encoding behaviour is fairly evident in the other SDKs, I'm still not grasping the fact there is no encoding of S3 ObjectKeys in the path, they are explicitly untouched for signing in both Ruby and Python SDKs. And again, neither SDK appears to explictly encode path elements for the actual request - unless it occurs in bowels of the respective HTTP request libs.

So the differences with Amazonka from what I understand so far:

1. The SDKs URL encode the path components between the delimiter `/` for constructing the canonical request to sign _unless_ it is S3, and then no encoding is performed.
2. URL encoding has extra cases for `~+_-` comparing to the RFC.

**Comment by michaelneale** [comment]
I actually think the Python one shows that it does encode only the path
elements, by saying safe="/"

**Comment by brendanhay** [comment]
That's correct - but it doesn't do that for S3. The path encoding for the canonical request is [overriden](https://github.com/boto/botocore/blob/3e0489a1cccf30f0f2f643a0d62fa2f729ee0ffd/botocore/auth.py#L368) to be a noop. I also can't find evidence of any path mutation occuring pre signing.

**Comment by michaelneale** [comment]
Oh wow. Ok back to WTF. They all do work how we expect right?

**Comment by brendanhay** [comment]
I'm pretty squarely in WTF territory. I'll try tracing some awscli requests and see if I can figure out what is up in py-thong land.

**Comment by brendanhay** [comment]
Mein eyes. Mein brain.

`url_path` which is used for the HTTP request is encoded [here](https://github.com/boto/botocore/blob/3e0489a1cccf30f0f2f643a0d62fa2f729ee0ffd/botocore/serialize.py#L401) and [here](https://github.com/boto/botocore/blob/3e0489a1cccf30f0f2f643a0d62fa2f729ee0ffd/botocore/serialize.py#L424).

But wait, there's more! It's also then decoded and re-encoded [here](https://github.com/boto/botocore/blob/3e0489a1cccf30f0f2f643a0d62fa2f729ee0ffd/botocore/vendored/requests/models.py#L404) and [here](https://github.com/boto/botocore/blob/3e0489a1cccf30f0f2f643a0d62fa2f729ee0ffd/botocore/vendored/requests/utils.py#L417).

Observed behaviour seems to be something like:

* Escape the path according to the RFC with the additional cases mentioned above for `+` etc.
* Collapse dot (`.`/`..`) delimiters and escape it again for non-S3 requests when calculating the canonical request. (WTF, double escaping can't be right.)

The docs say `Normalize URI paths according to RFC 3986 by removing redundant and relative path components. Each path segment must be URI-encoded. If the absolute path is empty, use a forward slash (/). In the example request, nothing follows the host in the URI, so the absolute path is empty.`

So this suggests just straight up encoding with additional characters and an exception for the delimiter `/` should be kosher. The additional collapsing of relative paths can be done in the canonical request construction, with and exception for S3.

I think that clarifies it in my mind at least. There just needs to be a more central/consistent approach to ensuring that the entire URL is split, encoding, and intercalated before signing/sending.

**Comment by brendanhay** [comment]
So basically, just doing what @nhibberd's fix did but for all paths. :)

**Comment by michaelneale** [comment]
Right that is what we (somewhat accidentally) did in our client code.

**Comment by michaelneale** [comment]
Nice. Yes go with that. Let us never speak of this again.

**Comment by brendanhay** [comment]
![stimpy](https://cloud.githubusercontent.com/assets/4493/8955838/8a356f3c-35f0-11e5-9df8-4c61b027b1c9.gif)

**Comment by michaelneale** [comment]
Yay!
