### ISSUE TITLE
AWSPager for ListObjects

### ISSUE THREAD

**Issue by nhibberd** [brendanhay/amazonka#128]
I can see the input paginators json for [ListObjects](https://github.com/brendanhay/amazonka/blob/develop/gen/input/s3/2006-03-01.paginators.json) is slightly out of sync or incomplete with [aws spec](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html) or possible the aws api is really incomplete.
Basically there is more than one option for pagination in regards to `ListObjects`, the json and generated code show the first, given that a `delimiter` is specified then the marker for subsequent request is the `NextMarker` returned.
```
instance AWSPager ListObjects where
    page rq rs
        | stop (rs ^. lorIsTruncated) = Nothing
        | otherwise = Just $ rq
            & loMarker .~ rs ^. lorNextMarker
```

Another option is where no `delimiter` is specified, however the response will not contain `NextMarker`, this is possibly an oversight from amazon. The pagination then relies on setting the `NextMarker` to the last result from the `Contents` on the response.
i.e.

```
instance AWSPager ListObjects where
    page rq rs
        | stop (rs ^. lorIsTruncated) = Nothing
        | otherwise =
            if (isJust $ rs ^. lorDelimiter)
              then Just $ rq & loMarker .~ rs ^. lorNextMarker
              else Just $ rq & loMarker .~ ((^. oKey) <$> (lastMaybe (rs ^. lorContents)))

lastMaybe :: [a] -> Maybe a
lastMaybe = listToMaybe . reverse
```

**Comment by brendanhay** [comment]
Thanks for outlining the proper logic.

It's actually a bug in the generated code as S3 paginators definition correctly contains the [disjunction](https://github.com/brendanhay/amazonka/blob/600f44ac882535a5579d0a7bb7e8ebe271274b99/gen/input/s3/2006-03-01.paginators.json#L36).

At the risk of sounding like a broken record, the `feature/ast` branch appears to have generated a more correct [ListObjects AWSPager instance](https://github.com/brendanhay/amazonka/blob/c6658f88d0b87db39734808f70399482fb0d14d2/amazonka-s3/gen/Network/AWS/S3/ListObjects.hs#L121).

**Comment by nhibberd** [comment]
Ah indeed, looking forward to when that branch comes through :+1:

**Comment by brendanhay** [comment]
The changes to the [ListObjects AWSPagest instance](https://github.com/brendanhay/amazonka/blob/2b02a3d35cf5949163b8221641d33c982e96b83d/amazonka-s3/gen/Network/AWS/S3/ListObjects.hs#L124-L137) is now in `develop`.
