### ISSUE TITLE
Derive Data, Typeable, and Generic instances for request & response types

### ISSUE THREAD

**Issue by iand675** [brendanhay/amazonka#130]
It would be really nice to offer these instances for boilerplate reduction purposes, since more and more libraries offer default instances for data types with these instances.

**Comment by brendanhay** [comment]
Can do. I'll look at adding them after this weekend.

**Comment by brendanhay** [comment]
Had to revert a small change in the above commit - all product + sum types generated in `.Types.hs` will have GHC-derived `Data`, `Typeable`, and `Generic` instances. But for request/response types, they will only have `Data` and `Typeable` if they do not contain a streaming body. 

The reason for this is the wrapped `Conduit` types do not have these instances. Hopefully this is still sufficient for your purposes.

**Comment by iand675** [comment]
Yes, this is excellent, thank you!
