### ISSUE TITLE
Mock testing?

### ISSUE THREAD

**Issue by jkozlowski** [brendanhay/amazonka#133]
I understand that what I'm asking for is very Java-esque, but I was wondering if it is possible to mock out actual calls to AWS for testing? I would like to be able to write automated tests for AWS logic. I had a quick peruse around the code and I think it could be possible, but I was wondering if someone has actually tried it?

**Comment by brendanhay** [comment]
I personally haven't tried, but it would indeed be useful.

Off the top of my head, some work would need to be done to make available the choice of actually performing an HTTP request or using a canned response. I'll look into it.

**Comment by jkozlowski** [comment]
If I'm not mistaken, every request goes through Network.HTTP.Conduit.Manager (and Env in general) (I think), so abstract that away somehow and maybe that wouldn't require any other changes. Apologies if I'm oversimplifying.

**Comment by brendanhay** [comment]
You're correct, it looks like you could mock out the related functions for `Manager` and `Connection`, and pass that in to the `Env`. I'll try it out.

For comparison `http-client` tests itself via running a [local TCP server](https://github.com/snoyberg/http-client/blob/fd987de9f218ab32baded995251cf6fb4d0ef324/http-client/test-nonet/Network/HTTP/ClientSpec.hs#L20).

A more elaborate implementation might be to offer a Free Monad + interpretations for `MonadIO` and a pure variant. Not sure if that gains anything other than intellectual satisfaction, though.

**Comment by jkozlowski** [comment]
I get that spinning a TCP server is a possibility, but I am simply speaking about testing code that uses the Amazon client; spinning a TCP server would be a good way of testing the client itself (i.e. Amazonka).

At least that's how I see it. For the testing I had in mind, I just want to lock down that my code is doing what I think it should be doing (regardless of whether that is correct or not). Then some sort of integration/regression testing in a test environment would confirm whether what I thought it should do is correct. 

> A more elaborate implementation might be to offer a Free Monad + interpretations for MonadIO and a pure variant. Not sure if that gains anything other than intellectual satisfaction, though.

Personally I would like to see that, but again for intellectual curiosity (as I've not gone that way before myself). Would it be a more invasive change?

**Comment by brendanhay** [comment]
Yeah, I only referred to the TCP server as an illustration of my attempts to find other people mocking using `http-client`.

As a contrived example, say you'd like to perform an S3 `GetObject` request and return a `GetObjectResponse` which would need to contain a `RsBody` filled with some streaming data.

How would you envisage performing the mock from your own code?

It seems reconfiguring/mocking `Manager` and `Connection` don't allow you to dispatch on the type, ie you don't know from the `Manager` POV what request is being sent. You'd need to wrap every individual call in your application so that each HTTP request returns the mock response for that particular call:

```haskell
-- Modifies the 'Manager' to noop and return a mocked response.
mock rs = ...

main = runAWS $ do
    rs <- mock (getObjectResponse ...) $
      send (getObject ...)
```

As such It would seem preferrable to associate _any_ `GetObject` request with some 'pre-defined' `GetObjectResponse` pertinent to your application. This would be generalised to allow overloading the top-level with 'this is the `Rs a` to return (without performing an actual HTTP request) when `a` is sent':

```haskell
-- Actual application doing real AWS calls.
main = runAWS $ ...

-- Mocked application that ensures any AWS calls return predefined responses.
main = mockAWS mocks $ ...
  where
    mocks =
      [ Mock (Proxy :: GetObject) (getObjectResponse ..)
      , Mock (Proxy :: PutObject) (putObjectResponse ..)
      ]
```

A `Free` (or `Operational`) Monad would mean the functions currently defined in `Network.AWS` would essentially become branches of a GADT. It's a little less trivial to draw up an example without a type checker. Here is a real-world example:

* [RedisRESP protocol](https://github.com/twittner/redis-resp/blob/091305bf2445b724c116e0d934dfb660c9a3c748/src/Data/Redis/Command.hs#L280) `Command`s represented as a GADT.
* [IO interpretation](https://github.com/twittner/redis-io/blob/a9c20b00aa70c58b787aef2535d22cd4ed19861a/src/Database/Redis/IO/Client.hs#L195) of the above `Command` structure using Operational.

**Comment by jkozlowski** [comment]
This is seriously above my Haskell experience, so I can only speak of Java mocking frameworks which basically are a bunch of hacks (like proxying classes) to make for a nice dev experience. So the following are my guesses.

Maybe "send" and other primitive operations should basically be stuck into a typeclass (so MonadAWS would need to be a typeclass), but I don't know what the implication of this would be. This is how it would be done in Java, have an interface and allow you to switch it's implementations (for a mocked one that you can "prepare" in advance to return you the right responses).

This is probably totally wrong.

**Comment by brendanhay** [comment]
There would be nothing inherently wrong with misusing type classes to provide overridable behaviour, it's more a question of style.

You end up having to re-implement all of the logic when defining your mock instance, and you don't get any 'correct by construction' guarantees that `Free` Monads might give you.

[Here](https://gist.github.com/brendanhay/0d967882713c1c22ee35/f4e0b7dd17d514f387a64e36d57b1d308b4f4bf3#file-network-aws-free-program-hs-L1) is an example using `FreeT`. This instruction set captures any potentially external HTTP calls, and defers the interpretation until later using [the appropriate interpreter](https://gist.github.com/brendanhay/0d967882713c1c22ee35/f98f3edccef0543467b1c87233d7f8681a06b681#file-network-aws-hs-L34-L43). In the `runAWS` case, it actually performs the expected external calls etc. In the pure `mockAWS` case, you're required to denote how to construct the appropriate response for a request.

**Comment by jkozlowski** [comment]
Thanks for looking into this!

This is where my lack of experience comes out: I don't understand this code just yet, but from what I know about free-monads this would indeed allow for mocking everything nicely. I would like to use the same idea to provide a higher level interface to Amazon SWF (maybe you would be interested in this).

Would be great to get more people to look into the actual code, as I can't evaluate it fully yet :)

**Comment by brendanhay** [comment]
The changes are now in `develop`. Separately from this issue, over the coming week(s) I'll try and document how one would go about mocking the library directly in the Haddock documentation available [here](http://www.brendanhay.nz/amazonka-doc/amazonka).

**Comment by jkozlowski** [comment]
Awesome, thanks :)

**Comment by cstrahan** [comment]
@brendanhay did you back out of the `Free` Monad approach? (I'm looking at https://github.com/brendanhay/amazonka/blob/bae8a2ff15f19636028b652b0d6a7743fb44d511/amazonka/src/Control/Monad/Trans/AWS.hs#L184)

If you did, I would be interested in knowing the rationale.

**Comment by brendanhay** [comment]
Mobile, so in the meantime some light reading is available [here](https://github.com/brendanhay/amazonka/pull/186).

**Comment by parsonsmatt** [comment]
Is there a way to mock requests right now for Amazonka?

**Comment by brendanhay** [comment]
Unfortunately, no. The `Free` approach may make a reappearance at some point - but it's a non-trivial amount of work so has been shelved for now.

**Comment by LeifW** [comment]
I wonder about using the aws service descriptions to generate a Servant API. Then clients could be generated from that, as well as mock servers if need be.

**Comment by parsonsmatt** [comment]
Ahh, I remember this :) My thoughts on testing/mocking have evolve da bit and mocking AWS at this level feels like the wrong approach to me. I think there are two better approaches:

1. Use [`localstack`](https://github.com/localstack/localstack) for testing where you want to test the AWS-ish bits.
2. Write an internal type class or interface record that abstracts over the higher level bits of AWS. Using SQS? Make a `class MonadQueue m where ..` that captures what you're doing, and then you can write easy in-memory instances that use TQueues etc to make assertions on.

**Comment by brendanhay** [comment]
@LeifW There are a number of drawbacks to using `servant` to describe an API of this size, primarily compilation times (see `gogol`) and supporting the individual service minutiae. To implement said specifics for the 5 or 6 variants of service type (AWS parlance) such as `rest-json`, `rest-xml`, `json`, and `s3`, etc. you need to extend servant with a plethora of newtypes and new interpretations. All these new types then need instances for everything, ie. `servant-client`, or the usual orphan instance dance.

I personally find the servant ecosystem is not particularly open for extension (like a lot of heavy type-level programming) if you have service definitions that don't rigidly follow the provided type class instance/interpretations provided with servant.

There is regret for going down that road with [gogol](https://github.com/brendanhay/gogol/blob/e31ece9b325f14cfae54523ad6c15c84b06d3715/core/src/Network/Google/Types.hs#L379-L600) and think a better thought out version of what is in `amazonka` (namely, less type classes, more value-level programming/functions, `IO`) is a saner approach. I personally test similar to what @parsonsmatt describes, by better structuring my applications such that I can replace actual SQS use with a different instance of `MonadQueue` when testing, for example.

**Comment by 0xd34df00d** [comment]
Came across this issue while googling for "amazonka free monad".

@brendanhay if I'm willing to take a stab at providing a free monad API (say, to support both mock testing and dry-run), would you have any suggestions for me where to start? I'm mostly interested in s3 at the moment.
