### ISSUE TITLE
SendRawEmail fails with large data

### ISSUE THREAD

**Issue by qxjit** [brendanhay/amazonka#134]
When I try to send a large payload (e.g. a 50k attachment) using `SendRawEmail`, I end up getting an HTTP 505 Version Not Supported error from AWS.

It looks like `SendRawEmail` is putting the the entire request into the query string rather than the POST body, which I suspect is the problem.

**Comment by brendanhay** [comment]
Thanks, I'll need to consider how to conditionally (or wholly) place the contents into the POST body.

**Comment by qxjit** [comment]
Thank you! :D
