### ISSUE TITLE
301 Failure Mode.

### ISSUE THREAD

**Issue by nhibberd** [brendanhay/amazonka#135]
Seeing a weird behaviour where S3 PutObject results in a 301 where the bucket exists but is in another region (due to a typo - it isn't even our bucket and we we don't have permissions to this other bucket). However when 301 is returned it is classed as a success case, no following of the redirect appears to happen, and using send_ makes it looks like everything is all good even though no successful upload was ever made. What is the expected behaviour here? Should 301 not be a success here? Is there a better alternative to send_ here that would let this be handled correctly.

**Comment by brendanhay** [comment]
Due to the signing mechanisms (Version 4, specifically) encoding the region name as part of the signature calculation a `301 Redirect` should in fact be an error.

For more information, see: https://github.com/boto/botocore/issues/424

**Comment by brendanhay** [comment]
The [statusSucess](https://github.com/brendanhay/amazonka/blob/96247f733dce1fdcd193b15b82a3ebc66eee798b/core/src/Network/AWS/Error.hs#L33) definition and usage for the [S3 service](https://github.com/brendanhay/amazonka/blob/96247f733dce1fdcd193b15b82a3ebc66eee798b/amazonka-s3/gen/Network/AWS/S3/Types.hs#L459) in `develop` doesn't consider `>= 300` status code responses as successful.

I apologise for not offering a fix/workaround for `0.3.6`.
