### ISSUE TITLE
DynamoDBs' PutItem can't accept the use of ConditionExpression.

### ISSUE THREAD

**Issue by seanparsons** [brendanhay/amazonka#142]
It appears Amazon have some validation which causes a PutItem request to fail if the piConditionExpression lens is used to set a value for that:

    ServiceError "DynamoDB" (Status {statusCode = 400, statusMessage = "Bad Request"}) "JSONError {_jsonType = Just \"com.amazon.coral.validate#ValidationException\", _jsonCode = Nothing, _jsonMessage = \"Can not use both expression and non-expression parameters in the same request: Non-expression parameters: {Expected} Expression parameters: {ConditionExpression}\"}"

I'm assuming that they're treating an empty "Expected" map to indicate that something has been passed for that field. :(

**Comment by brendanhay** [comment]
Are you using `0.3.6` from Hackage? It looks (at first glance) like it might be related to #98, which has been fixed in `develop` as part of preparation for a `1.0` release.

**Comment by seanparsons** [comment]
@brendanhay I am! Aha, cheers for that, I'll close this then as it sounds like it's a duplicate.
