### ISSUE TITLE
ObjectKey opacity and combinators

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#143]
In `develop` I introduced the `ObjectKey` `newtype` instead of exposing raw `Text` in `amazonka-s3`. This was intended to make it easier to transition to + work on a fix for #127.

There are a couple of annoyances:

* Lack of a `Monoid` instance makes path manipulation difficult.
* The specific delimiter used needs to be known at encode/decode time.

Since the delimiter is only specified as part of operations such as `ListObject`, and there is no way to obtain that information during the encoding of the `ObjectKey` it looks likely it will need to also be contained in the `ObjectKey` data type.

Perhaps some combinators can be provided which assume a `/` delimiter, to make the default case as simple as possible and for those that use a custom delimiter, probably some less convenient but more exposed API can be offered.

**Comment by brendanhay** [comment]
Since any forms of encoding/decoding rely on the user specifying the exact delimiter to be used, this is one approach off the top of my head:

```haskell
type Delimiter = Char

data ObjectKey
    = Decoded Char [ByteString]
    | Encoded ByteString

data ObjectKey = ObjectKey Delimiter [ByteString]
    deriving (Eq, Ord, Read, Show, Data, Typeable, Generic)

instance FromText ObjectKey where
    parser = Encoded . Text.encodeUtf8 <$> takeText

instance FromXML ObjectKey where
    parseXML = parseXMLText "ObjectKey"

instance ToByteString ObjectKey where
    toBS = encodeKey

instance ToText    ObjectKey where toText   = toText  . toBS
instance ToQuery   ObjectKey where toQuery  = toQuery . toBS
instance ToBuilder ObjectKey where build    = build   . toBS
instance ToXML     ObjectKey where toXML    = toXMLText

-- Would this cause more problems than it's worth?
instance IsString ObjectKey where
    fromString = objectKey '/'

-- no sensible Monoid instance, path combinators instead?

objectKey :: Char -> ByteString -> ObjectKey
objectKey c = Decoded c . BS8.split c

encodeKey :: ObjectKey -> ByteString
encodeKey = \case
    Decoded c xs -> BS8.intersperse c $ map (urlEncode False) xs
    Encoded bs   -> bs

decodeKey :: ObjectKey -> Either (Char -> ByteString) ByteString
decodeKey = \case
    Decoded c xs -> Right (BS8.intersperse c xs)
    Encoded bs   -> Left $ \c ->
        BS.intercalate (BS.singleton c) $
            map (urlDecode False) (BS.split c bs)
```

**Comment by kim** [comment]
Upon revisiting my use of object keys, I realise that it would be sufficient for me to be able to obtain an `IndexedTraversal` of an `ObjectKey` (where I could supply the delimiter): I am assembling the actual "path" in an application-specific way, but would like to be able to modify the "file name" component (ie. the last element, ie. the `traverseMax` traversal). Though I don't have an opinion about the internal representation, this would suggest preferring an `O(1)`-indexable structure over a list in the underlying data structure.

Another thing is that the `copySource` of a `CopyObject` (respectively `UploadCopySource`) could use a more specific type than `Text`, with a (smart) constructor to make one from a `BucketName` and `ObjectKey`.

**Comment by brendanhay** [comment]
Not entirely sure how to make a nice API out of this. When you construct the `ObjectKey` the delimiter is required to ensure the serialisation of path components - the bits in between the delimiters, can be done correctly.

When deserialising you have no idea what the delimiter is, so you leave it up to the user to specify it when converting to another representation - `ByteString` in the `decodeKey` case above.

If you provide some kind of traversal - then you already have the delimiter in the decoded case, but not in the encoded case and it would need to be specified to correctly traverse the encoded `ByteString`.

I'm guessing there's a nicer approach somewhere around here ..

**Comment by brendanhay** [comment]
Tangentially - `Data.Seq` offers `O(1)` access of the last element via the `viewR` pattern, and likewise has good support in `lens`.

**Comment by brendanhay** [comment]
I'll also note here for my future self - returned keys are not encoded by default, If `encoding-type=url` is specified in a request, then the keys will be URL encoded in the response.

**Comment by brendanhay** [comment]
I'm a fool! Totally fucked that up. Custom delimiters are only important for the traversal you outlined above - for purposes of encoding and calculating the region only `'/'` is considered for splitting etc.

Very nearly over complicated that ..

**Comment by brendanhay** [comment]
@kim: [here](https://github.com/brendanhay/amazonka/blob/164bda086fa76966239dcba3fda82c9f5c6bbb24/amazonka-s3/src/Network/AWS/S3/Internal.hs#L116-L130) are some preliminary combinators, have a look and feel free to bike shed over naming + API etc, I'm not particularly set on anything.

The internal representation is less than ideal, but I also have no strong opinions either way  there.

**Comment by kim** [comment]
:+1:
