### ISSUE TITLE
Maybe release 0.3.6.1 w/ T2.Large instances?

### ISSUE THREAD

**Issue by dysinger** [brendanhay/amazonka#147]

**Comment by brendanhay** [comment]
I can hotfix `0.3.6` sometime later today, if the timing is suitable.

**Comment by proger** [comment]
Could you squeeze in M4 instances too please?

**Comment by brendanhay** [comment]
Sure, I'll regenerate from the latest service definitions. If that goes without a hitch everything should be updated and I'll release `0.3.7` - otherwise I'll backport just the updated `InstanceType` constructors as `0.3.6.1`.

**Comment by brendanhay** [comment]
The updated `InstanceType` can be found in [0.3.6.1](http://hackage.haskell.org/package/amazonka-ec2-0.3.6.1/docs/Network-AWS-EC2-Types.html#g:103) on Hackage.

Only `amazonka-ec2` has been updated to some of the other libraries requiring more work relative to the update service definitions to safely release.

Let me know if you have any problems. I'll keep the `0.3-series` branch around in case any further updates are needed.

**Comment by proger** [comment]
Thank you very much!
