### ISSUE TITLE
Seconds/microseconds confusion in service timeouts

### ISSUE THREAD

**Issue by rjmac** [brendanhay/amazonka#153]
On develop, most (all?) services have their default `_svcTimeout` set to `Just 70000000`, which looks like it is intended to be 70 seconds expressed in microseconds.  The `_svcTimeout` field is of type `Seconds`, however.  In addition, they are being converted back to a number of microseconds for http-client's use by dividing the value by 1000000 (in `microseconds :: Seconds -> Int`).  As a result, http-client is only willing to wait 70µs for a response from AWS.

**Comment by brendanhay** [comment]
Thanks!

**Comment by brendanhay** [comment]
Oops!
