### ISSUE TITLE
Develop creates x-amz-dates with "UTC" instead of "Z"

### ISSUE THREAD

**Issue by rjmac** [brendanhay/amazonka#154]
On `develop`, amazonka is generating x-amz-date headers like `20150730T143802UTC` when signing requests, causing the error (at least, using the Oregon region) "AWS authentication requires a valid Date or x-amz-date header" to be returned.  This doesn't happen in 0.3.x because the format there has "Z" instead of "%Z" in that the `AWSTime` formatting instance.  Changing it back to that allows the request to proceed.

**Comment by rjmac** [comment]
Actually, it allowed the request to proceed a few days ago.  Now the signature is being computed incorrectly (as of b4a49c3); I'll open a separate issue for that.

**Comment by brendanhay** [comment]
Thanks. I'll look into the signature calculation first.
