### ISSUE TITLE
Incorrect signature computation

### ISSUE THREAD

**Issue by rjmac** [brendanhay/amazonka#155]
As of commit b4a49c352b, the signature is being computed incorrectly for my requests.  The access key I'm using does contain the characters "/" and "+", and that commit did change the way query strings are generated.  This key isn't super-secret; I can share it privately if you'd like for reproduction purposes if the cause isn't clear.

**Comment by brendanhay** [comment]
Thanks, if you can contact me via the email in the licensing header it'd be appreciated.

**Comment by rjmac** [comment]
Actually thinking about it, I don't think it's specific to this key.  `listBuckets` still works (that's not something the program which uses that key ordinarily does), and the only thing that changed in b4a49c3 is a separator that looked superfluous (but apparently wasn't) got removed.

**Comment by brendanhay** [comment]
Perfect. It's because the rendering of the `Query` type for both signing + the actual request is shared by that type, I'd planned at some point to separate those two code paths - I guess now is the time. Thanks!

**Comment by brendanhay** [comment]
It turned out to be re-encoding `/` delimiters in `ObjectKey`s during signing. I'm able to run a few operations such as `ListObjects`, `PutObject`, and `GetObjects` in the `feature/signer-updates` branch successfully.

I'll need to add some more tests before merging.

**Comment by rjmac** [comment]
`ListObjects` (and `ListMultipartUploads`) are both still failing for me with an "invalid signature" error as of ab9dd2dde3.  What information can I get you to find out what's different about our tests?

**Comment by brendanhay** [comment]
Not cool! Can you please send me some info privately?

I'll need the region, any buckets names, and some object keys for the failing requests. You could also send me some of the log output - just please scrub you secret key if they're traces.

**Comment by rjmac** [comment]
Yes, I can.  I've just sent that info in email.  It has the exact code being used and the highest detail log output (which didn't seem to contain the secret key anywhere, incidentally).

**Comment by brendanhay** [comment]
Excellent, thanks.
