### ISSUE TITLE
Provide additional endpoints + service configuration for AWS compatible services

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#158]
Currently the default `Service` configuration and `Network.AWS.Endpoint` in `amazonka-core` provide AWS specific endpoints and signers.

It'd be easy enough to provide simplified construction of configuration for Eucalyptus, RiakCS, and other services that offer AWS compatibility.

**Comment by adbrowne** [comment]
Hey Brendan,

Would this make it easy to use DynamoDB local as well? I cannot work out how to do that at the moment.

cheers Andrew

**Comment by brendanhay** [comment]
Can you point me to the local service you're running to mock/spoof Dynamo, if open source? I'll see if I can get it running and provide an example.

**Comment by adbrowne** [comment]
This one: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.DynamoDBLocal.html
It's a java program that uses sqllite to simulate dynamo.

**Comment by brendanhay** [comment]
I was about to say 'it works!' and exhibit a magnificent example - but alas, I appear to have no made provision for actually modifying the port. I've made some changes in `develop` and it appears to be working for some minor operations such as `Scan` + `ListTables`.

**Comment by brendanhay** [comment]
An example is [here](https://github.com/brendanhay/amazonka/blob/fd56eefdb78cc348cf66a1da0f2eb51b8918bdc7/examples/src/Example/DynamoDB.hs#L37). It's using `paginateWith`, identical use for `sendWith/awaitWith`. You'll need to import the `Control.Monad.Trans.AWS` module and use `liftAWS` if you're using `Network.AWS`.

The `*With*` variants documentation is [here](http://www.brendanhay.nz/amazonka-doc/amazonka/Control-Monad-Trans-AWS.html#g:8).  The available `Service` configuration is [here](http://www.brendanhay.nz/amazonka-doc/amazonka-core/Network-AWS-Types.html#g:5), now with lenses for most of the fields as well as `endpointHost` / `endpointPort` etc. Documentation for those is still building.

**Comment by brendanhay** [comment]
Also, to run the examples you'll need to `stack build/ghci amazonka-examples` and then:

```haskell
λ: import Example.DynamoDB 
λ: printTables Frankfurt (Just ("localhost", 8000))
Listing all tables in region eu-central-1
[Client Request] {
  host      = localhost:8000
  secure    = False
  method    = POST
  target    = Just DynamoDB_20120810.ListTables
  timeout   = Just 70000000
  redirects = 0
  path      = /
  query     = 
  headers   = host: localhost; ...
  body      = {"ExclusiveStartTableName":null,"Limit":null}
}
[Client Response] {
  status  = 200 OK
  headers = content-type: application/x-amz-json-1.0;
     x-amz-crc32: 1315925753;
     x-amzn-requestid: 941d667d-77c8-4313-9247-e50f109beb5d;
     content-length: 17;
     server: Jetty(8.1.12.v20130726)
}
[Raw Response Body] {
{"TableNames":[]}
}
```

**Comment by brendanhay** [comment]
I'll add a mechanism for overriding it globally shortly, rather than per request.

**Comment by brendanhay** [comment]
I've addded some [additional sugar](https://github.com/brendanhay/amazonka/blob/feature/service-override/examples/src/Example/DynamoDB.hs#L37) in a separate branch. It allows override the endpoint in the initial `Env` or via a scoped `endpoint` function similar to `within`.

**Comment by adbrowne** [comment]
Thanks Brendan. Now working with DynamoDB local!

**Comment by endgame** [comment]
Given that we've moved to pattern synonyms (#597), we're no longer bound to AWS-specific constants for stuff like regions. The tools in [`Network.AWS.Endpoint`](https://github.com/brendanhay/amazonka/blob/27e5fb472139b685244d4fdcc0eba50e04e24b4b/amazonka/src/Network/AWS/Endpoint.hs) also let us point requests at other services, so does that mean all the primitives are in place?

@brendanhay I suggest that supporting every AWS-"compatible" service out of the box is outside of `amazonka`'s scope. Keeping pace is enough of a maintenance burden as is. If someone else wants to maintain `amazonka-s3-objectstores` that provides `Service` definitions for Wasabi/B2/R2/..., that's great: we should make sure there's enough flexibility in the `Env` and `Service` structures to do this. If there isn't, then that's a bug they can open and we can fix later.
