### ISSUE TITLE
Amazon Cloud Drive

### ISSUE THREAD

**Issue by joeyh** [brendanhay/amazonka#168]
Users request I add Amazon Cloud Drive support to git-annex, so if it can be added to amazonka's suite of APIs, that would be awesome.

https://developer.amazon.com/public/apis/experience/cloud-drive/

**Comment by brendanhay** [comment]
As I'm not familiar with the REST API for CloudDrive I'll have to dig around a bit to get a feel for how much work it'd be before promising anything. I'll keep you posted.

**Comment by endgame** [comment]
Amazon Cloud Drive appears to have been renamed to Amazon Drive and deprecated: https://developer.amazon.com/docs/amazon-drive/ad-restful-api.html

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391

Closing this.
