### ISSUE TITLE
Replacement for paginateCatch in 1.x?

### ISSUE THREAD

**Issue by proger** [brendanhay/amazonka#175]
What is the proper replacement for `paginateCatch` in 1.0.0+?

My understanding of the transformer stack is not exactly good yet, and it seems that the only viable way is inlining `try` inside `paginateWith`. (Conduit's combinator operates on return values and not on outputs)

**Comment by proger** [comment]
OTOH running `try` outside the paginate action is not a big problem too.

**Comment by brendanhay** [comment]
I'd thought `tryC` etc from `Data.Conduit` would be sufficient - but of course looking into it in more depth, it's always going to short circuit at the first error.

Do you need short circuiting - ie. yield the first error and then quit the conduit? If so then one of `exceptions-Control.Monad.Catch.try`, `lens-Control.Exception.Lens.trying _Error`, or `conduit-Data.Conduit.tryC` should be what you need.

**Comment by proger** [comment]
Thanks! That should be sufficient.
