### ISSUE TITLE
Misleading documentation for EC2.ImportKeyPair

### ISSUE THREAD

**Issue by proger** [brendanhay/amazonka#176]
http://hackage.haskell.org/package/amazonka-ec2-1.0.1/docs/src/Network-AWS-EC2-ImportKeyPair.html#ikpPublicKeyMaterial

Looks like smart base64 encoding is a recent feature, however the documentation comes from AWS.

**Comment by brendanhay** [comment]
Right, thanks for bringing this up. Not entirely sure how to deal with it - maybe overriding the help text, or I could intelligently (due to the use of the `_Base64` iso) append a note saying that Base64 encode/decode is managed for you.

You found this out due to double-encoding?

**Comment by proger** [comment]
I found this during refactoring from 0.3-series to 1.0 and spotted the types changed; I haven't actually tested how it works yet.

**Comment by brendanhay** [comment]
OK - so the intention is that you pass a raw `ByteString` to the `Lens`, and the actual `Base64` encoding is taken care of during serialisation and deserialisation.

**Comment by proger** [comment]
Yep, and this is quite awesome — however I suppose the docs should be more clear on that (funny OT thing is i remember boto-based aws-cli suffered from trying to base64 encode files if passed a file path and expecting a base64 string otherwise at some point, yay types)

**Comment by brendanhay** [comment]
Cool, I'll look into generating a note appended to the documentation for every member that uses the underlying `Base64` type

**Comment by brendanhay** [comment]
An example of the annotated help for lenses which manage encoding via the `_Base64` iso is [here](https://github.com/brendanhay/amazonka/blob/283ad2c4d3ca660d3e6eb7c434964dd39ec71231/amazonka-ec2/gen/Network/AWS/EC2/ImportKeyPair.hs#L98-L102).

**Comment by brendanhay** [comment]
Ah shit, spelling mistake included. ;)
