### ISSUE TITLE
EC2 Credentials discovery chain breaks without a home directory.

### ISSUE THREAD

**Issue by romanb** [brendanhay/amazonka#184]
When running amazonka on an EC2 instance as a user without a home directory, with the intention to have the credentials be discovered from the instance metadata, the discovery chain fails early due to a missing home directory / `HOME` not being set: `HOME: getHomeDirectory: does not exist (no environment variable)`.

**Comment by brendanhay** [comment]
Thanks. As mentioned on slack, this is incorrect behaviour. It should in fact fail and fall through to the next discovery case - IAM profile information.

**Comment by brendanhay** [comment]
The fix is available on Hackage as part of [1.1.0](http://hackage.haskell.org/package/amazonka-1.1.0).
