### ISSUE TITLE
Null attributes should be omitted for Dynamo

### ISSUE THREAD

**Issue by adbrowne** [brendanhay/amazonka#192]
I've logged this as Dynamo for the moment but this could be other APIs as well.

When encoding requests null values should not be sent.

ie Currently it will send the body of PutItem like this:
body      = {"ExpressionAttributeNames":null,"ReturnValues":null,"ExpressionAttributeValues":null,"ReturnConsumedCapacity":null,"ReturnItemCollectionMetrics":null,"ConditionExpression":null,"Item":{"eventNumber":{"N":"0"},"streamId":{"S":"Brownie"}},"ConditionalOperator":null,"Expected":null,"TableName":"testtable-5469046236"}

When it should be like:
body = {"Item":{"eventNumber":{"N":"0"},"streamId":{"S":"Brownie"}},"TableName":"testtable-5469046236"}

Sending nulls causes the API to give a 400 response.

I found got it work by editing the generated ToJSON instance to filter out null values. I started playing around with the generator code but wasn't sure if there was a nice way to only apply this only to select ToJSON instances. Happy to work on a PR for this if you can point me in the right direction. I can easily change it globally in Syntax.hs but I'm presuming that would have too wide an impact.

**Comment by brendanhay** [comment]
Shit. Apologies - I'd thought I'd long fixed this. I'm going to write up some failing tests before implementing any fixes now. Regarding your changes to `Syntax.hs`, were you changing the definition for `toJSOND/E` or something else?

**Comment by brendanhay** [comment]
An example of how `Data.Aeson.TH/Generics` does it:

```haskell
{-# LANGUAGE TemplateHaskell #-}

{-# OPTIONS_GHC -ddump-splices #-}

module Test where

import           Data.Aeson
import           Data.Aeson.TH
import           Data.Maybe
import qualified Data.Text     as Text

data Foo = Foo
    { _foo1 :: Int
    , _foo2 :: Maybe Double
    } deriving (Eq, Show)

deriveJSON defaultOptions { omitNothingFields = True } ''Foo
```

Emits:

```haskell
instance ToJSON Foo where
    toJSON = \value_a12iV ->
        case value_a12iV of
            Foo arg1_a12iW arg2_a12iX ->
                object . catMaybes $
                    [ ((Text.pack "_foo2" .=) <$> arg2_a12iX)
                    ] ++
                    [ ((Text.pack "_foo1") .= arg1_a12iW)
                    ]
```

**Comment by brendanhay** [comment]
I'll work on emitting the above `catMaybes` approach from the generated code. Let me know if you had a different approach in mind, for comparison.

**Comment by brendanhay** [comment]
Oops, auto-closed.

**Comment by brendanhay** [comment]
The commit in 7ae4737 ouputs the following `ToJSON` instance for `PutItem`:

```haskell

instance ToJSON PutItem where
        toJSON PutItem'{..}
          = object
              (catMaybes
                 [("ReturnValues" .=) <$> _piReturnValues,
                  ("ExpressionAttributeNames" .=) <$>
                    _piExpressionAttributeNames,
                  ("ReturnConsumedCapacity" .=) <$>
                    _piReturnConsumedCapacity,
                  ("ExpressionAttributeValues" .=) <$>
                    _piExpressionAttributeValues,
                  ("ReturnItemCollectionMetrics" .=) <$>
                    _piReturnItemCollectionMetrics,
                  ("ConditionExpression" .=) <$>
                    _piConditionExpression,
                  ("ConditionalOperator" .=) <$>
                    _piConditionalOperator,
                  ("Expected" .=) <$> _piExpected,
                  Just ("TableName" .= _piTableName),
                  Just ("Item" .= _piItem)])
```

**Comment by brendanhay** [comment]
Sample (pretty-printed) output using the updated instances in `develop`:

```haskell
[Client Request] {
  host      = dynamodb.eu-central-1.amazonaws.com:443
  secure    = True
  method    = POST
  target    = Just DynamoDB_20120810.Query
  timeout   = Just 70000000
  redirects = 0
  path      = /
  query     = 
  headers   = host: dynamodb.eu-central-1.amazonaws.com; ...
  body      =
      {
      "TableName": "credential-store",
      "Limit": 1,
      "ScanIndexForward": false,
      "ConsistentRead": true,
      "KeyConditions": {
        "name": {
          "ComparisonOperator": "EQ",
          "AttributeValueList": [
            {
              "S": "foo"
            }
          ]
        }
      }
    }
}
[Client Response] {
  status  = 200 OK
  headers = x-amzn-requestid: A7MKEMVQ8MGJ9GGU6OV0BP81NBVV4KQNSO5AEMVJF66Q9ASUAAJG; x-amz-crc32: 2794111476; content-type: application/x-amz-json-1.0; content-length: 618; date: Sun, 23 Aug 2015 14:05:32 GMT
}
[Raw Response Body] {
...
}

[Client Request] {
  host      = dynamodb.eu-central-1.amazonaws.com:443
  secure    = True
  method    = POST
  target    = Just DynamoDB_20120810.PutItem
  timeout   = Just 70000000
  redirects = 0
  path      = /
  query     = 
  headers   = host: dynamodb.eu-central-1.amazonaws.com; ...
  body      =
  {
  "TableName": "...",
  "Expected": {
    "version": {
      "Exists": false
    }
  },
  "Item": {
    "version": {
      "N": "10"
    },
    "hmac": {
      "B": "..."
    },
    "name": {
      "S": "foo"
    },
    "key": {
      "B": "..."
    },
    "contents": {
      "B": "..."
    }
  }
}
}
```

**Comment by adbrowne** [comment]
Thanks @brendanhay. What you have done looks very similar to what I did by hand. Testing this branch out now.

**Comment by adbrowne** [comment]
Testing and it's working really well. Have completely replaced all my https://hackage.haskell.org/package/aws with amazonka now and all tests are passing.

This exercises: 
* CreateTable
* GetItem
* PutItem
* Query
* Scan
* UpdateItem

Thanks again @brendanhay

**Comment by brendanhay** [comment]
Great! Glad to hear that it works. :sparkles:
