### ISSUE TITLE
QueueAttributeName is used instead of missing MessageAttributeName

### ISSUE THREAD

**Issue by EduardSergeev** [brendanhay/amazonka#199]
[QueueAttributeName](https://github.com/brendanhay/amazonka/blob/73ad00369ac3024d6ca6ac212ba33f01233a1de4/amazonka-sqs/gen/Network/AWS/SQS/Types/Sum.hs#L22-L36) is used to [represent a set of "would be" MessageAttributes](https://github.com/brendanhay/amazonka/blob/develop/amazonka-sqs/gen/Network/AWS/SQS/ReceiveMessage.hs#L100).
The correct set of `MessageAttributes` is [as per comments](https://github.com/brendanhay/amazonka/blob/develop/amazonka-sqs/gen/Network/AWS/SQS/ReceiveMessage.hs#L166-L177):
 * `All` - returns all values.
 * `ApproximateFirstReceiveTimestamp` - returns the time when the message was first received from the queue (epoch time in milliseconds).
 * `ApproximateReceiveCount` - returns the number of times a message has been received from the queue but not deleted.
 * `SenderId` - returns the AWS account number (or the IP address, if anonymous access is allowed) of the sender.
 * `SentTimestamp` - returns the time when the message was sent to the queue (epoch time in milliseconds).

Looks like Amazon documentation [is incorrect](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html) since it enumerates QueueAttributes as valid values for MessageAttributes.

**Comment by brendanhay** [comment]
I believe this is the same issue raised upstream: https://github.com/boto/botocore/issues/602

**Comment by brendanhay** [comment]
Short term, I may just construct an override to correct the enum branches.

**Comment by brendanhay** [comment]
Leaving this open due to other potentially issues. Really needs to be fixed upstream, but in the meantime I'll add overrides as I become aware of the cases.
