### ISSUE TITLE
Treat 3xx responses as successes

### ISSUE THREAD

**Issue by romanb** [brendanhay/amazonka#2]
Either generally or at least for S3 responses, 3xx codes should be treated as a success to allow client code to identify with `304` responses when using ETags as well as other use-cases involving 3xx response codes.

I already made this change on [master](https://github.com/brendanhay/amazonka/commit/efc894b008626eed55b73900a5de5fa9b65dd279) but am creating this issue as a reminder that this behaviour should be retained (or generalised for all AWS responses) in the upcoming changes on the `gen` branch.

**Comment by AriFordsham** [comment]
301 is a redirect and not a valid response unless correctly handled. Amazon is uding these - see #630
