### ISSUE TITLE
amazonka-core fails to build

### ISSUE THREAD

**Issue by ababkin** [brendanhay/amazonka#208]
Building amazonka-core-1.2.0.2...
Preprocessing library amazonka-core-1.2.0.2...
[ 1 of 28] Compiling Network.AWS.Data.Crypto ( src/Network/AWS/Data/Crypto.hs, dist/dist-sandbox-c10633e8/build/Network/AWS/Data/Crypto.o )
[ 2 of 28] Compiling Network.AWS.Data.Text ( src/Network/AWS/Data/Text.hs, dist/dist-sandbox-c10633e8/build/Network/AWS/Data/Text.o )
[ 3 of 28] Compiling Network.AWS.Data.JSON ( src/Network/AWS/Data/JSON.hs, dist/dist-sandbox-c10633e8/build/Network/AWS/Data/JSON.o )
[ 4 of 28] Compiling Network.AWS.Data.ByteString ( src/Network/AWS/Data/ByteString.hs, dist/dist-sandbox-c10633e8/build/Network/AWS/Data/ByteString.o )
[ 5 of 28] Compiling Network.AWS.Data.Query ( src/Network/AWS/Data/Query.hs, dist/dist-sandbox-c10633e8/build/Network/AWS/Data/Query.o )
[ 6 of 28] Compiling Network.AWS.Data.XML ( src/Network/AWS/Data/XML.hs, dist/dist-sandbox-c10633e8/build/Network/AWS/Data/XML.o )
[ 7 of 28] Compiling Network.AWS.Data.List1 ( src/Network/AWS/Data/List1.hs, dist/dist-sandbox-c10633e8/build/Network/AWS/Data/List1.o )

src/Network/AWS/Data/List1.hs:64:36:
    Couldn't match type ‘Item Array’ with ‘Value’
    Expected type: Array
                   -> aeson-0.9.0.1:Data.Aeson.Types.Internal.Parser (List1 Value)
      Actual type: Array
                   -> aeson-0.9.0.1:Data.Aeson.Types.Internal.Parser
                        (List1 (Item Array))
    In the first argument of ‘(>=>)’, namely ‘go’
    In the second argument of ‘withArray’, namely
      ‘(go >=> traverse parseJSON)’

src/Network/AWS/Data/List1.hs:69:14:
    Could not deduce (IsList Array) arising from a use of ‘toList’
    from the context (FromJSON a)
      bound by the instance declaration
      at src/Network/AWS/Data/List1.hs:63:10-41
    In the second argument of ‘(.)’, namely ‘toList’
    In the second argument of ‘(.)’, namely
      ‘NonEmpty.nonEmpty . toList’
    In the expression:
      maybe
        (fail
           "Error parsing empty List1 when expecting at least one element.")
        (pure . List1)
      . NonEmpty.nonEmpty . toList
cabal: Error: some packages failed to install:
amazonka-1.2.0.2 depends on amazonka-core-1.2.0.2 which failed to install.
amazonka-core-1.2.0.2 failed during the building phase. The exception was:
ExitFailure 1
amazonka-sns-1.2.0.2 depends on amazonka-core-1.2.0.2 which failed to install.
xds-downloader-0.1.0.0 depends on amazonka-core-1.2.0.2 which failed to
install.

**Comment by brendanhay** [comment]
Could you supply some information about the GHC version + build steps (cabal / stack) you are using?

**Comment by ababkin** [comment]
GHC 7.8.3, OSX, standard cabal (1.22) build
Please let me know if you need more details

**Comment by brendanhay** [comment]
It appears to be a `vector` dependency issue. It didn't receive a `GHC.Exts.IsList/Item` instance until `>= 0.10.12.*`. Rather than constraining the version, I've added the fix in 4ee1738.

**Comment by ababkin** [comment]
Thanks. Curious when you are planning to release this fix in hackage?

**Comment by brendanhay** [comment]
Probably not until the end of the week (say Thurs/Fri), I'd like to get a couple of other things in if possible.
