### ISSUE TITLE
Malformed SNS Subscribe request

### ISSUE THREAD

**Issue by lostman** [brendanhay/amazonka#209]
I've been getting a rather cryptic `Start of list found where not expected` error when attempting to subscribe to SNS topic:

```Haskell
res <- runTokyoDebug $ AWS.send $
    SNS.subscribe topic "sqs"
        & SNS.subEndpoint .~ Just (
            SNS.endpoint & SNS.eEndpointARN .~ Just arn
        )
```

The request body is:

```
Action=Subscribe&Endpoint.EndpointArn=...&Protocol=sqs&TopicArn=...&Version=2010-03-31
```

while request body from `aws-sdk-go` looks like this:

```
Action=Subscribe&Endpoint=...&Protocol=sqs&TopicArn=...&Version=2010-03-31
```

The only difference I can spot is `Endpoint.EndpointArn=` vs `Endpoint=`.

The full error message is:

```
[ServiceError] {
  service    = SNS
  status     = 400 Bad Request
  code       = MalformedInput
  message    = Just Start of list found where not expected
}
```

**Comment by brendanhay** [comment]
Thanks, I'll look into it.

**Comment by brendanhay** [comment]
`Endpoint` is being confused with `endpoint` during generation (they are disparate SNS types), apologies. I'll work on a fix and see if I can get something pushed shortly.

**Comment by brendanhay** [comment]
The fix is now in `develop`. It will be released at some point in the next week as part of a `1.3.*` series release.
