### ISSUE TITLE
defaultForAz may not exist in CreateSubnetResponse

### ISSUE THREAD

**Issue by phunehehe** [brendanhay/amazonka#221]
Seems like it won't be there when the subnet is `pending`

```
[Raw Response Body] {
<?xml version="1.0" encoding="UTF-8"?>
<CreateSubnetResponse xmlns="http://ec2.amazonaws.com/doc/2015-04-15/">
    <requestId>61ed7dd0-77bc-474a-8f63-3ae874eed50e</requestId>
    <subnet>
        <subnetId>subnet-2103ba48</subnetId>
        <state>pending</state>
        <vpcId>vpc-745df71d</vpcId>
        <cidrBlock>10.247.0.0/18</cidrBlock>
        <availableIpAddressCount>16379</availableIpAddressCount>
        <availabilityZone>eu-central-1a</availabilityZone>
    </subnet>
</CreateSubnetResponse>
}
```

I'm not sure what will be a nice way to cope with this. `Maybe Bool`?

**Comment by brendanhay** [comment]
Out of interest, which `Region` are you running in?

**Comment by phunehehe** [comment]
I'm not sure what you mean. The VPC is in eu-central-1.

**Comment by phunehehe** [comment]
eab4b590e0378c6b9af8fe5f04711d4d1851d99d seems to help, but then there is the same problem with `mapPublicIpOnLaunch`.
Almost unrelated, but is `gen` currently broken?

```
src/Gen/Types/Orphans.hs:51:10:
    Duplicate instance declarations:
      instance ToJSON a => ToJSON (Identity a)
        -- Defined at src/Gen/Types/Orphans.hs:51:10
      instance [incoherent] ToJSON a => ToJSON (Identity a)
        -- Defined in ‘aeson-0.9.0.1:Data.Aeson.Types.Instances’
```

**Comment by phunehehe** [comment]
(I made a change for `mapPublicIpOnLaunch` and want to confirm whether it works before submitting a PR)

**Comment by brendanhay** [comment]
Not that I'm aware of, you'll have to share details of how you're building it. Are you using `stack`? It looks like `aeson` has been updated to include an instance for `Identity` which it previously didn't have.

**Comment by phunehehe** [comment]
Ah right, probably just because I'm not using Stack :)
How do you run `gen` actually?

**Comment by brendanhay** [comment]
The `Makefile` has targets for `gen` and `format`, to generate and format the code respectively. The use `stack` under the hood.

There appear to have been some upgrades to `aeson`, so I'm working on removing the orphan instance and constraining the dependencies to the appropriate version now.

**Comment by brendanhay** [comment]
Sorry, auto-closed.

**Comment by brendanhay** [comment]
I've updated the `ToJSON` `Identity` instance to be conditional on the version of `aeson` that provides one. It might help with your build issue.

I'll also commit the change to `mapPublicIpOnLaunch` and regenerate the service in `develop` for expediency.

**Comment by phunehehe** [comment]
I didn't notice the makefile inside gen. Will try with `develop` again.
While it's nice that I can now build without commenting out the additional instance, I don't think it's worth cluttering the code to accommodate a non-standard setup such as mine. Feel free to remove it later if you want :)

**Comment by phunehehe** [comment]
It works now. Thanks!
