### ISSUE TITLE
S3 GetBucketPolicy returns Json 

### ISSUE THREAD

**Issue by nhibberd** [brendanhay/amazonka#224]
Seems to be the only S3 response return Json -- http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETpolicy.html.

**Comment by brendanhay** [comment]
Pasting the discussion with @charleso:

* The `Policy` type (which is a primitive string) is set as `"payload": "Policy`" on the `GetBucketPolicyOutput` shape - meaning it is returned in the response body, here: https://github.com/boto/botocore/blob/ee99c1c7cc3f5f9326de71004bd7967548d9ba35/botocore/data/s3/2006-03-01/service-2.json#L2064
* Boto then just returns this as a string https://github.com/boto/botocore/blob/ee99c1c7cc3f5f9326de71004bd7967548d9ba35/botocore/data/s3/2006-03-01/service-2.json#L3634

So boto is just consuming the response body as a string and then you need to JSON parse it. (Or whatevers.)

The generator is not taking into account the payload + primitive type interplay here, so I'll fix that shortly.
