### ISSUE TITLE
S3 GetBucketLogging xml response

### ISSUE THREAD

**Issue by nhibberd** [brendanhay/amazonka#228]
[getBucketLocation](https://hackage.haskell.org/package/amazonka-s3-1.3.2/docs/Network-AWS-S3-GetBucketLocation.html) always returns `Nothing`. Looks like it is expecting a nested xml object but it only exists at the top level?

Example code
```
getLocation' :: BucketName -> AWS (Maybe Region)
getLocation' n = do
  r <- send $ getBucketLocation  n
  pure $ r ^. grsLocationConstraint
```

Raw response
```
[Client Response] {
  status  = 200 OK
  ...
}
[Raw Response Body] {
<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/">ap-southeast-2</LocationConstraint>
}
```

**Comment by brendanhay** [comment]
It'll be a few hours before I can look into this, I'll keep you posted.

**Comment by brendanhay** [comment]
By a few hours, I mean 14 days.
