### ISSUE TITLE
Support for reading from EC2 meta-data?

### ISSUE THREAD

**Issue by greglearns** [brendanhay/amazonka#231]
Does Amazonka support reading credential data from meta-data if it is launched on an EC2 instance? (For background and details: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html).

This blog entry talks about how, if code is launched on a EC2 instance, the credentials can be read from the instance's meta-data (because, the credentials are rotated every few hours): 

http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs

```
If the code is running on an EC2 instance, via an IAM role for Amazon EC2. In that case,
the code gets temporary security credentials from the instance metadata service;
the credentials have the permissions derived from the role that is associated with the instance.
```

Amazonka looks amazing. I'm looking forward to using it (as a Haskell noob) :-)

**Comment by brendanhay** [comment]
Yes, when constructing a new environment for use with `runAWS` using [`Discover`](https://github.com/brendanhay/amazonka/blob/173cbc3bde012e4a3ab1dae7157be9627ffca7b1/amazonka/src/Network/AWS/Auth.hs#L150), `amazonka` will transparently try, in order:

* [Environment variables](https://github.com/brendanhay/amazonka/blob/173cbc3bde012e4a3ab1dae7157be9627ffca7b1/amazonka/src/Network/AWS/Auth.hs#L88-L98).
* A [Credentials file](https://github.com/brendanhay/amazonka/blob/173cbc3bde012e4a3ab1dae7157be9627ffca7b1/amazonka/src/Network/AWS/Auth.hs#L100-L133).
* [EC2 instance metadata](https://github.com/brendanhay/amazonka/blob/173cbc3bde012e4a3ab1dae7157be9627ffca7b1/amazonka/src/Network/AWS/Auth.hs#L398-L461). (IAM Profile.)

All of the above correspond to the other offical SDK defaults in terms of naming + behaviour.

For example:

```haskell
e <- newEnv Frankfurt Discover
runAWS e $ do
    ...
```

Will try the previously mentioned steps to obtain credentials. So if the code is running on EC2 and the metadata endpoint is available, those credentials will be used including the temporary security token and its related expiry time. A worker will be forked to ensure the credentials are transparently refreshed before they expire.

**Comment by greglearns** [comment]
Nice!

**Comment by brendanhay** [comment]
I'll close this for now. If you have more questions feel free to re-open or create a new issue, you can also use the [Gitter chat](gitter.im/brendanhay/amazonka).
