### ISSUE TITLE
SWF - SimpleWorkflowService.RespondDecisionTaskCompleted fails

### ISSUE THREAD

**Issue by mfine** [brendanhay/amazonka#236]
I'm moved my amazonka SWF project over to stack, meaning I'm on `0.3.6` (which I was using before). A number of the API calls are working fine, but `RespondDecisionTaskCompleted` fails - I get `FailedConnectionException` errors:

```
[Amazonka Env] {
  region      = us-east-1
  retry (n=0) = Nothing
  [Amazonka Auth] {
    access key     = ####
    secret key     = ****
    security token = Nothing
    expiry         = Nothing
  }
}
[Client Request] {
  host              = swf.us-east-1.amazonaws.com
  port              = 443
  secure            = True
  headers           = authorization: AWS4-HMAC-SHA256 Credential=####/20151008/us-east-1/swf/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=$$$$; content-type: application/x-amz-json-1.0; host: swf.us-east-1.amazonaws.com; x-amz-date: 20151008T061529Z; x-amz-target: SimpleWorkflowService.RespondDecisionTaskCompleted
  path              = /
  query             = ?
  method            = POST
  redirect count    = 10
  response timeout  = Just -3425
  request version   = HTTP/1.1
}
[Retrying] after 1 attempts.
HttpError (FailedConnectionException "swf.us-east-1.amazonaws.com" 443)
```

I'm now in the process of trying to update to newer amazonka builds (`1.3.2`), but was curious if there might be a quick answer here around why only one of the API's is failing so far.

Definitely close this out if this is from too old stuff :)

**Comment by brendanhay** [comment]
Humm. The host/port all look fine - `http-client` will throw `FailedConnectionException` when connecting to the endpoint fails.

Unfortunately I can't see any further into it - unless SWF is mysteriously not accepting HTTPs connections? I'm also assuming you have no other network issues?

**Comment by mfine** [comment]
It's just for that operation so far - which is what's weird. The other operations I send in work fine:

```
[Amazonka Env] {
  region      = us-east-1
  retry (n=0) = Nothing
  [Amazonka Auth] {
    access key     = ####
    secret key     = ****
    security token = Nothing
    expiry         = Nothing
  }
}
[Client Request] {
  host              = swf.us-east-1.amazonaws.com
  port              = 443
  secure            = True
  headers           = authorization: AWS4-HMAC-SHA256 Credential=####/20151008/us-east-1/swf/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=$$$$; content-type: application/x-amz-json-1.0; host: swf.us-east-1.amazonaws.com; x-amz-date: 20151008T061349Z; x-amz-target: SimpleWorkflowService.PollForActivityTask
  path              = /
  query             = ?
  method            = POST
  redirect count    = 10
  response timeout  = Just -3425
  request version   = HTTP/1.1
}
[Client Response] {
  status code    = 200
  status message = OK
  version        = HTTP/1.1
  headers        = x-amzn-requestid: be06d406-6d83-11e5-a7ce-89c55e9507c3; content-type: application/x-amz-json-1.0; content-length: 20
  cookies        = CJ {expose = []}
}
```

**Comment by mfine** [comment]
Upgraded to `1.3.2` and the API calls I'm making are all going through. Still perplexed by the above behavior and the failures just on `RespondDecisionTaskCompleted`. Closing this out.

Btw, the changes to the library look great! Really excited about how it's evolved in such a short time - the `timeout` stuff on the Env was a great way to fix our problem with configurable timeouts. Thanks again - and great work!

**Comment by brendanhay** [comment]
Very strange :persevere: - glad the newer version seems to fix things though. You might've seen already, but the default timeout is now 70 seconds, so you shouldn't have to reconfigure the timeouts for SWF unless needed.
