### ISSUE TITLE
Support for API Gateway

### ISSUE THREAD

**Issue by proger** [brendanhay/amazonka#240]
[API Gateway](http://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html) looks like a recent AWS service, and I can't seem to find the specs for it in [botocore](https://github.com/boto/botocore/tree/develop/botocore/data), however it goes contain IoT stuff already (which was announced just today).
Do you know if it's possible to support API GW?

Thanks

**Comment by proger** [comment]
Found some explanation about some mysterious "HAL" in https://github.com/boto/botocore/issues/607

**Comment by brendanhay** [comment]
Yeah, I was literally about to link that and saw your comment at the bottom. :smile:

**Comment by brendanhay** [comment]
Pretty sure they are not referring to this [HAL](https://en.wikipedia.org/wiki/HAL_9000), but to this [HAL](http://stateless.co/hal_specification.html).

**Comment by proger** [comment]
Out of curiosity, do you know if it's possible to retrieve at least the original HAL spec?
