### ISSUE TITLE
S3 GetBucketLocation fails when location is US Classic

### ISSUE THREAD

**Issue by tvh** [brendanhay/amazonka#249]
When the bucket's region is US Classic, Amazon S3 returns an empty string for the bucket's region:
```
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"/>
```

This results in the following error in `amazonka-s3`:
```
SerializeError (SerializeError' {_serializeAbbrev = Abbrev "S3", _serializeStatus = Status {statusCode = 200, statusMessage = "OK"}, _serializeMessage = "empty node list, when expecting single node Region"})
```

**Comment by tvh** [comment]
This would also fail if `LocationConstraint` is set to `EU`.

**Comment by brendanhay** [comment]
Thanks for reporting, I'll look into fixing it.

**Comment by tvh** [comment]
Related to this, `CreateBucket` will fail to work in `us-east-1` as well. According to http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html, it expects the value to be missing in this case.

**Comment by brendanhay** [comment]
Right, thanks. It seems the decision to replace the stringly-typed `BucketLocationConstraint` from the service definitions with the core `Region`-type was incorrect. I'll introduced a newtype for `Region` that can handle the expected de/serialisation behaviour.
