### ISSUE TITLE
TlsExceptionHostPort exceptions with amazonka in stackage

### ISSUE THREAD

**Issue by ck-luminal** [brendanhay/amazonka#269]
Hey Bren!

I was about to send you a PR for this and then realized I wouldn't be able to. Stackage appears to be using a newer version of `http-conduit` than the version fixed in amazonka's Cabal file. It turns out that version throws an additional type of TLS exception, `TlsExceptionHostPort` that you probably want to retry here as well: https://github.com/brendanhay/amazonka/blob/develop/amazonka/src/Network/AWS/Env.hs#L211 .

As an effect, we've seen this go uncaught occasionally:
```
TransportError (TlsExceptionHostPort (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher")) "s3.amazonaws.com" 443)
```

Not a critical issue for us (since we can declare a different retry handler that catches this), but I figured I'd give you a heads up.

**Comment by brendanhay** [comment]
Still as smooth as ever CK!

Thanks for raising this, I've added some CPP h(on)orrifics to deal with backwards compatibility - I'm going to hold off on merging until I can determine if the error makes sense to retry in the base library, since the error is being thrown by the `hs-tls` library dependency of `http-client`, more info [here].

**Comment by ck-luminal** [comment]
Awesome, thanks for taking a look at it. Btw, really enjoy working with this library... I got the chance to redo our CLI tool in haskell and its been super easy. We miss you at luminal bruh!

**Comment by brendanhay** [comment]
Neat sauce, interested to hear your experience with Haskell/libraries in general. I'll ping you on the glorious source of truth (FB) sometime!

**Comment by brendanhay** [comment]
This appears to be fixed with the new(er) versions of `tls`.  Feel free to reopen if the issue persists.

**Comment by AlexeyRaga** [comment]
I am still having this issue with a newest `tls-1.3.8`:

```
$ sqs-resurrector -q dead-letter-queue
[HttpException] {
TlsExceptionHostPort (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,IllegalParameter)]" " expected: change cipher")) "sqs.us-west-2.amazonaws.com" 443
}
sqs-resurrector: TransportError (TlsExceptionHostPort (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,IllegalParameter)]" " expected: change cipher")) "sqs.us-west-2.amazonaws.com" 443)

$ stack list-dependencies | grep tls                                                                 ⤬
http-client-tls 0.2.4.1
tls 1.3.8
```
