### ISSUE TITLE
cannot omit tag values for DeleteTags

### ISSUE THREAD

**Issue by oswynb** [brendanhay/amazonka#270]
In Network.AWS.EC2.DeleteTags, there is no way to omit the value of a tag, since the exposed lens requires a `[Tag]` : `dtsTags :: Lens' DeleteTags [Tag]` but `Tag` has compulsory keys and values: `tag :: Text -> Text -> Tag`, `tagValue :: Lens' Tag Text`

**Comment by brendanhay** [comment]
Hmm, seems like a problem with the service definition. What happens if the value is empty? Does EC2 still delete the tag or does it fail since the tag exists with a value?

**Comment by oswynb** [comment]
The expected behaviour is the tag with matching key will be deleted regardless of its value
