### ISSUE TITLE
Missing 'host' signed header from S3 presigned URL

### ISSUE THREAD

**Issue by spl** [brendanhay/amazonka#272]
I added the following function to `examples/src/Example/S3.hs`:

```haskell
module Example.S3 where
-- ...
import           Data.ByteString         (ByteString)
import           Data.Time
-- ...

getPresignedURL
  :: Region     -- ^ Region to operate in.
  -> BucketName
  -> ObjectKey  -- ^ The source object key.
  -> IO (ByteString)
getPresignedURL r b k = do
    lgr <- newLogger Debug stdout
    env <- newEnv r Discover <&> envLogger .~ lgr
    tm <- getCurrentTime
    runResourceT . runAWST env $ do
        presignURL tm 60 $ getObject b k
```

And I ran it in GHCi (output reformatted for readability):

```haskell
*Example.S3> getPresignedURL <region> "<bucket>" "<object-key>"
"https://s3.<region>.amazonaws.com/<bucket>/<object-key>
?X-Amz-Algorithm=AWS4-HMAC-SHA256
&X-Amz-Credential=<aws-secret-id>/20160225/<region>/s3/aws4_request
&X-Amz-Date=20160225T071228Z
&X-Amz-Expires=60
&X-Amz-SignedHeaders=
&X-Amz-Signature=<signature>"
```

And I copied the URL into a browser and received:

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>There were headers present in the request which were not signed</Message>
  <HeadersNotSigned>host</HeadersNotSigned>
  <RequestId>...</RequestId>
  <HostId>...</HostId>
</Error>
```

So, the `host` header is missing. The presigned URL [should](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html) have `X-Amz-SignedHeaders=host`.

Am I doing something wrong, or is there a bug?

**Comment by brendanhay** [comment]
Apologies for the delay, currently traveling. You issue definitely looks like a bug .. I'll try and get a fix out shortly.

**Comment by brendanhay** [comment]
I've added your example to the project (thanks!), and after spending a bit of time losing more hair as the example seems to output the correct headers, I realised it had already been fixed in `develop` by another contributor!

A new release will be going out in a few days, so the fix will be available in `>= 1.3.8`.

See: https://github.com/brendanhay/amazonka/pull/264

**Comment by spl** [comment]
Thanks! Sorry that I didn't see #264 before reporting.

**Comment by brendanhay** [comment]
No worries, thanks again for the example.
