### ISSUE TITLE
How do I deserialize unstructured "AttributeValue" data stored in DynamoDB?

### ISSUE THREAD

**Issue by statusfailed** [brendanhay/amazonka#282]
I'm storing some unstructured data in DynamoDB. For example, I this top-level Attribute value:

```
    "heterogeneous_array": {
      "L": [
        {
          "BOOL": false
        },
        {
          "N": "1"
        },
        {
          "S": "two"
        },
        {
          "M": {
            "three": {
              "N": "4"
            }
          }
        },
        {
          "L": [
            {
              "S": "five"
            }
          ]
        }
      ]
    },
```

amazonka-dynamodb helpfully parses this JSON response into the [AttributeValue](http://hackage.haskell.org/package/amazonka-dynamodb-1.4.0/docs/Network-AWS-DynamoDB.html#g:43) type.
However, it seems like it's impossible to tell from inspecting `AttributeValue` which fields are actually set: internally they're stored as `Maybe <type>`, but the lenses which expose them are ambiguous. For example: if I do `myAttributeValue ^. avL`, I get an empty list both when the object is not a `List`, and when it was a `List` with empty contents.

My current workaround is to turn the `AttributeValue` into an Aeson `Value`, turn that into an internal object like the one described in #263, then transform that back into a `Value`.

Is there a better solution that I'm missing? 

(I'm also linking #263 because I think a single good solution might exists for both problems.)

**Comment by brendanhay** [comment]
For the point about the ambiguous lenses - I definitely agree, either the full type needs to be exposed, (as in, `Maybe`) which makes some things considerably less nice to work with, or in your case access to the internal data constructor/fields aside from the lenses.

I'm not sold on using Aeson's `Value` as an intermediate representation, primarily because it doesn't support the full range of values that can be encoded in DynamoDB. Therefore it's still on the drawing board, but I'm definitely open to suggestions.

**Comment by statusfailed** [comment]
Yeah, I'm mostly going via `Value` because I don't have access to the library internals (and I didn't want to patch amazonka). I think `axman6`'s solution with the `AttrValue` type from #263 would work well for me, what do you think?

Also: thanks for a really great library!

**Comment by jdreaver** [comment]
@brendanhay would it be possible to expose the lenses with `Maybe` types, or even the internal record selectors that return `Maybe` values? I'm totally fine with `Value` as a representation for `AttributeValue` in my application, but given the current lenses I can't figure out if I have an empty `Object` or empty `Array` encoded in my `AttributeValue`.

Is there some workaround I can use for now?

Thanks for any help! I just started using `amazonka-dynamodb` and it's been totally awesome so far :smile:

**Comment by endgame** [comment]
I think some time after 2.0, we should consider using lenses that return `Maybe` for all `AttributeValue` options, and then either in `amazonka-dynamodb` (or maybe elsewhere) provide an AST type for dynamo values (and a `Prism` to convert between them).

**Comment by endgame** [comment]
I think #724 kills this dead by deserialising into a proper AST for AttributeValue.
