### ISSUE TITLE
NFData instances?

### ISSUE THREAD

**Issue by gregwebs** [brendanhay/amazonka#283]
I wanted to put a retry around sending a request to AWS. Unfortunately there are no NFData instances, so it is difficult for me to confidently trap an exception.

Is it possible to automatically generate NFData instances for everything?

**Comment by brendanhay** [comment]
Sure is. Been meaning to add them for a while, so I'll do it sometime over the weekend.

**Comment by brendanhay** [comment]
Unfortunately due to the use of conduit for some request/response types, NFData instances cannot be provided. I've attempted to generate them wherever else possible.

**Comment by brendanhay** [comment]
Let me know if this will cover your use case @gregwebs, and I'll look at cutting a release pending some other minor changes + CI.

**Comment by gregwebs** [comment]
Seems like a great improvement. However, I still have many *responses* without instances. some of which seem like they shouldn't have anything to do with conduits.

* SetDesiredCapacityResponse
* TerminateInstancesResponse
* DescribeSpotPriceHistoryResponse
* DetachInstancesResponse

**Comment by gregwebs** [comment]
Note that I cannot generate instances myself because smart constructors and exported instead of the data constructors.

**Comment by brendanhay** [comment]
Thanks for catching that, an error on my part. [ d75a122](https://github.com/brendanhay/amazonka/pull/284/commits/d75a122fed201154b62bfb783542a9adff999982#diff-5e5663b50852ee6099a98ba533183fbdR160) adds the expected response instances.

Does your latter comment imply you'd rather see fully exported types?

**Comment by gregwebs** [comment]
That's better!

This satisfies my only current use case for fully exported types. In general it can be nice to expose them at least from an Internal module so that a user can create instances.

**Comment by brendanhay** [comment]
I ask because it's not that I haven't exported them out of some misguided principle, it just requires some work to ensure that the `.Internal` style modules are generated - or that there isn't an additionally overwhelming amount of exports/imports (also Haddock) happening. I'll look into doing it as a somewhat low priority.

**Comment by brendanhay** [comment]
The `NFData` instances are available in `1.4.1` on [Hackage](http://hackage.haskell.org/package/amazonka-1.4.1).
