### ISSUE TITLE
CreateRestAPI fail in deserialization of response

### ISSUE THREAD

**Issue by abailly** [brendanhay/amazonka#291]
I am trying to use the `APIGateway` client and run into an issue in deserialization of response from AWS.

Here is the code (c/p directly from example...):

    createApi :: (MonadResource m, MonadCatch m) => Text -> AWST m Method
    createApi api = do
        restApi <- send (createRestAPI api)
        let Just apiId = restApi ^. raId
        resources :: [Resource] <- (view grrsItems) <$> send (getResources apiId)
        let Just rootId = head resources ^. rId
        resource :: Resource <- send (createResource apiId rootId "{file}")
        let Just fileResourceId = resource ^. rId
        method :: Method <- send (putMethod apiId fileResourceId "GET" "NONE")
        return method
 
And here is the answer I get from AWS:

```
[Client Request] {
  host      = apigateway.eu-west-1.amazonaws.com:443
  secure    = True
  method    = POST
  target    = Nothing
  timeout   = Just 70000000
  redirects = 0
  path      = /restapis
  query     = 
  headers   =  ...
  body      = {"name":"testApi"}
}
[Client Response] {
  status  = 201 Created
  headers = x-amzn-requestid: 0279b6cc-23e6-11e6-a7e7-519c2fbcef76; content-type: application/hal+json; content-length: 2215; date: Fri, 27 May 2016 08:35:47 GMT
}
[Raw Response Body] {
{"_links":{...},"createdDate":"2016-05-27T08:35:47Z","id":"8y2etpow95","name":"testApi"}

}
[SerializeError] {
  service = APIGateway
  status  = 201 Created
  message = when expecting a POSIX, encountered String instead
}
```

I checked in the code and the type of `createdDate` is definitely a `Maybe POSIX` but it looks like AWS is sending back an ISO-8601 formatted string.

**Comment by abailly** [comment]
Is there a workaround I could use? Maybe explicitly deserializing response?

**Comment by brendanhay** [comment]
Typically I'd use `Control.Exception.catch` (or friends), but this would suppress the `id` field you need. 

Ideally the `SerialiseError` (and possibly other error types) would return the raw response body since it's known to be non-streaming.

**Comment by abailly** [comment]
Thanks a lot!

**Comment by abailly** [comment]
I am sorry to reply to a closed issue but using amazonka-1.4.2 I got the following error:

```
[Client Request] {
  host      = apigateway.eu-west-1.amazonaws.com:443
  secure    = True
  method    = POST
  target    = Nothing
  timeout   = Just 70000000
  redirects = 0
  path      = /restapis
  query     = 
  headers   = ...
  body      = {"name":"testApi2"}
}
[Client Response] {
  status  = 201 Created
  headers = x-amzn-requestid: 18d9fbe5-2c7a-11e6-ad14-53dc0102cda5; content-type: application/json; content-length: 63; date: Tue, 07 Jun 2016 06:35:59 GMT
}
[Raw Response Body] {
{"createdDate":1465281359,"id":"4x69hrdz0g","name":"testApi2"}

}
[SerializeError] {
  service = APIGateway
  status  = 201 Created
  message = Error in $.createdDate: failed to parse field createdDate: expected ISO8601, encountered Number
  body    = Just {"createdDate":1465281359,"id":"4x69hrdz0g","name":"testApi2"}

}
```

That's odd! The documentation pointed at in #292 definitely states `createdDate` should be an ISO8601 date...

**Comment by brendanhay** [comment]
No problem, if it's closed and still broken, it should be reopened!

This is not entirely unusual, having encountered quite a few inconsistencies in the documentation. I'll get some test fixtures written, as well as an example and hopefully provide a hotfix to `1.4.2` shortly.

**Comment by abailly** [comment]
I would happy to help if I can, this seems rather simple to fix :)

**Comment by brendanhay** [comment]
Before I commit any fixes, I need to narrow down the differences in your two examples.

In `1.4.1`, `CreateRestAPI: POST /restapis` returns an `ISO8601` timestamp:

```json
{"_links":{},"createdDate":"2016-05-27T08:35:47Z","id":"8y2etpow95","name":"testApi"}
```

And the most recent `1.4.2`, `CreateRestAPI: POST /restapis` returns a `POSIX` timestamp:

```json
{"createdDate":1465281359,"id":"4x69hrdz0g","name":"testApi2"}
```

Is that correct? Are there any other differences that may be missing from the above information?

**Comment by abailly** [comment]
Indeed, that's the only meaningful differences I can spot: The absence of `_links` field and the difference in `createdDate` format.

**Comment by brendanhay** [comment]
Hmm. Horrific squash noise. 

Timestamps will attempt to parse either a `POSIX` integer or an `ISO8601` for APIGateway responses. Timestamps will still be encoded as `POSIX` integers.

This is a rather unfortunate workaround, but I can't see another option presently due to the inconsistent responses.

**Comment by abailly** [comment]
:) 

This makes me think of a possibly interesting addition to amazonka: Let user inject their own (de)serializers upon requests sending. This would make it possible to work around inconsistencies, sudden changes, custom types in between major releases. Not sure how much effort this would entail though. It might even be possible to do right now?

**Comment by brendanhay** [comment]
In`>= 1.4.2`, you can use [Control.Monad.Catch.catch](http://hackage.haskell.org/package/exceptions-0.8.2.1/docs/Control-Monad-Catch.html#v:catch) to recover a `SerializeError` and then manually deserialise the [_serializeBody](https://github.com/brendanhay/amazonka/blob/1.4.2/core/src/Network/AWS/Types.hs#L226-L227) which contains the entire raw response body, if the request was non-streaming (ie. not S3 `GetObject`).

Or using [Control.Exception.Lens.catching](http://hackage.haskell.org/package/lens-4.14/docs/Control-Exception-Lens.html) with something like: 
`catching _SerializeError $ \SerializeError'{..} -> _serializeBody ...`

Regarding your suggestion of pluggable deserialisers, it'd probably be simplest to offer a variant of `send` which just returns a raw `http-client` response instead of attempting to parse the associated response type.

**Comment by abailly** [comment]
I did not think of catching the exception... And you are right: Much simpler to have something like `sendRaw` that would return raw response. Thanks a lot for your efforts and great work!

**Comment by abailly** [comment]
Works fine now! Thanks a lot.

**Comment by brendanhay** [comment]
Great! Good to hear.
