### ISSUE TITLE
Paginating over FilterLogEvents call results bails out early and skips data.

### ISSUE THREAD

**Issue by andreyk0** [brendanhay/amazonka#296]
I have this tiny tool https://github.com/andreyk0/aws-logs, just a wrapper around this single API call.
Noticed that it occasionally skips data that I think should show up in the results.

Finally tracked it down and it seems that it simply bails out too early, specifically making this change in the generated code fixes it:
```
diff --git a/amazonka-cloudwatch-logs/gen/Network/AWS/CloudWatchLogs/FilterLogEvents.hs b/amazonka-cloudwatch-logs/gen/Network/AWS/CloudWatchLogs/FilterLogEvents.hs
index 5e9c351..166dd64 100644
--- a/amazonka-cloudwatch-logs/gen/Network/AWS/CloudWatchLogs/FilterLogEvents.hs
+++ b/amazonka-cloudwatch-logs/gen/Network/AWS/CloudWatchLogs/FilterLogEvents.hs
@@ -162,8 +162,6 @@ fleLogGroupName = lens _fleLogGroupName (\ s a -> s{_fleLogGroupName = a});
 instance AWSPager FilterLogEvents where
         page rq rs
           | stop (rs ^. flersNextToken) = Nothing
-          | stop (rs ^. flersEvents) = Nothing
-          | stop (rs ^. flersSearchedLogStreams) = Nothing
           | otherwise =
             Just $ rq & fleNextToken .~ rs ^. flersNextToken

```

Turns out it's actually perfectly normal for CW to return an empty list of events or an empty list of log streams. The important part is the presence of the next token.

In my case I'm querying a consolidated log from many instances (that change over time due to scaling activities). Each instance has a log stream that matches its ID. Searching for some rarely seen string in these tends to produce many 'empty' responses. But as long as they have 'next token' set if one keeps searching with it - eventually it yields results.

Sorry couldn't make a meaningful patch, got confused with code-generation aspects of this.

Thanks for taking a look!

**Comment by brendanhay** [comment]
Thanks for the detailed report!
