### ISSUE TITLE
Amazonka kicked out of stackage - ghc 8.0.1

### ISSUE THREAD

**Issue by alexanderkjeldaas** [brendanhay/amazonka#297]
Regarding #87, amazonka is not in nightly because of some ghc 8 issue.  It would be great to get it back.

I'm sure you already know this, but in case you don't I'm filing an issue (couldn't see a filed issue on this).

**Comment by brendanhay** [comment]
It should be fixed due to #294, I just haven't had the time to verify this yet.

**Comment by brendanhay** [comment]
Re-enabled via https://github.com/fpco/stackage/pull/1560
