### ISSUE TITLE
http-conduit-2.2

### ISSUE THREAD

**Issue by phadej** [brendanhay/amazonka#302]
`amazonka-core` isn't buildable with `http-conduit-2.2`

I made revisions on hackage for `1.4.*`. major series. rest of `1.*` are still red: http://matrix.hackage.haskell.org/package/amazonka-core

**Comment by phadej** [comment]
Edit the rest of the versions as well.

**Comment by brendanhay** [comment]
`amazonka-* > 1.4.3` is constrained to `http-conduit >= 2.2`.
