### ISSUE TITLE
Possibly weird request: optional URI encoding for signature?

### ISSUE THREAD

**Issue by MichaelXavier** [brendanhay/amazonka#303]
Hi,

I built a project a little while back called [bloodhound-amazonka-auth](https://github.com/MichaelXavier/bloodhound-amazonka-auth). It combines the bloodhound ElasticSearch client with Amazonka's types and signing tooling to properly authorize requests going to Amazon's ElasticSearch service.

However, I've found that using index patterns (i.e. `my-index-name-*`) with authorized requests was not working and was kicking back an error about an invalid signature. I've spent the better part of the day tracking this down and it looks like amazonka encodes the "*" as "%2A" before generating the signature. 

The weird part is that if my canonical string goes out as "/my-index-name-%2A", amazon rejects my signature and says the path part of the canonical string should be "/my-index-name-%252A", thus seemingly double-encoding that part of the path. Weirder still, if i monkeyed with the internals of amazonka to double encode, the error came back *triple* encoded. So its almost like (at least on elasticsearch endpoints) aws takes your already-encoded URI and encodes it again to calculate the expected signature.

Anyways, the only way I've found that solves this is to explicitly change the V4 signer *not* to encode the path component of the request for the canonical string, but this is currently a non-optional step in the process when using amazonka.

I understand this isn't directly related to this project since you're not providing an actual elasticsearch client but I'm curious if:

1. You know from your experience what is going on here.
2. If it is in any way sensible to make V4 signing flexible enough to opt into *not* encoding the path. Right now it looks like my only recourse would be to port almost *all* of your V4 signing code into `bloodhound-amazonka-auth` to remove the encoding.
3. If I do have to vendor all of the v4 signing code into my project, is that even permissible from a licensing perspective?

Sorry for the wall of text but it has literally been a day of debugging this and its causing me to lose my mind a bit ;)

**Comment by brendanhay** [comment]
Hi @MichaelXavier,

1. My experience says debugging AWS signing is an incredibly opaque and frustrating procedure. Even their own test cases and documentation is subtly incorrect in places.
2. This seems like a sane solution to your problem. Approach outlined below.
3. According to the MPL v2.0 this is permissible if any modifications are similarly made available under open source. [tldrlegal.com](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)) has a summary.

So the simplest possible solution I can think of for 2. is:

* Extend the signing algorithm to take an extra parameter (`Options` or `Bool`) that controls this behaviour.
* By default the signer the `Service` uses is [rendered](https://github.com/brendanhay/amazonka/blob/0656b5a12001a1d32cca65cf69f6327d3fcef858/amazonka-elasticsearch/gen/Network/AWS/ElasticSearch/Types.hs#L147) by the generator, this would default to encoding the URI/path per the [documentation](http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html)
* You would then need to [override](https://github.com/brendanhay/amazonka/blob/0656b5a12001a1d32cca65cf69f6327d3fcef858/amazonka/src/Network/AWS/Env.hs#L136-L144) the service configuration used for the ElasticSearch requests:

```haskell
elasticSearchUnencoded :: Service
elasticSearchUnencoded =
    -- The generator emits a stable identifier for each service encoded in the
    -- service configuration. By extending the relevant generated service configuration
    -- you can ensure any similarly generated request for the service will uses this
    -- modified configuration via 'reconfigure', shown below in 'main'.
    Network.AWS.ElasticSearch.elasticSearch
        & serviceSigner .~ Network.AWS.Sign.V4.v4 NoURLEncode

main :: IO ()
main = do
    ...
    runAWST env $
        -- 'reconfigure' takes a 'Service' and sets the environment to use this
        -- service configuration for any ElasticSearch request sent within the monadic
        -- scope (via 'Control.Monad.Reader.local'):
        reconfigure elasticSearchUnencoded $ do
             --
            ... <- send (describeElasticsearchDomains & dedDomainNames .~ ...)
```

So if this seems like it'll fix your issue - I'll look at making the necessary changes to the signers.

Additionally I'd like to run some tests to reliably reproduce using another SDK, and assuming fingers don't point at me I'll look at raising the issue with AWS customer support.

**Comment by MichaelXavier** [comment]
Thanks for the detailed and timely writeup! Your solution seems like it would work but I almost think it makes my use case too easy. As far as we know, this only happens with the elasticsearch service and only if you have url-unsafe characters like * in a path, which is unlikely with any of the APIs you expose via `amazonka-elasticsearch`. Since `v4 :: Signer` and `Signer` is a record, what if we added a field for URL encoding and defaulted it to off in all exported signers. That way, the only code that would need update is user code and only if they were implementing a custom signer. So for my case, the signer would look like `Network.AWS.Sign.v4 { v4URLEncoding = NoURLEncode}` or perhaps `Network.AWS.Sign.v4 & v4URLEncoding .~ NoURLEncode}`. I could also take a crack at making this change if you'd like.

Also, if you were to do this, maybe it would be prudent to keep it on a branch for a bit and I'd be happy to test it out and make sure it solves the issue I've encountered.

As for a test case, my library now has a contrived integration test case that exposes the issue [here](https://github.com/MichaelXavier/bloodhound-amazonka-auth/blob/signature-encoding-error/test/Main.hs#L56). So all you'd need to do is clone this repo, maybe unpack the `amazonka-core` package and set it up in the stack.yaml if you wanted to fiddle with it. The test doesn't run by default, you need to pass it an argument and it uses amazonka's credential discovery mechanism to authenticate. So my test loop right now looks like:

```
stack test --fast --file-watch --test-arguments="--integration-server https://MY-ES-CLUSTER.us-east-1.es.amazonaws.com -p patterns"
```

Part of me was suspicious as to what link in the chain this was coming from. This case isn't *that* obscure. I would assume that using wildcards in index names is fairly common practice with elasticsearch, but maybe people who are doing that with AWS ES are also just using IP-based security instead of V4 signing...

**Comment by MichaelXavier** [comment]
Hey, so good news! I think we can all slowly back away from this craziness. After ripping up a bunch of amazonka-core to get this working it dawned on me that the hook that bloodhound wants is `Request -> IO Request`. The key thing it seems that need to change is that the *request* should not be path-encoded. Everything else (including the signature) should be based off the encoded path. I think I got this wrong from spending so much time with the problem and getting confused.

So the fix to my library seems to simply be to compose in a final function of type `Request -> Request` that just uses `urlDecode` from `uri-bytestring` and lo and behold the tests pass.

**Comment by brendanhay** [comment]
Nice debugging work! :+1:

I am wondering for consistencies sake, how the other SDKs handle the encoding of the actual request path on the wire - something for me to investigate.
