### ISSUE TITLE
 Please provide a proper license tag in the Cabal file

### ISSUE THREAD

**Issue by peti** [brendanhay/amazonka#310]
My understanding is that `MPL-2.0` would be the correct choice.

**Comment by peti** [comment]
`amazonka-lightsail-1.4.5` advertises itself as `OtherLicense` when, in fact, it's licensed under `MPL-2.0`, too.

**Comment by peti** [comment]
Same problem in `amazonka-xray`.

**Comment by brendanhay** [comment]
Thought these were automated! :smile: 

I'd held off actually specifying since older version of cabal (or Hackage?) would fail to upload when `MPL-2.0` was used as the license field. I'll change it for the next release.

**Comment by peti** [comment]
Same problem in `amazonka-stepfunctions`, `amazonka-ssm`, `amazonka-snowball`, `amazonka-sms`, `amazonka-shield`, `amazonka-servicecatalog`, `amazonka-rekognition`, etc. ...

Anyway, I suppose there's no value in listing them all. :-)

**Comment by brendanhay** [comment]
No, it's just a change to the generator template for all libraries. :+1:

**Comment by peti** [comment]
Generally speaking, the `MPL-2.0` license has been supported in Cabal for a long time. I think you'd have to go back to GHC 6.x to find a compiler that can't handle that tag.

**Comment by brendanhay** [comment]
It was probably Hackage specifically then. I just tried another library and it appears to accept the upload with the correct license field.
