### ISSUE TITLE
[RFC] Consider renaming module namespace

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#312]
This is a call for comments on a potentially contentious change, which arises only due to my intense dislike of the current `Network.AWS.` namespace due to all of the packages complete dissociation with actual networking and Java-style taxonomy in general.

> Prior ~~bike-shedding~~ discussion:
> - [What's the Right Way to Name Packages and Modules?](https://www.reddit.com/r/haskell/comments/2ggopt/whats_the_right_way_to_name_packages_and_modules/)
> - [Packages and Namespace Naming Conventions](https://www.reddit.com/r/haskell/comments/1qrilm/packages_and_namespaces_naming_convention/)
> - [Towards a Better Haskell Package](http://fvisser.nl/post/2013/may/28/towards-a-better-haskell-package.html)

Ideally since the packages are named `amazonka` and `amazonka-*`, I'd like the namespace of the modules to reflect the package name. Illustrating the potential change using `amazonka-dynamodb`:

**Current**

```
Network.AWS.DynamoDB
Network.AWS.DynamoDB.BatchGetItem
Network.AWS.DynamoDB.BatchWriteItem
Network.AWS.DynamoDB.CreateTable
Network.AWS.DynamoDB.DeleteItem
Network.AWS.DynamoDB.DeleteTable
Network.AWS.DynamoDB.DescribeLimits
Network.AWS.DynamoDB.DescribeTable
Network.AWS.DynamoDB.GetItem
Network.AWS.DynamoDB.ListTables
Network.AWS.DynamoDB.PutItem
Network.AWS.DynamoDB.Query
Network.AWS.DynamoDB.Scan
Network.AWS.DynamoDB.Types
Network.AWS.DynamoDB.UpdateItem
Network.AWS.DynamoDB.UpdateTable
Network.AWS.DynamoDB.Waiters
```

**Proposed**

```
Amazonka.DynamoDB
Amazonka.DynamoDB.BatchGetItem
Amazonka.DynamoDB.BatchWriteItem
Amazonka.DynamoDB.CreateTable
Amazonka.DynamoDB.DeleteItem
Amazonka.DynamoDB.DeleteTable
Amazonka.DynamoDB.DescribeLimits
Amazonka.DynamoDB.DescribeTable
Amazonka.DynamoDB.GetItem
Amazonka.DynamoDB.ListTables
Amazonka.DynamoDB.PutItem
Amazonka.DynamoDB.Query
Amazonka.DynamoDB.Scan
Amazonka.DynamoDB.Types
Amazonka.DynamoDB.UpdateItem
Amazonka.DynamoDB.UpdateTable
Amazonka.DynamoDB.Waiters
```

Since this would be a widespread breaking-change, additional placeholder modules would be added to preserve the old namespaces so that existing code doesn't break until a deprecation period can be served. An example of a placeholder module to ensure code importing `Network.AWS.DynamoDB` continues to work is:

```
module Network.AWS.DynamoDB (module Export) where

import Amazonka.DynamoDB as Export
```

What modules actually need this treatment? Providing placeholders for all modules would simply slow down compilation. I'd expect only the top-level `Network.AWS.*` and `Network.AWS.*.Types` would be necessary. This would result in the `exported-modules` looking as follows:

```
exported-modules:
      Network.AWS.DynamoDB
    , Network.AWS.DynamoDB.Types

    , Amazonka.DynamoDB
    ...
```

But the most important question - is this just too invasive? I'm currently leaning on the side of the pain outweighs the gain.

**Comment by axman6** [comment]
I'm all for this change, shorter import lines is always nice, and I agree on having the package name in the module namespace. I'm not convinced the stub modules are really necessary, just have a version bump and given that the fix for upgrading is essentially running Grep over any code base and there will be no material change to the code it doesn't seem worth adding to the namespace. i just worry you'll be left supporting two name spaces because have no real reason to update with the stubs.

**Comment by axman6** [comment]
Because users have*

**Comment by brendanhay** [comment]
Your point about there being no material change and people having no reason to update to the new namespace make sense, it'd be better to avoid the placeholders in that case.

Thanks for your input, I'll sit on it for a bit and see if anyone else cares enough to chime in.

**Comment by kim** [comment]
Would you want to keep `Control.Monad.Trans.AWS`? Also, would you want to apply the same substitution to `amazonka-core` (Imports from which are occasionally necessary)?

**Comment by brendanhay** [comment]
I'd probably keep `Control.Monad.Trans.AWS` for the foreseeable future - I think that'd be the only exception?

It'd also apply to `amazonka-core`, unless there's a compelling reason not to do so.

**Comment by joehillen** [comment]
I'm all for switching to `Amazonka.*` . 

Just please also bump the major version number when you eventually break backwards compatibility. For some reason, the haskell community don't like to increment major version numbers.

**Comment by jdreaver** [comment]
I think this is a good change. Migration shouldn't be too painful if all you have to do is replace `Network.AWS` with `Amazonka`.

**Comment by charleso** [comment]
The critical thing for us is obviously that it's a major version bump.

We're on the fence as to whether we would want/need the placeholders. We have wrapped _everything_ that we use in amazonka is mismi, so it's the only place we would need to touch when we upgrade. It _might_ be nice to add placeholders for core, just to give us some options for upgrading partially, but even then I'm not sure.

No serious objects from Ambiata anyway. 👍

**Comment by kim** [comment]
I have expressed my preference for flat(ter) namespacing before, so I should probably just shut up. However, I find it hard to justify such a large change this late after `1.0`.

Just to throw in a couple of points from the devil's point of view:

* `Amazonka.MonadAWS` as well as `Control.Monad.AWS.AWST` both appear to claim being canonical for the domain, where only one reflects that in it's namespace
* on the "provenance vs. purpose" front, it would seem nicer to me to have `Network.AWS` and `Network.Gogol` align in my import list (likely a minority use case). Which would suggest swapping the somewhat meaningless `Network` with the more ontologically correct `Cloud` or something.
* or why not just contract to `AWS`?

Anyways, I don't feel too strongly about this, and wouldn't assess to cost of switching unbearable for the projects I maintain. So ±0 from me.
