### ISSUE TITLE
re-generate amazonka-ecs

### ISSUE THREAD

**Issue by gregwebs** [brendanhay/amazonka#314]
I am missing the new memoryReservation field. Happy to try out master for you.

**Comment by brendanhay** [comment]
Thanks. Will look at regenerating over the weekend.

**Comment by brendanhay** [comment]
Hmm. As of writing this the [botocore models](https://github.com/boto/botocore/blob/40510b3469e5f7e05e97f012e97ed097275c6df9/botocore/data/ecr/2015-09-21/service-2.json) don't have the `memoryReservation` field, apologies!
