### ISSUE TITLE
SQS readme links

### ISSUE THREAD

**Issue by tippenein** [brendanhay/amazonka#319]
the way the documentation for SQS is generated has blank items in its list
![screen shot 2016-10-10 at 9 04 22 pm](https://cloud.githubusercontent.com/assets/1235263/19258522/4fd9efce-8f2d-11e6-9fca-a2f57294fbd3.png)

**Comment by brendanhay** [comment]
Thanks, yes I'm aware the Pandoc HTML -> Haddock conversion is currently suboptimal in terms of output markup. There's a lot of poor formatting, blanks, and mis-linked code in a few of the libraries.

The fix ideally will probably be to hand-rolled the HTML -> Haddock conversion, and specifically handle cases such as these.

**Comment by brendanhay** [comment]
The linked PR provides more control over the parsing of HTML and rendering of Haddock markup. The SQS example you posted above is now rendered as:

![screenshot from 2016-11-28 16-55-43](https://cloud.githubusercontent.com/assets/4493/20675139/9232cc68-b58b-11e6-8b85-179b5bbd303d.png)

**Comment by tippenein** [comment]
👍 artisinal HTML parsing looks 💯
