### ISSUE TITLE
S3 gorsContentLength should be Int64 instead of Int

### ISSUE THREAD

**Issue by bitc** [brendanhay/amazonka#320]
In 32 bit versions of GHC, the "Int" type is 32 bits. This means that `gorsContentLength :: Lens' GetObjectResponse (Maybe Int)` will overflow on S3 files that are larger than 2GB.

I believe that the correct type should be "Int64" (just like how lazy ByteString uses Int64 for length: https://hackage.haskell.org/package/bytestring-0.10.8.1/docs/Data-ByteString-Lazy.html#v:length)

I believe the same also applies to `horsContentLength`, `poContentLength`, `upContentLength`

**Comment by brendanhay** [comment]
Thanks for notifying me, I'll look at changing it in the next release.

**Comment by jystic** [comment]
I think this is also a problem with `oSize`

**Comment by endgame** [comment]
I went spelunking. I don't think this is a thing any more:

For GetObject, it's parsed out of the header here:

https://github.com/brendanhay/amazonka/blob/6846721de1c95984c2c9563b80f7935d8bb9ef8e/amazonka-s3/gen/Network/AWS/S3/GetObject.hs#L587

This calls this operator from `Headers.hs`:

https://github.com/brendanhay/amazonka/blob/6846721de1c95984c2c9563b80f7935d8bb9ef8e/amazonka/src/Network/AWS/Data/Headers.hs#L30

Which ultimately calls into `Data.Attoparsec.Text.decimal`, which can parse into any `Integral` (and doesn't go via `Int`).

Similar for `horsContentLength`, `poContentLength`, `upContentLength`.

`oSize` is different; I'll prepare a PR.
