### ISSUE TITLE
instance metadata parsing failure

### ISSUE THREAD

**Issue by gregwebs** [brendanhay/amazonka#321]
I tried to use the function `Network.AWS.EC2.Metadata.identity` and got the following:

```
(Error in $.instanceId: failed to parse field instanceId: Failed reading: Failure parsing Region from i-411a9670)
```

It would be nice to get an error message that has the string that the parse was attempted on.

Not sure if this is related to #271 which I will also look at more closely

**Comment by brendanhay** [comment]
Well, that was rather embarrassing - I apologise.

`amazonka-1.4.4.1` has been uploaded and `1.4.4.` deprecated. The other packages haven't changed.

Whilst the error you pasted is horribly convoluted - it's the default `aeson` error, it does state that it tried to parse a `Region` from the `instanceId` field.

**Comment by gregwebs** [comment]
thanks!
