### ISSUE TITLE
failed to parse kernelId

### ISSUE THREAD

**Issue by gregwebs** [brendanhay/amazonka#322]
Similar to #321 I am getting a parse failure at startup

```
user error (Error in $.kernelId: failed to parse field kernelId: expected Text, encountered Null)
```

My only goal is to get the account id. It would be nice to be able to de-couple that with the rest of the meta data. Maybe provide a base meta-data API that lets the user give their own specific url endpoint, and the current parser can be used if desired.

**Comment by brendanhay** [comment]
This is a bit of a cluster fuck on my part. As usual their are differing fields that are required or not, and this particular case illustrates why almost everything should be `Maybe`.

What I will probably do is provide something that returns an `aeson` `Value`. Does this satisfy your case above?

**Comment by brendanhay** [comment]
I should of mentioned, I'll also convert the current call to return mostly `Maybe` fields, as well as provide a lower level function that returns `Value` and can be used in conjunction with some form of JSON lenses.

**Comment by gregwebs** [comment]
Sounds good

**Comment by brendanhay** [comment]
I forgot to mention, in the meantime you can use something like:

```
import Network.HTTP.Client
import Network.AWS.EC2.Metadata as Meta

main = do
    m  <- newManager defaultManagerSettings
    bs <- Meta.dynamic m Meta.Document
    ...
```

Where `bs` above is the raw unparsed instance identity document.
