### ISSUE TITLE
Example/Documentation Request: `putItem` example for DynamoDB

### ISSUE THREAD

**Issue by atc-** [brendanhay/amazonka#326]
Firstly: thanks for this immensly useful API - it's really great being able to talk to AWS from Haskell.

I am struggling to get a working example for `putItem` with respect to DynamoDB. Is there any chance the existing examples could demonstrate it?

**Comment by brendanhay** [comment]
I've added an example in #327 which should hopefully illustrate it more clearly, most of the code there is related to setting up a custom endpoint to work with [DynamoDBLocal](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) - but hopefully the `putItem` call is self explanatory.

Let me know if that helps, there's a more 'real world' example available in the [credentials](https://github.com/brendanhay/credentials/blob/8a968cc8df19f89dbf320a91f5866f9172b78ead/credentials/src/Credentials/DynamoDB.hs#L224-L242) library.

**Comment by atc-** [comment]
Perfect. Thank you so much!
