### ISSUE TITLE
Add Amazon Mechanical Turk APIs?

### ISSUE THREAD

**Issue by agrafix** [brendanhay/amazonka#328]
Are there any plans on adding the [Amazon Mechanical Turk](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/Welcome.html) API?

**Comment by brendanhay** [comment]
Mechanical Turk does not have a publicly available [service definition](https://github.com/boto/botocore/tree/develop/botocore/data) like the currently supported services, so I'd need to manually produce a definition to feed into the generator or write a bespoke implementation by hand.

**Comment by danharaj** [comment]
@brendanhay It looks like they have added a service definition for Turk [1]. I would like to do the work to add the library to amazonka but I'm not entirely sure how to go about it. Could you give me some guidance?

[1] https://github.com/boto/botocore/blob/develop/botocore/data/mturk/2017-01-17/service-2.json

**Comment by brendanhay** [comment]
Thanks for the heads up. The work to add a new library is minimal in the best case, and new libraries are added as part of the process of updating all service definitions from upstream.
