### ISSUE TITLE
Add us-east-2 to Region?

### ISSUE THREAD

**Issue by MichaelXavier** [brendanhay/amazonka#333]
Looks like AWS added us-east-2 in Ohio on [October 17th](https://aws.amazon.com/about-aws/whats-new/2016/10/announcing-the-aws-us-east-ohio-region/). I think that means we need another case in the Region type.

**Comment by MichaelXavier** [comment]
Also looks like you're missing ap-northeast-2 (Seoul).

**Comment by brendanhay** [comment]
Thanks for the headsup!
