### ISSUE TITLE
The AWSPager instance for dynamodb is wrong

### ISSUE THREAD

**Issue by ondrap** [brendanhay/amazonka#340]
The AWSPager for `Scan` and `Query` are wrong. E.g. here: https://github.com/brendanhay/amazonka/blob/develop/amazonka-dynamodb/gen/Network/AWS/DynamoDB/Query.hs#L232

It stops when `qrsItems` or `qrsCount` is zero; however that is a legal situation - if you specify a filtering condition, the query can return no items, yet the paging should continue. I think the https://github.com/brendanhay/amazonka/blob/develop/gen/model/dynamodb/2012-08-10/paginators-1.json should omit at least the `Items` and `Count`. The `ScannedCount` could be IMO omitted too as the `LastEvaluatedKey` should be enough to decide if paging should continue.

**Comment by zudov** [comment]
To quote the ["Paginating the Results" section](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html#Pagination) of dynamodb docs:

> The only way to know when you have reached the end of the result set is when LastEvaluatedKey is null.

So as @ondrap says, `LastEvaluatedKey` is enough to decide, and should be used as the only source of truth.
