### ISSUE TITLE
Autoscaling TerminateInstanceInAutoScalingGroup response

### ISSUE THREAD

**Issue by nhibberd** [brendanhay/amazonka#342]
Seeing this error
```
[SerializeError] {
   service = AutoScaling
   status  = 200 OK
   message = unable to find element "AutoScalingGroupName" in nodes ["ActivityId","Description","Progress","Cause","Details","StartTime","StatusCode"]
...
```

Looks like the amazon api documentation is contradicting itself

The response [documentation](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_TerminateInstanceInAutoScalingGroup.html#API_TerminateInstanceInAutoScalingGroup_ResponseElements) specifies the [`Activity`](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_Activity.html) object should be returned which includes the `AutoScalingGroupName` which marked as mandatory, however even the [sample example](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_TerminateInstanceInAutoScalingGroup.html#API_TerminateInstanceInAutoScalingGroup_Examples) shows an object without `AutoScalingGroupName`.

**Comment by brendanhay** [comment]
I'll have to make the `AutoScalingGroupName` `Maybe` in the short term to get the deserializer to work reliably. I'll also raise upstream for sanity.

**Comment by endgame** [comment]
I PR'd this, but where do service definition issues get reported?

**Comment by brendanhay** [comment]
What all the AWS SDKs include in the sources as JSON service definitions are themselves generated from an internal service framework / XML IDL. This IDL isn't open source, so we can only report on the generated service definitions (ie. https://github.com/boto/botocore) - which is about as ideal as it sounds.

Maybe at some point they'll move to [smithy](https://github.com/awslabs/smith) completely and have a centralised public repository of definitions. One can dream, anyway.
