### ISSUE TITLE
Question: stream from an S3 obj, transform the stream, then stream to another S3 obj

### ISSUE THREAD

**Issue by ababkin** [brendanhay/amazonka#343]
all in constant space - is this possible and if so, how? (i could not figure it out)

Thanks!

**Comment by axman6** [comment]
What problems are you running into? RsBody provides a ResumableBody and RqBody can take a Producer, and it should be possible to compose those together.

**Comment by axman6** [comment]
Uh, ResumableSource

**Comment by ababkin** [comment]
Thanks for answering so promptly Alex

Yes I gathered as much from the docs, but it seems that in order to create a ChunkedBody for the RqBody from a Source, I need to know ahead of time the stream length (in order to populate the _chunkSize and _chunkedLength fields in ChunkedBody). 
I would like to avoid streaming twice - once to count the number of bytes and the second time to actually stream (and potentially transform the stream along the way) into another s3 object.

OTOH, I just realized that I can do a simple head request (https://hackage.haskell.org/package/amazonka-s3-1.4.5/docs/Network-AWS-S3-HeadObject.html#v:horsContentLength <https://hackage.haskell.org/package/amazonka-s3-1.4.5/docs/Network-AWS-S3-HeadObject.html#v:horsContentLength>) to find out the size of an s3 object, so that may solve the problem of figuring out _chunkSize and _chunkedLength

I was hoping there is an example of what i want to do somewhere. Seems like a pretty useful thing to stream from one s3 obj to another in constant space (say in AWS Lambda) while transforming the stream

**Comment by axman6** [comment]
Are you modifying the data at all? There is also a CopyObject command if you aren't.

**Comment by ababkin** [comment]
Yes, modify data / transform / expand / reduce the stream

**Comment by axman6** [comment]
Look so I've you want the Multipart API, see CreateMultipartUpload and UploadPart.  It'd be nice to have a lightly easier API for this where you can just stream data into a Sink and it'd handle everything.

**Comment by axman6** [comment]
@ababkin you got me interested in this problem, so I started work on github.com/axman6/amazonka-s3-streaming. it's probably pretty immature, given it's had about 6 hours work done on it, but it _can_ upload files by streaming them to a conduit Sink.

**Comment by ababkin** [comment]
@axman6 This is great, I'll take a look
thanks for letting me know
