### ISSUE TITLE
amazonka-s3 implicitly decompresses some gzipped files

### ISSUE THREAD

**Issue by MichaelXavier** [brendanhay/amazonka#346]
First off, this may be expected behavior and may be just something you want to document, though as I'll explain, I expect this behavior is more implicit than that and is inherited from http-conduit.

I'm using kinesis firehose to dump bytestrings into S3. It does chunking and gzip compression, so it drops .gz files into an s3 bucket. Knowing this, I set up a conduit consumer that used gzip decompression to download the files and got a `ZlibException`. I then downloaded the file from the AWS console with my browser and `gunzip` couldn't read it despite the .gz extension. I also noted that the gorsContentLength was smaller than the actual bytestring produced from amazonka-s3 (i.e. it was uncompressed). Finally, I downloaded the file using the official aws s3 cli (`aws s3 cp`) and that file *was* compressed.

Looking into [http-conduit](https://www.stackage.org/haddock/lts-7.14/http-conduit-2.1.11/Network-HTTP-Conduit.html) I noticed it is by default configured for `browserDecompress`, which says `Decompress a compressed stream unless the content-type is 'application/x-tar'.`, so I think amazonka-s3's body stream will *implicitly* decompress the content of any .gz file provided it isn't a .tar.gz. I'm not sure of the reasons why browsers do this. I guess any file can be sent with gzip compression if the headers are right but I'd think for files which should save as gz there'd be some way to differentiate.

Anyway, this may be something you want in S3 but I suspected it was just implicit behavior carried over from http-conduits default, so I'm leaving it up to you to decide what to do. In the mean time I'll just remove gzip decompression from my consumer conduit.

**Comment by MichaelXavier** [comment]
Discussed this a bit and it turns out this only happens when transfer-encoding is set to gzip, and that evidently only happens when S3 is told to during upload. Since Kinesis Firehose does the upload, I have no say in it and this seems like its just how the service works, so maybe there's nothing to do here.

**Comment by brendanhay** [comment]
Thanks for sharing your findings! I'm going to close this for now, but if it turns out there is some way we can actually control this on our end and either fix/document it - then feel free to reopen.
