### ISSUE TITLE
newEnv in version 1.4.4+ breaks the PVP

### ISSUE THREAD

**Issue by axman6** [brendanhay/amazonka#348]
Seems a change that was supposed to be released with version 1.5.0 has made it into amazonka, with the type of newEnv changing in a breaking way. The comments say

> Since: 1.5.0 - The region is now retrieved from the AWS_REGION environment variable (identical to official SDKs), or defaults to us-east-1. You can override the Env region by using envRegion, or the current operation's region by using within.

but this change is already present and breaking code which relied on version < 1.5.0 not breaking the API.

**Comment by axman6** [comment]
Hey @brendanhay any comments on this? I'm surprised more people aren't running into this, and it's a pain to have to use CPP to handle all calls to newEnv.

**Comment by brendanhay** [comment]
Unfortunately due to my initial mistake this will exist until I (hopefully shortly) release `1.5.0` and can then deprecate the affected versions from being select by the solver in Hackage. I'll also retroactively update the changelog so people are aware.

**Comment by axman6** [comment]
Sounds like the most reasonable solution, looking forward to 1.5! Is there a changelog of upcoming changes for 1.5? Also, did you want to keep this issue open until the release?

**Comment by brendanhay** [comment]
Lets' keep the issue open until the release is out.

I'll start updating the changelog once the `1.5.0` release branch is cut, which tentatively should be over the weekend pending airport connectivity.

**Comment by dudebout** [comment]
1.4.4 has been deprecated. This issue should be closed.

**Comment by endgame** [comment]
@brendanhay This looks closeable.
