### ISSUE TITLE
Slow DynamoDB request/response turnaround

### ISSUE THREAD

**Issue by ababkin** [brendanhay/amazonka#350]
Hi, I'm trying to investigate the following issue:
If i do a simple DDB Put with javascript API, it takes well under 100ms to complete. If i do the same using the amazonka API, it consistently takes almost 1s to complete the request/response.

What is the reason for such discrepancy / slowness on amazonka part? Is there a way to improve this currently? If so, what should i look into?

**Comment by brendanhay** [comment]
Hi @ababkin,

Are you using the same AWS region for both requests?

The first point of investigation would be to enable `Trace` logging and share the output of the request/response life-cycle. Please make sure that any sensitive information is not contained in the log before pasting it on GitHub, or you can email it directly to me at the maintainer email address which can be found in any of the Haskell module headers.

An example of enabling tracing can be found here: https://github.com/brendanhay/amazonka/blob/develop/examples/src/Example/DynamoDB.hs#L43

**Comment by ababkin** [comment]
@brendanhay - thanks so much for your help. I was too quick to post the issue before looking harder into my code - the delay was introduced by my logger.

**Comment by brendanhay** [comment]
No problem! Glad you figured out the issue.
