### ISSUE TITLE
Missing new R4 and T2 instance types

### ISSUE THREAD

**Issue by phickey** [brendanhay/amazonka#354]
There are two new `t2` (`t2.xlarge, t2.2xlarge`) and six new `r4` (`r4.large, r4.xlarge, r4.2xlarge, r4.4xlarge, r4.8xlarge, r4.16xlarge`) instance types, but no entries exist for them yet. 

These instance types (and some others that are in preview or "coming soon") were [announced](https://aws.amazon.com/blogs/aws/ec2-instance-type-update-t2-r4-f1-elastic-gpus-i3-c5/) 2016-11-30 and may have appeared since the last round of service updates.

**Comment by brendanhay** [comment]
Thanks, I'll look at adding them shortly as part of the upcoming `1.5.0` release.

**Comment by phickey** [comment]
The [previously announced](https://aws.amazon.com/about-aws/whats-new/2016/11/coming-soon-amazon-ec2-i3-instances-next-generation-storage-optimized-high-io-instances/) `i3` instance types (`i3.large, i3.xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge, i3.16xlarge)` have also become generally available in a number of regions . Hopefully these will be added as part of the `1.5.0` release?

**Comment by brendanhay** [comment]
For sure, the release is pending some quality time between me and `amazonka` - but I'll definitely add the additional types.
