### ISSUE TITLE
Extract keys

### ISSUE THREAD

**Issue by whittle** [brendanhay/amazonka#355]
I need to create pre-signed S3 requests. I understand that because that doesn’t involve any requests, it’s beyond the scope of Amazonka. However, I’m already configuring my app to use Amazonka for other reasons, and I’d like to avoid providing AWS keys to my app in two different ways. Is there a way for Amazonka to expose the keys it’s using to my app?

**Comment by brendanhay** [comment]
Hi @whittle, have you had a look at [Network.AWS.Presign](http://hackage.haskell.org/package/amazonka-1.4.5/docs/Network-AWS-Presign.html)? There are some functions there that allow you to presign either a URL or an `http-client` `ClientRequest`.

**Comment by whittle** [comment]
Thank you, @brendanhay, I totally missed that. I’ll close the ticket.
