### ISSUE TITLE
S3 Event?

### ISSUE THREAD

**Issue by whittle** [brendanhay/amazonka#358]
I keep missing things in Amazonka, so I just thought I’d ask: is there an existing deserializer for [S3 notification events](http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html)? 

If not, are you interested in including a hand-coded version? I haven’t found a definition for the message structure yet, just examples.

**Comment by brendanhay** [comment]
There is not an existing deserializer, mainly because it's not included in the service definition(s).

If you want to sketch out a hand-written version - I'd be happy to look at how we can integrate it with `amazonka-s3`!

**Comment by endgame** [comment]
This type appears to be implemented by the `hal` library (a **H**askell **A**WS **L**ambda runtime): https://hackage.haskell.org/package/hal-0.4.8/docs/AWS-Lambda-Events-S3.html

While the `hal` package is designed for use with Lambda, it's just providing a record type with a `FromJSON` instance, and you could probably use it to parse the payload in other contexts.

Closing this to avoid duplicating work.
