### ISSUE TITLE
BucketName semantics

### ISSUE THREAD

**Issue by whittle** [brendanhay/amazonka#360]
For clarification, is `Network.AWS.S3.Types.BucketName` supposed to be the ARN of the bucket, or name of the bucket? It feels like a silly question just because of the name of the type, but there are multiple lenses (e.g. `asbdBucket`, `dBucket`, `isbdBucket`) that specify that they are using BucketName to provide an ARN.

**Comment by brendanhay** [comment]
Hi, unfortunately due to the coarseness of the upstream type specifications that AWS supplies there appears to be no distinction a bucket's name or ARN, they're both specified as `BucketName`.
