### ISSUE TITLE
ssm GetParameters serialize error

### ISSUE THREAD

**Issue by wuzzeb** [brendanhay/amazonka#362]
Here is the error I get when trying to use GetParameters from `amazonka-ssm`

```
LevelError:[SerializeError] {
  service = SSM
  status  = 200 OK
  message = Error in $: Error parsing empty List1 when expecting at least one element.
  body    = Just {"InvalidParameters":[],"Parameters":[{"Name":"foo","Type":"SecureString","Value":"bar"},{"Name":"foo2","Type":"SecureString","Value":"bar2"}]}
}
```

Looking at the docs at http://docs.aws.amazon.com/ssm/latest/APIReference/API_GetParameters.html, it does say that the InvalidParameters list has minimum length 1 but clearly the json returned has the empty list.  The error comes because GetParametersResponse has InvalidParameters of type `Maybe (List1 Text)` but it should be `Maybe [Text]`.

I actually worked around this by just including an invalid parameter name and ignoring it!

**Comment by brendanhay** [comment]
[GetParametersResponse](https://github.com/brendanhay/amazonka/blob/736e261cdb2c9d61b8015d950d2481ddd8876422/amazonka-ssm/gen/Network/AWS/SSM/GetParameters.hs#L147-L151) has been fixed with updated service definitions.
