### ISSUE TITLE
Add new regions

### ISSUE THREAD

**Issue by ian-ross** [brendanhay/amazonka#364]
Looks like there are a few new AWS regions added recently:

| Name | Region |
|----- |----- |
| `us-east-2` | US East (Ohio) |
| `ca-central-1` | Canada (Central) |
| `eu-west-2` | EU (London) |
| `ap-northeast-2` | Asia Pacific (Seoul) |
| `ap-south-1` | Asia Pacific (Mumbai) |

(From [here](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions).)

**Comment by brendanhay** [comment]
Thanks. `develop` [currently is only missing](https://github.com/brendanhay/amazonka/blob/e0c8fea840b44b6173fc59d4715c2b29b2acee18/core/src/Network/AWS/Types.hs#L657-L674) `ca-central-1` and `eu-west-2`. They should be part of the upcoming `1.5.0` release.

**Comment by ian-ross** [comment]
Great!  Thanks for the quick response!

**Comment by deepfire** [comment]
Waiting for release.. : -)
