### ISSUE TITLE
Documentation is not bulleted

### ISSUE THREAD

**Issue by charles-cooper** [brendanhay/amazonka#375]
Not sure if this is the best place for this question but, for instance:
http://brendanhay.nz/amazonka-doc/amazonka-ec2/Network-AWS-EC2-DescribeInstances.html#v:diiFilters is kind of difficult to read.

**Comment by axman6** [comment]
I was also going to mention this, in v1.5 most of the docs look great, but in 1.6 they're all single lines and really painful to read. @brendanhay did something change in the way docs are generated (or did Amazon break something?)

**Comment by endgame** [comment]
Appears to have been fixed in newer versions of generated code, but not yet on hackage: https://github.com/brendanhay/amazonka/blob/0433ee599feabd747a164bbc4445a08ff5364603/amazonka-ec2/gen/Network/AWS/EC2/DescribeInstances.hs#L396

I'll close this for now.
