### ISSUE TITLE
"list-type=2" not passed for ListObjectsV?

### ISSUE THREAD

**Issue by brynedwards** [brendanhay/amazonka#376]
Hi,

When using [lStartAfter](https://hackage.haskell.org/package/amazonka-s3-1.4.5/docs/Network-AWS-S3-ListObjectsV.html#v:lStartAfter) with a ListObjectsV request, I get this exception:
```
*** Exception: ServiceError (ServiceError' {
    _serviceAbbrev = Abbrev "S3"
  , _serviceStatus = Status {statusCode = 400 , statusMessage = "Bad Request"}
  , _serviceHeaders = [...]
  , _serviceCode = ErrorCode "InvalidArgument"
  , _serviceMessage = Just (ErrorMessage "startAfter only supported in REST.GET.BUCKET with list-type=2")
  ...
})
```
Changing [this line](https://github.com/brendanhay/amazonka/blob/80d42482b4a1be7c28006d9106351c865e9c1978/amazonka-s3/gen/Network/AWS/S3/ListObjectsV.hs#L190) to `"list-type" =: (2 :: Int)` fixes it for me.

Edit - had a look around and came across [`Network.AWS.Data.Query.toBS`](https://github.com/brendanhay/amazonka/blob/develop/core/src/Network/AWS/Data/Query.hs#L57):
```
>>> toBS $ QValue (Just "list-type=2")
"list-type%3D2="
````
I think that's what happening

**Comment by qrilka** [comment]
@brynedwards did you create a fork with this change? Also `Network.AWS.S3.ListObjectsV` haddocks quotes v1 docs:
```
ListObjectsV2 is the revised List Objects API and we recommend you use this revised API for new application development.
```
@brendanhay probably some PR should be done against `gen`?

**Comment by qrilka** [comment]
Actually it appears that the comment is correct (I just didn't understand it properly on 1st reading) but module name has only `V` in it and not `V2`

**Comment by qrilka** [comment]
Also it looks like other services could have this problem. At least `grep` shows "=" in `requestUri` for Glacier, API Gateway, Cloudfront and CloudSearch. E.g. see
```

instance ToQuery ImportAPIKeys where
        toQuery ImportAPIKeys'{..}
          = mconcat
              ["failonwarnings" =: _iakFailOnWarnings,
               "format" =: _iakFormat, "mode=import"]
```

**Comment by qrilka** [comment]
@brendanhay what about missing `2` in `Network.AWS.S3.ListObjectsV`?
