### ISSUE TITLE
The newLogger function breaks output of Unicode characters

### ISSUE THREAD

**Issue by mrkkrp** [brendanhay/amazonka#380]
Hey there, I must say it's a very pleasant piece of software to work with, thank you. However, recently I found myself investigating a rather strange situation where console output that prints Unicode characters (Cyrillic script in my case) produced rather strange results (i.e. printed garbage). I started investigating this and have found that the reason is in `newLogger` function, which I use like this:

```haskell
logger <- newLogger logLevel stdout
```

It sets output mode of `stdout` to binary and this is not good:

https://www.stackage.org/haddock/nightly-2017-04-10/amazonka-1.4.5/src/Network.AWS.Internal.Logger.html#newLogger

I don't understand why for logging purposes we need to set output mode to binary? Also, it looks like logging to `stdout` is not uncommon and changing its settings in this way should be at least documented. What do you think?

**Comment by mrkkrp** [comment]
I have put together my own version of the function without setting output mode to binary, works perfectly.

**Comment by brendanhay** [comment]
Thanks for bringing this to my attention. The output mode should not be set to binary, as you've noted. It's a mistake on my part that it carried through from the precursor to `amazonka`.
