### ISSUE TITLE
Why adjunctions?

### ISSUE THREAD

**Issue by qrilka** [brendanhay/amazonka#384]
I was a bit surprised that `fail "Boo"` in AWS monad didn't result in `IOException` and it appears that the reason is in `ReaderT` from `adjunctions` packages which doesn't lift `fail` (while ordinary `ReaderT` from `transformers` does).
Could you give a hint why `ReaderT` from `adjunctions` was chosen here? (I wish there were some docs in `adjunctions` but not so much info there)

**Comment by brendanhay** [comment]
Hi @qrilka, `adjunctions` is not a direct dependency and the `ReaderT` instance over which `AWST` is formed is imported from the `mtl` and `transformers` packages.

Are you layering another monad stack within `AWST`, perhaps?

**Comment by qrilka** [comment]
That's odd, now I see `import Control.Monad.Reader` in `Control.Monad.Trans.AWS` but `MonadReader` at http://hackage.haskell.org/package/amazonka-1.4.5/docs/Control-Monad-Trans-AWS.html leads to `adjunctions` - probably some haddocks issue?
Actually in my code I use basic `runAWS` but I don't understand why `fail` doesn't give `IOException` while `liftIO . fail` does, e.g.:
```
λ> runResourceT . runAWS env $ fail "foo" `catchIO` \_ -> liftIO $ putStrLn "caught"
*** Exception: foo
λ> runResourceT . runAWS env $ liftIO (fail "foo") `catchIO` \_ -> liftIO $ putStrLn "caught"
caught
```

**Comment by qrilka** [comment]
Closing it as not important
