### ISSUE TITLE
Support for ECS credentials discovery method

### ISSUE THREAD

**Issue by lexi-lambda** [brendanhay/amazonka#385]
ECS allows providing roles for tasks, as documented in [IAM Roles for Tasks](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html). This seems to expect that a request be made to `169.254.170.2` if the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable is set. It would be nice if amazonka’s credentials discovery method attempted this.

**Comment by brendanhay** [comment]
Thanks for raising the issue. From your commit chain, it looks like you're planning on opening a PR for this - or do you want me to do it?

**Comment by lexi-lambda** [comment]
Thanks for checking up on this! I was indeed planning on opening a PR, though I hadn’t gotten around to it yet (and I’ve been getting away with just configuring stack to use my patched version). The changes I’ve made seem to work, but I still haven’t documented all of them on my branch yet, which is the main reason I haven’t opened a PR.

I’ll try and get things cleaned up sometime this week so that I can open something for review.
