### ISSUE TITLE
Upgrade monad-control dependency

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#40]
With the recent release of `monad-control >= 1` the `MonadBaseControl` instance in `amazonka` for `AWST` breaks due to the change from associated data types to associated type synonyms.

Since this is backwards/forwards incompatible, the cabal constraint is currently `< 1`. At some point this should be changed to `> 1` presuming no issues with the usual dependency hell for downstream consumers of this library.

**Comment by shlevy** [comment]
Fixed by #56: dependency hell addressed by following PVP
