### ISSUE TITLE
Refresh auth token on non-EC2 in case it's expired

### ISSUE THREAD

**Issue by reactormonk** [brendanhay/amazonka#400]
The auth tokens on the local machine are valid for 1h, after that they are refreshed. So using amazonka for scripts that take more than 1h is not possible.

**Comment by effectfully** [comment]
@brendanhay, what should be done in order to fix this problem? I could try to cook up a pull request.

**Comment by endgame** [comment]
This probably needs clarification - are you getting auth tokens from STS and then instantiating another amazonka `Env`? It probably needs some kind of refresh logic similar to the stuff in `amazonka/src/Network/AWS/Auth.hs`.

I'd look at a PR but I don't consider it must-have for the 2.0 milestone; there hasn't been much discussion over the past 4 years.
