### ISSUE TITLE
Network.AWS.Glacier.UploadArchive is missing x-amz-glacier-version

### ISSUE THREAD

**Issue by carlohamalainen** [brendanhay/amazonka#402]
When using ```Network.AWS.Glacier.UploadArchive``` to push a small file to Glacier I got this error:

    ErrorMessage "Required parameter missing: API version"

Full error message:

    *** Exception: ServiceError (ServiceError' {_serviceAbbrev = Abbrev "Glacier", _serviceStatus = Status {statusCode = 400, statusMessage = "Bad Request"}, _serviceHeaders = [("x-amzn-RequestId","A6nW3L9RjkwKh1ofDsoUVSP-Y98F39V1vtLGd2WFyb909Eg"),("Content-Length","109"),("Date","Wed, 23 Aug 2017 03:39:15 GMT"),("Connection","close")], _serviceCode = ErrorCode "MissingParameterValue", _serviceMessage = Just (ErrorMessage "Required parameter missing: API version"), _serviceRequestId = Just (RequestId "A6nW3L9RjkwKh1ofDsoUVSP-Y98F39V1vtLGd2WFyb909Eg")})

To confirm the problem I manually mashed ```x-amz-glacier-version: 2012-06-01``` into the header like this:

```
diff --git a/amazonka-glacier/gen/Network/AWS/Glacier/UploadArchive.hs b/amazonka-glacier/gen/Network/AWS/Glacier/UploadArchive.hs
index 6d809c02d..e30ae91a8 100644
--- a/amazonka-glacier/gen/Network/AWS/Glacier/UploadArchive.hs
+++ b/amazonka-glacier/gen/Network/AWS/Glacier/UploadArchive.hs
@@ -139,7 +139,8 @@ instance ToHeaders UploadArchive where
         toHeaders UploadArchive'{..}
           = mconcat
               ["x-amz-sha256-tree-hash" =# _uaChecksum,
-               "x-amz-archive-description" =# _uaArchiveDescription]
+               "x-amz-archive-description" =# _uaArchiveDescription,
+               "x-amz-glacier-version" =# ("2012-06-01"::Text)]
 
 instance ToPath UploadArchive where
         toPath UploadArchive'{..}
```

But I shouldn't be touching this auto-generated file.

I see ```apiVersion``` in ```gen/model/glacier/2012-06-01/service-2.json``` with the right value, but I'm not sure how to refer to this in the model.

**Comment by DaveCTurner** [comment]
I ran into this issue recently too with 1.6.0. It seems that [Glacier requires the `x-amz-glacier-version` header](https://docs.aws.amazon.com/amazonglacier/latest/dev/api-common-request-headers.html) and I can't find a reference to a similar header with other services - I looked at [S3](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html), [EC2](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/CommonParameters.html), [SNS](https://docs.aws.amazon.com/sns/latest/api/CommonParameters.html) and [SQS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/CommonParameters.html). This, unfortunately, seems to mean that `amazonka-glacier` doesn't currently work.

**Comment by carlohamalainen** [comment]
See also: https://github.com/brendanhay/amazonka/pull/468

**Comment by endgame** [comment]
@carlohamalainen @DaveCTurner Any chance you can look into preparing a PR that does something like https://github.com/carlohamalainen/amazonka/commit/f44183d0053c58e99b22952dfc1d7d0673b17e0f but for current `develop`?

**Comment by LeifW** [comment]
@endgame I assume this was fixed by https://github.com/brendanhay/amazonka/pull/623, and should've been closed when that was merged. Though I don't know that that that was verified.

**Comment by endgame** [comment]
I see stuff like this all over `amazonka-glacier`, so I'm closing:

https://github.com/brendanhay/amazonka/blob/0433ee599feabd747a164bbc4445a08ff5364603/amazonka-glacier/gen/Network/AWS/Glacier/UploadArchive.hs#L183
