### ISSUE TITLE
ObjectVersionStorageClass needs STANDARD_IA?

### ISSUE THREAD

**Issue by rfn01** [brendanhay/amazonka#408]
I'm getting this SerializeError:

message = Failed reading: Failure parsing ObjectVersionStorageClass from value: 'standard_ia'. Accepted values: standard                            

I think this just needs STANDARD_IA added to the enum right under here:
https://github.com/brendanhay/amazonka/blob/68a83fa175539e890cf2b527fde37a1208dcc361/gen/model/s3/2006-03-01/service-2.json#L4655

I'm working on building with that change now.  If I get that working I'll send a PR...

Thanks!

/rob

**Comment by newhoggy** [comment]
I'm currently using this: https://github.com/brendanhay/amazonka/pull/498

**Comment by domenkozar** [comment]
See https://github.com/brendanhay/amazonka/pull/527

**Comment by endgame** [comment]
#597 should make this more robust and #609 is the reminder to check we have 'em all before we push out 2.0 RC.
