### ISSUE TITLE
Help doing this in other languages

### ISSUE THREAD

**Issue by rex-remind101** [brendanhay/amazonka#413]
Hello, this looks awesome. I'd like to attempt this same code generation process in a couple other languages. I was wondering if you could help point me to where the service definitions are hosted and possibly provide whatever documentation you follow for the service definitions that determines the structure and semantics of what is outputted by the generator.

For example I can look at https://github.com/brendanhay/amazonka/tree/develop/gen/model/apigateway/2015-07-09 and see that there's a bunch of JSON objects describing different entities for a service's sdk but I don't know what these objects actually mean, what they're intentions are, or what they are used for.

Any help would be most appreciated.

**Comment by penntaylor** [comment]
Disclaimer: I'm not associated with amazonka, aws, or amazon  in any way. I just saw this issue and thought I could provide some information.

The service description JSONs come from the botocore project for python. It's an AWS in-house project, so it gets "correct" service descriptions anytime something changes or a new service is added. The canonical service descriptions (for botocore) can be found at https://github.com/boto/botocore/tree/develop/botocore/data

I'm not aware of any explicit documentation of those JSON service descriptions. If you squint, they look a bit like a JSON version of WSDL. Probably a good place to start would be to look at the code botocore itself uses to parse those files into Python objects. Example: https://github.com/boto/botocore/blob/develop/botocore/model.py

The boto3 python API uses a slightly different version of the above:
https://github.com/boto/boto3/tree/develop/boto3/resources/model.py

**Comment by rex-remind101** [comment]
Awesome, I'll dive into those python models then and see what I can figure out. Thanks a bunch!
