### ISSUE TITLE
PutObjectACL doesn't support `[Grant]`

### ISSUE THREAD

**Issue by reactormonk** [brendanhay/amazonka#419]
E.g. adding two users with read permissions results in two requests. I'd expect to be able to add `[Grant]` to [`PutObjectACL`](https://www.stackage.org/haddock/lts-9.11/amazonka-s3-1.4.5/Network-AWS-S3-PutObjectACL.html), similar to [`GetObjectACL`](https://www.stackage.org/haddock/lts-9.11/amazonka-s3-1.4.5/Network-AWS-S3-GetObjectACL.html) `goarsGrants`.

**Comment by endgame** [comment]
It appears that this is (now?) doable. `PutObjectAcl` contains an `AccessControlPolicy` member:

https://github.com/brendanhay/amazonka/blob/ffdbd4b50092fbb591619010d2e5efe8551c215d/amazonka-s3/gen/Network/AWS/S3/PutObjectAcl.hs#L211

And an `AccessControlPolicy` can contain a `[Grant]`:

https://github.com/brendanhay/amazonka/blob/ffdbd4b50092fbb591619010d2e5efe8551c215d/amazonka-s3/gen/Network/AWS/S3/Types/AccessControlPolicy.hs#L33-L38
