### ISSUE TITLE
Codename O'Farrell

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#421]
@charleso Most of the discussed build improvements/simplifications are in #420. The next steps in no particular order are:

* Currently `amazonka-gen` requires `config/<boto_service_name>.json` file to exist. This should be turned into a warning so the generator will run through to completion even if there is a new/unseen service definition present.
* Create a 2-stage `generate` + `build` CI job where the generator runs in the first stage, and then the generated code is built in the second dependent stage. I'm unsure if this should be separate from the usual push + build CI workflow, or if in fact generated code should _only_ be committed back by a successful CI/generator run? It's possible the latter option while purer in principle, would lie upon the path to madness.
* Run the 2-stage build as a Travis Cron job (say, nightly). This should cover most `botocore` updates and give people a `nightly` branch they can use to get the latest version.
* The [documentation builds](http://brendanhay.nz/amazonka-doc/develop) have been disabled. `stack haddock` for the entire project is both consuming too much memory and taking too long to run - and then being killed by CI timeout. The most recent approach attempted to build documentation per `amazonka-*` library and then force push the updates to the GitHub pages repository. This was complicating the build scripts and just a bit shit in the general sense. I'd like to find another, possibly out of band solution to have up to date `develop` documentation (or the `nightly` branch) for people to refer to.
* Add an additional [override](https://github.com/brendanhay/amazonka/blob/afeb929c758c772fe83692a54978cf7bb05a9de5/gen/src/Gen/Types/Config.hs#L83) to `config/<boto_service_name>.json` which allows an `Other/Unknown` field to be emitted for an enum. The intent being only _some_ enum types could be extended deliberately with a field that will always succesfully encode/decode, such as `InstanceType = Unknown !Text | ...`. 
* Generating a nice `CHANGELOG.md` as part of the release process. It is currently (mostly) hand-rolled to try and decipher some of the upstream changes and keep it mostly to the point. A better policy regarding PR naming and my own personal branch/commit/squash messaging strategy would also go a long way.

Looking at Travis' staged build + cron documentation this should be possible - but a move to Gitlab CI could also be an option, as it has better support for pipelines + cron/triggered builds.

Additional steps that need to be documented:

* Running the generator (which is literally `make -C gen`).
* Releasing the project (`git flow release start ...; ./script/set-version 1.5.0 1.5.0; make -C gen`).

If you can help out with any of these - please feel free to open an issue or PR and go for it.

**Comment by charleso** [comment]
@brendanhay Thanks so much! We'll take a look and see if where we can help out over the next couple of weeks/months.
