### ISSUE TITLE
SQS message parsing complexity is super-linear in length

### ISSUE THREAD

**Issue by jessekempf** [brendanhay/amazonka#433]
I have an SQS producer and consumer I control. The producer batches a bunch of small records into a single message, for the sake of efficiency. I can select the upper bound on message size and it'll produce the appropriate number of messages and send them through SQS.

I've attempted two scenarios:
- 10 messages of 256 kB length
- 100 messages of 25 kB in length

Both scenarios account for approximately 2.5 MB of data.

Running single-threaded It takes approximately 13 seconds of CPU time to reduce the 100 messages to normal form using `Control.DeepSeq.force`. It takes approximately 150 seconds to reduce the 10 messages to normal form using `Control.DeepSeq.force`.

SQS message download is effectively instantaneous -- I've observed this using tcpdump. I think I have ruled out everything except the XML parser.

**Comment by jessekempf** [comment]
I believe the underlying cause might be related to https://github.com/snoyberg/xml/pull/118.

**Comment by MaxGabriel** [comment]
I think this can be closed based on the underlying issue being closed
