### ISSUE TITLE
Order of arguments to createSecurityGroup changed

### ISSUE THREAD

**Issue by rcook** [brendanhay/amazonka#439]
I just noticed that in change 2de11d0fa7f5eeb89dbfea32ce143bb4be53a06c (specifically at https://github.com/brendanhay/amazonka/commit/2de11d0fa7f5eeb89dbfea32ce143bb4be53a06c#diff-bca0cdb904543d15c42fc6d872ed01c3R86), that regenerated amazonka-ec2, the order of the arguments to `createSecurityGroup` was (seemingly arbitrarily) flipped from:

```
createSecurityGroup
    :: Text -- ^ 'csgGroupName'
    -> Text -- ^ 'csgDescription'
```

to

```
createSecurityGroup
    :: Text -- ^ 'csgDescription'
    -> Text -- ^ 'csgGroupName'
```

Since both arguments are of type `Text`, this will result in a breaking behavioural change in code that will continue to compile. This change tripped me up when migrating a project from version 1.4.5 to master of amazonka-ec2.

Would it be possible to generate methods like this with a `newtype` wrapper or equivalent to distinguish the arguments, e.g.

```
newtype SecurityGroupDescription = SecurityGroupDescription Text
newtype SecurityGroupName = SecurityGroupName Text
createSecurityGroup
    :: SecurityGroupDescription -- ^ 'csgDescription'
    -> SecurityGroupName -- ^ 'csgGroupName'
```

That way, at least, old code would fail to compile and would require manual developer intervention to remedy the problem instead of failing at runtime.

**Comment by rcook** [comment]
See also #435.

**Comment by endgame** [comment]
Closing as dupe of #435 .
