### ISSUE TITLE
Signing issue with http-types 0.11 and query strings with hex encoding

### ISSUE THREAD

**Issue by brynedwards** [brendanhay/amazonka#440]
Hi,

In http-types 0.11, [URI encoding changed to use lower-case hexadecimal instead of uppercase](https://hackage.haskell.org/package/http-types-0.11/changelog). It looks like this is causing issues with request signing. For example:

    listObjectsV "my-bucket" & lStartAfter .~ Just "/"

Will fail with http-types 0.11 only, with the request's query being `?list-type=2&start-after=%2f`, instead of `...&start-after=%2F` which happens with http-types 0.10 or earlier. In the [URI spec](https://tools.ietf.org/html/rfc3986#section-2.1) it says they should be equivalent but also "For consistency, URI producers and normalizers should use uppercase hexadecimal digits for all percent-encodings." so I'm not really sure how this should be handled. In the meantime, for anyone else who runs into this issue, adding `http-types < 0.11` to your project's cabal file is the easiest workaround.

Thanks.

**Comment by DanBurton** [comment]
Came here to report the same!

On the Stackage build server, I'm seeing test suite failures for:

* amazonka-ec2 (1 out of 5 tests failed)
* amazonka-s3 (2 out of 12 tests failed)
* amazonka-sqs (3 out of 7 tests failed)

Which were all related to this issue of uppercase vs lowercase.

Given what the URI spec says, I think we should ask the maintainer of http-types to upload a new version that goes back to uppercase.

**Comment by aristidb** [comment]
http-types 0.12 is released and should fix the issue

**Comment by phadej** [comment]
@brendanhay should we (you or me as Hackage Trustee) make revisions adding `http-types < 0.11 || http-types >= 0.12` to disallow *broken* `http-types-0.11.*` version?

**Comment by brendanhay** [comment]
Works for me, @phadej, thanks.

**Comment by brynedwards** [comment]
Closing. Thanks everyone.
