### ISSUE TITLE
Amazonka unable to use EC2 Instance Profiles?

### ISSUE THREAD

**Issue by ketzacoatl** [brendanhay/amazonka#443]
Hello,

I am running some executables (which use `amazonka`), on EC2 instances that have instance profiles to grant access to AWS resources through IAM, and without the need to set envvars. `amazonka` appears to choke on the fact that no cred/config files exist for the AWS tools. Or, if you provide those files, but try to omit the credentials, `amazonka` will error out:

```
cache-s3: InvalidFileError "/home/user/.aws/credentials, key aws_access_key_id Couldn't find key: aws_access_key_id"
```

Is it feasible for `amazonka` to support the use of instance profiles, if only with some flag or envvar?

**Comment by dudebout** [comment]
`amazonka` supports EC2 instance profile. If you create you environment with `newEnv Discover` (see https://hackage.haskell.org/package/amazonka-1.5.0/docs/Network-AWS.html for a full example), it will try to find credentials in `~/.aws/credentials`, before trying the instance profile.

From the error message you gave, it looks like your `~/.aws/credentials` file is malformed. Try to move it out of the way to see if your instance profile get picked. If this does not happen, check how you created your environment.

**Comment by ketzacoatl** [comment]
I have gotten a colleague to confirm the setup in a new env, and it worked fined with an EC2 instance. The issue is most likely in my env setup, so I am looking through that. Thanks for the confirmation, and sorry for the noise!
