### ISSUE TITLE
conduit-1.3 support

### ISSUE THREAD

**Issue by naushadh** [brendanhay/amazonka#449]
I noticed an open PR [#448 - Add conduit < 1.3 bound](https://github.com/brendanhay/amazonka/pull/448). ~~I take it that it's an interim strategy to get `amazonka` ecosystem to build with the current stackage LTS.~~

Are there plans to move to conduit-1.3 anytime soon? I'd be happy to help. Here's my first stab, [86fa620](https://github.com/naushadh/amazonka/commit/86fa620dfa7fcc4d6d0eb199b4eb4cae43faef21), `amazonka-core` patched and tests pass.

Shall I open a PR?

**Comment by domenkozar** [comment]
cc @brendanhay for lts-11.0

**Comment by domenkozar** [comment]
https://github.com/brendanhay/amazonka/pull/454

**Comment by etorreborre** [comment]
@brendanhay we (at Zalando) are also interested in this amazonka upgrade. Is there anything we can do to help besides the proposed PR?

**Comment by docmoxie** [comment]
@brendanhay @etorreborre likewise here at CJ Affiliate. Anything we can do to help get amazonka back into the newest LTS.

**Comment by domenkozar** [comment]
@brendanhay could we get a release?

**Comment by brendanhay** [comment]
@domenkozar Sure can.

**Comment by naushadh** [comment]
@domenkozar looks like release is [merged](https://github.com/brendanhay/amazonka/pull/459) and [published](https://hackage.haskell.org/package/amazonka-1.6.0).

**Comment by domenkozar** [comment]
Thank you @brendanhay <3
