### ISSUE TITLE
Does amazonka support SSL/TLS certificates from Amazon Trust Services?

### ISSUE THREAD

**Issue by MHova** [brendanhay/amazonka#453]
We use `amazonka` for DynamoDB access and we just got this email from AWS. Does the `amazonka` library need to be updated in any way?

> We recently analyzed your use of DynamoDB. During that process, we noticed you have a system that makes calls to DynamoDB using either an older AWS SDK or an unknown SDK that may not support SSL/TLS certificates issued by Amazon Trust Services (ATS).
>
> Beginning on May 14, 2018, Amazon DynamoDB will update the SSL/TLS certificates the service uses to secure communications. Once the update is complete, ATS will issue the SSL/TLS certificates used by DynamoDB. ATS is also the certificate authority (CA) used by AWS Certificate Manager.
>
> After DynamoDB migrates to certificates issued by ATS, applications that use an SDK (i.e., one that does not properly handle the new certificates) may stop working. In order for your application to continue to operate normally, you may need to migrate to a newer AWS SDK, or modify your custom SDK to trust ATS.
>
> The following documentation provides more information and guides you through the process: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ats-certs.html
>
> Thanks for using Amazon DynamoDB. Please contact AWS Support (https://aws.amazon.com/support) with any questions.

**Comment by MHova** [comment]
Does `amazonka` just use the certificates from the underlying operating system?

**Comment by brendanhay** [comment]
@MHova That is correct - `amazonka` uses the `http-client-tls`, `tls`, `connection`, and specifically [x509-system](http://hackage.haskell.org/package/x509-system) libraries, where the latter uses the global certificate store for your operating system. The paths for each OS are listed [here](http://hackage.haskell.org/package/x509-system-1.6.6/docs/src/System-X509-Unix.html)

**Comment by endgame** [comment]
Since `amazonka` uses the underlying OS certificates, the list of operating systems supporting ATS includes ancient OSes like Ubuntu 8.10, Windows (Jan 2005 updates or later) and macOS 10.4, and nobody else has complained about this in the three years this bug's been open, I think we're safe.
