### ISSUE TITLE
Missing ECS NetworkMode

### ISSUE THREAD

**Issue by techtangents** [brendanhay/amazonka#457]
Amazon ECS supports a new network mode "awsvpc", see:

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RegisterTaskDefinition.html#API_RegisterTaskDefinition_RequestSyntax

Amazonka doesn't have this. 
http://hackage.haskell.org/package/amazonka-ecs-1.5.0/docs/Network-AWS-ECS-Types.html#t:NetworkMode

I assume Amazonka needs to be updated to the latest AWS API.

Much appreciated. My team is using Amazonka in production and we love it.

**Comment by brendanhay** [comment]
Hi @techtangents - this is fixed in the upcoming [1.6.0.](#459) release, specifically https://github.com/brendanhay/amazonka/commit/b1f570808cd0848bf8e6e90878e3edef264cc33e.
