### ISSUE TITLE
RFC: Allow Unknown Generated Enum Branches

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#460]
Following on from the discussion in #418:

The deserializer for enums currently errors when it encounters an unknown value with an error like the following:

```
data ResourceStatus
    = CreateComplete
    | CreateFailed
    | CreateInProgress
    | DeleteComplete
    | DeleteFailed
    | DeleteInProgress
    | DeleteSkipped
    | UpdateComplete
    | UpdateFailed
    | UpdateInProgress
      deriving (Eq, Ord, Read, Show, Data, Typeable, Generic)

data StackResource = StackResource'
    { _srPhysicalResourceId   :: !(Maybe Text)
    , _srResourceStatusReason :: !(Maybe Text)
    , _srStackId              :: !(Maybe Text)
    , _srDescription          :: !(Maybe Text)
    , _srStackName            :: !(Maybe Text)
    , _srLogicalResourceId    :: !Text
    , _srResourceType         :: !Text
    , _srTimestamp            :: !ISO8601
    , _srResourceStatus       :: !ResourceStatus
    } deriving (Eq, Read, Show, Data, Typeable, Generic)
```

```
_serializeMessage =
    "Failed reading: Failure parsing ResourceStatus from value 'update_complete_cleanup_in_progress'.
        Accepted values:
            create_complete, create_failed, create_in_progress, delete_complete, delete_failed, delete_in_progress, delete_skipped, update_complete, update_failed, update_in_progress"
```

This is unfortunate and the root of many people's issues with needing a _very_ frequent `amazonka` release cadence. The proposed solution is to return the 'unknown' textual value instead of raising a serialization error. How that might look is the subject of this RFC.

**Comment by brendanhay** [comment]
### Adding an `Unknown Text` constructor to every generated enum

```haskell
data Stack
    = SPartyAnimals
    | SDevBlops
    | UnknownStack !Text
```

This has the unfortunate drawback pointed out by @charleso that pattern matching upon an unknown textual value has the potential to silently break or overlap - there is no way to distinguish between the actual exhaustive/known enum constructors and the unknown since they are conflated in the single data type and the pattern match ordering is entirely up to the programmer:

```haskell
case status of
    UnknownStack "dev-blops" -> 
    DevBlops ->
    ...
```

This seems to be the simplest change - at least on the surface.

**Comment by brendanhay** [comment]
### Force enums to be un/wrapped from a coproduct, like Either

Exposing the enum deserialization success or failure separately from any `SerializationError` results all enums having to be handled (or supplied) by the programmer as something analogous to `Either Text a`.
That is, accessing a product's field that contains an enum means you are required to unwrap and handle the error case. While somewhat invasive/unwieldy this allows the user to supply unsupported enum branches at their own peril, or pattern match on either the unhandled raw textual value, or the exhaustive 'known' enumeration branches.

What follows is how the generated code might look, as well as the smart constructor and lens from a product exposed to the user:

```haskell
data ResourceStatus
    = CreateComplete
    | CreateFailed
    | CreateInProgress
    | DeleteComplete
    | DeleteFailed
    | DeleteInProgress
    | DeleteSkipped
    | UpdateComplete
    | UpdateFailed
    | UpdateInProgress
      deriving (Eq, Ord, Read, Show, Data, Typeable, Generic)

data StackResource = StackResource'
    { _srPhysicalResourceId   :: !(Maybe Text)
    , _srResourceStatusReason :: !(Maybe Text)
    , _srStackId              :: !(Maybe Text)
    , _srDescription          :: !(Maybe Text)
    , _srStackName            :: !(Maybe Text)
    , _srLogicalResourceId    :: !Text
    , _srResourceType         :: !Text
    , _srTimestamp            :: !ISO8601
    , _srResourceStatus       :: !(UnknownEnum ResourceStatus)
    } deriving (Eq, Read, Show, Data, Typeable, Generic)

stackResource
    :: Text -- ^ 'srLogicalResourceId'
    -> Text -- ^ 'srResourceType'
    -> UTCTime -- ^ 'srTimestamp'
    -> Either Text ResourceStatus -- ^ 'srResourceStatus'
    -> StackResource
stackResource pLogicalResourceId_ pResourceType_ pTimestamp_ pResourceStatus_ =
    StackResource'
        { _srPhysicalResourceId   = Nothing
        , _srResourceStatusReason = Nothing
        , _srStackId              = Nothing
        , _srDescription          = Nothing
        , _srStackName            = Nothing
        , _srLogicalResourceId    = pLogicalResourceId_
        , _srResourceType         = pResourceType_
        , _srTimestamp            = _Time # pTimestamp_
        , _srResourceStatus       = _UnknownEnum # pResourceStatus_
        }

srResourceStatus :: Lens' StackResource (Either Text ResourceStatus)
srResourceStatus = lens _srResourceStatus (\ s a -> s{_srResourceStatus = a})
    . _UnknownEnum
```

Where `UnknownEnum` resides in `amazonka-core`:

```
-- Exists internally for de/serialization purposes.
data UnknownEnum a = Unknown !Text | Known !a

_UnknownEnum :: Iso (UnknownEnum a) (Either Text a)
_UnknownEnum = ...

instance FromXML/JSON/Text/etc a => FromXML/JSON/Text/etc (UnknownEnum a) where
    parser = fmap Known parser <|> fmap Unknown parser
```

**Comment by brendanhay** [comment]
The use of the externally exposed `Either Text a` in the approach above exists to avoid having to write instances, but is potentially less descriptive than just exposing `UnknownEnum` directly.

**Comment by MichaelXavier** [comment]
@brendanhay weighing in on this way late since I just got bitten by t3 instances not able to be parsed. I like the idea of the `UnknownEnum` as opposed to tacking an additional case onto the sum types that need it. It gives you uniform, recognizable pattern to code to rather than always having to be on the lookout for an Unknown case in your sum types. I don't know if I agree with the either. How many instances are we avoiding by doing this? Maybe half a dozen?

**Comment by rjmac** [comment]
There is another possiblity to either of the above possibilities.  The problem with both of them is that they turn into a relatively silent breakage when amazonka is updated to handle new enum values, because things that were formerly an `Unknown "foo"` become either `Foo` or `Known Foo`.  Perhaps the right thing to do is to compile all these possibly-changing enums as just a newtype wrapper around Text, and use pattern synonyms to define the known cases?  So for example the enum generation for `InstanceType` (to use #503's case) might generate code that looks like

```haskell
newtype InstanceType = InstanceType Text
pattern C1_Medium = InstanceType "c1.medium"
pattern C1_XLarge = InstanceType "c1.xlarge"
... etc ...
```

Possibly even, instead of deriving Show/Read instances, generate them explicitly so that they render/accept the patterns?

Anyway, this way code that needs to talk about new a t3.micro instance can just use `InstanceType "t3.micro"` (or whatever) and it keeps working when amazonka is later updated with a `T3_Micro` pattern.  One downside of this is of course that the "enumeration" is no longer an Enum nor Bounded, but really if its universe of values can evolve independently of amazonka those instances are kind of lies anyway.

**Comment by SamProtas** [comment]
Not to focus on specifics... but https://github.com/brendanhay/amazonka/issues/418 was closed with the comment that the specific issue was fixed in 1.6.0. I'm using 1.6.1 and I don't believe this is true:

http://hackage.haskell.org/package/amazonka-cloudformation-1.6.1/docs/Network-AWS-CloudFormation-Types.html#g:17

I get the same message as that issue (relevant part below):
`_serializeMessage = "Failed reading: Failure parsing ResourceStatus from value: 'update_complete_cleanup_in_progress'. Accepted values: create_complete, create_failed, create_in_progress, delete_complete, delete_failed, delete_in_progress, delete_skipped, update_complete, update_failed, update_in_progress"`

I'm all for a better "general purpose" solution going forward. But do we think we can fix the immediate issue sooner rather than later?

Apologies if I'm somehow missing something.

**Comment by denibertovic** [comment]
@brendanhay  I'm also hitting the t3 instance bug. Is there some kind of workaround until this is resolved?

**Comment by mbj** [comment]
@denibertovic I typically fork amazonka, edit the specifications (or update them) regenerate and build from my fork.

**Comment by mattsawyer77** [comment]
@mbj it's probably a dumb question, but how where are these specifications, and how do you regenerate them? In my fork, I was editing the generated code just as a temporary stopgap -- but this is clearly not a workable solution long-term.

**Comment by mbj** [comment]
> @mbj it's probably a dumb question, but where are these specifications, and how do you regenerate them? In my fork, I was editing the generated code just as a temporary stopgap -- but this is clearly not a workable solution long-term.

See `gen/Makefile` there are all the entrypoints for running the code generator.

See `gen/models` for the specifications. These are typically 1:1 provided by AWS and vendored in this repo.

Sometimes amazonka is behind, or the specs provided by AWS are wrong. Hence I sometimes need to edit them before generating.

**Comment by mbj** [comment]
@mattsawyer77 Here is a branch I made that does such a fixup:

https://github.com/mbj/amazonka/pull/1/commits

you see where I updated the specification (even current CF spec from AWS is missing these values) and the next commit where I checked in the new generated source.

**Comment by denibertovic** [comment]
> I typically fork amazonka, edit the specifications (or update them) regenerate and build from my fork.

@mbj yeah that's what I ended up doing as a quick hack. I didn't add a new spec but just edited the existing one with my changes and regenerated the code.

> it's probably a dumb question, but where are these specifications, and how do you regenerate them?

@mattsawyer77 What I did is `cd amazonka/gen &&  MODELS=model/ec2 make` . Of course that's just for regenerating the ec2 model. You can regenerate them all by omitting the MODELS env var. Also, run `make debug` to get a list of all the available models.

**Comment by mbj** [comment]
BTW: I'd prefer to not make the API more complex via the unknown value enum member, but instead pool together resources and provide timely updates to this library.

**Comment by mbj** [comment]
And also a set of amazonka overlays for the AWS service files, where AWS clearly documents their own service wrong.

**Comment by brendanhay** [comment]
Rather than editing the model files directly and being forced to patch/discard changes when `make` is run, you can add a corresponding override under [./annex](https://github.com/brendanhay/amazonka/tree/develop/gen/annex) which will be [merged](https://github.com/brendanhay/amazonka/blob/29a6806fb01b22d0a58d455644cbea777ce41b43/gen/src/Gen/JSON.hs#L53-L63) with the service definition with the same name. For example, to correct the generated constructors for a nullary union you would provide the comprehesive enum values under:

```
# ./gen/annex/<service_name>.json
{
    "shapes": {
        { "<TYPE_NAME>": {
            "enum": [
                 "<VALUE1>",
                 "<VALUE1>",
                 ...
            ]
        }
    }
}
```

See the [EC2](https://github.com/brendanhay/amazonka/blob/29a6806fb01b22d0a58d455644cbea777ce41b43/gen/annex/ec2.json#L6-L14) annex for the equivalent of your PR without modifying the service definition.

These annex files are probably what you intend when you say 'overlays'. There is also generator configurator to control emitted prefixes, existing prelude type replacments and required/optional fields under [./config](https://github.com/brendanhay/amazonka/blob/develop/gen/config/ec2.json).

This issue exists because even with timely updates to the configuration - the build times, release turnaround, and speed at which AWS evolves in what should be a forwards compatible way breaks the brittle serialisation primitives - meaning people will still encounter runtime errors in production and still be subject to their own dependency update, rebuild, and redeploy lifecycle on top of whatever overhead we have.

In general I've gone cold on the idea of an `Unknown`  constructor and would rather offer people an API to choose how to handle serialisation errors. Some ways to deal with this are:

1. Offer an API that returns a raw HTTP response witnessed by the expected response value (currently denoted by the type family `Rs`), which you can then _optionally_ parse into the expected response:

```haskell
newtype Response (a :: *) = Response (HTTP.Client.Response ByteString)

send :: a -> m (Response (Rs a))
send = ...

parse :: Response a -> m a
parse = ...

example = do
    raw      :: Response PutItemResponse <- send (putItem "foo" "bar")
    response :: PutItemResponse <- parse raw
    ...
```

This effectively splits the current `send` functionality into two separate combinators, `send` to obtain the raw response and `parse` to obtain the expected Haskell value.

2. Further granularise the parsing by parameterising over either a functor `f :: * -> *` or use a trees-that-grow-esque type family to encode the presence or absence of partiality:

```haskell
-- Or whatever monad is used to de/serialise goes in here:
newtype Serialiser a = Serialiser { runSerialiser :: Either String a }
    deriving newtype (Functor, Applicative, Monad)

data Raw
data Parsed

type family Stage (s :: *) (a :: *) where
    Stage Raw    a = Serialiser a
    Stage Parsed a = a

newtype Bucket = Bucket Text

data Region = Taranaki | Rotorua | Galatea

data PutItemResponse s = PutItemResponse
    { key    :: Stage s Text
    , bucket :: Stage s Bucket
    , region : Stage s Region
    }

data PutItem = PutItem

instance AWSRequest PutItem where
    type Rs PutItem = PutItemResponse Raw

-- Specialising send/parse from the previous example

newtype Response (a :: *) = Response (HTTP.Client.Response ByteString)

send :: a -> m (Response (Rs a))
send = ...

-- a ~ Rs PutItem, see 'type Rs PutItem' above.
parseResponse :: Response a -> m a
parseResponse = ...

-- Parse each field, possibly accumulating errors via either:Data.Either.Validation
parseValue :: f Raw -> m (f Parsed)
parseValue = ...

example = do
    raw      :: Response (PutItemResponse Raw) <- send (putItem "foo" "bar")
    response :: PutItemResponse Raw <- parseResponse raw
  
    -- Parse the entire nested response strucutre:
    value :: PutItemResponse Parsed <- parseValue response

    -- Parse only a single item from the response structure:
    case runSerialiser (region response :: Serialiser Raw Region) of
        Left  (err :: String) -> ...
        Right (ok  :: Region) -> ...
    ...
```

With all of this could be wrapped up into the existing combinators such that we parse the entire response structure by default.

Personally I'd prefer an API where I can declare the conformity of a response - sometimes I only care about status codes and would rather skip parsing altogether - and other times I need specific values out of the response - in both cases running into serialisation errors due to the libraries inability to handle forwards compatibility is currently frustrating.

**Comment by SamProtas** [comment]
@brendanhay if you've leaning away from the Unknown constructor have you considered @rjmac 's idea from above? That seems like a nice upgrade path that solves backwards library compatibility and forwards "new enum without a library release" compatibility.

**Comment by denibertovic** [comment]
> Rather than editing the model files directly and being forced to patch/discard changes when make is run, you can add a corresponding override under ./annex which will be merged with the service definition with the same name. 

@brendanhay when I try and add new ec2 instance types that are missing from the service json file it does not merge the annex list (enum) with the one from the service file but rather it overrides it. 

Here's what I did. I edited: gen/annex/ec2.json and added this into the existing shapes key:

```
        "InstanceType":{
            "enum":[
                .....
            ]
         }
```

I listed some missing instance types that I need.

Then I ran: `MODELS=model/ec2 make`

Once the command finished `git diff` clearly shows that it deleted all the other instance types and only listed the ones in my annex file. Is this intended or am I doing something wrong?

**Comment by brendanhay** [comment]
@denibertovic the [JSON merge](https://github.com/brendanhay/amazonka/blob/09e492b3dfbfd7be76517d3b761e8887bc178258/gen/src/Gen/JSON.hs#L53-L63) is only a recursive `HashMap.unionWith` over objects. This could be possibly extended to say, concatenate arrays. There's no particular reason that it doesn't other than personal laziness.

**Comment by brendanhay** [comment]
@SamProtas Sorry, I missed your message. I've actually implemented @rjmac's proposal in a new experimental code generator for amazonka/google, which I think is the superior/longer term approach for dealing with these evolving enumerations. The Read/Show instances can be mechanised by the generator and the existing Enum/Bounded instances were a minor mistake that I'm happy to do away with.

**Comment by denibertovic** [comment]
>  the JSON merge is only a recursive HashMap.unionWith over objects. This could be possibly extended to say, concatenate arrays.

@brendanhay  Ah I thought as much. I was able to extend it for concatenating arrays. It seems to be working fine now. One thing that I noticed is that it's somehow (probably in some other part of the code) magically removing duplicate elements. What I mean is that I had the same entry in both the service.json array as well as in the annex array. I was thinking I'd get a type error warning me about duplicate constructors or something but somehow it only generated the sum type constructors once...which is the correct thing to do. Anyway thanks for the tip. I can make a PR for that if you want? 
I went through the AWS docs and the service json file we have in the repo and added all the missing instances
to the annex file. I'm not sure if you'd want that as a PR as well?

I had another question which is only tangentially related to this issue so I apologize if it would be better to ask somewhere else. Is `data Region` from [here](https://github.com/brendanhay/amazonka/blob/master/core/src/Network/AWS/Types.hs#L672) also generated from some json file or is that manually written? Cause I noticed there are some missing regions that I'd like to use (eu-west-3 for instance).

**Comment by denibertovic** [comment]
Hey @brendanhay what's the current status of this? Any chance there's a way to extend the regions enum?

**Comment by brendanhay** [comment]
@denibertovic https://github.com/brendanhay/amazonka/pull/597 - modulo some `case-insensitive` concerns.

**Comment by endgame** [comment]
The aforementioned PR has landed. Despite earlier comments, amazonka has gone with newtypes and pattern synonyms, including for the `Region` type. I'll close this, but reopen if that's an error.
