### ISSUE TITLE
Conduit bounds for amazonka-s3-encryption are incorrect

### ISSUE THREAD

**Issue by HuwCampbell** [brendanhay/amazonka#462]
In amazonka-s3-encryption there are direct imports of the `Conduit` module, which has only existed since `1.3`, even though the cabal bounds are for 

```
conduit >= 0.3
```

My preferred solution would be to import Data.Conduit so earlier versions could be used if desired; but fixing up the bounds so we don't see compilation errors would be ok.

**Comment by endgame** [comment]
Fixed in develop:
https://github.com/brendanhay/amazonka/blob/6846721de1c95984c2c9563b80f7935d8bb9ef8e/amazonka-s3-encryption/amazonka-s3-encryption.cabal#L98
