### ISSUE TITLE
Support for AWS config file

### ISSUE THREAD

**Issue by tswelsh** [brendanhay/amazonka#476]
When using the AWS CLI we make use of profiles, defined in `~/.aws/config`, not `~/.aws/credentials`.  The CLI can lookup profiles in there then fetch the credentials from `~/.aws/credentials` ([here](https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html)), and it looks like `boto3` can do this too ([here](https://boto3.readthedocs.io/en/latest/guide/configuration.html#configuring-credentials)).  However the docs for the Java and Javascript SDKs don't appear to mention this.  Are there plans to support making use of the `config` file in amazonka?

**Comment by endgame** [comment]
bae6e40ad3ee5658fbee35f8d93373e4498e5f10 Added basic parsing of the `config` file, but looks like it's only for regions at this stage.

**Comment by endgame** [comment]
If #746 gets merged, I'll close this issue. It supports most of the major features of the config files, and any minor differences between Amazonka and the SDKs can be dealt with in individual smaller issues.
