### ISSUE TITLE
"You do not need any credentials to call this API"

### ISSUE THREAD

**Issue by NickAger** [brendanhay/amazonka#483]
Hi,

I'm calling AWS Cognito [GetId](https://github.com/brendanhay/amazonka/blob/develop/amazonka-cognito-identity/gen/Network/AWS/CognitoIdentity/GetId.hs#L72) and Cognito [GetCredentialsForIdentity](https://github.com/brendanhay/amazonka/blob/develop/amazonka-cognito-identity/gen/Network/AWS/CognitoIdentity/GetCredentialsForIdentity.hs#L76) neither of which  require credentials to call. 

I'm calling using:

    runResourceT $ runAWS env $ send getIdAPI

where `env` appears to require `credentials`. Currently I'm supplying dummy credentials to call these APIs. This works but feels a bit ugly. Is there a better way to call amazonka APIs without needing to supply credentials?

**Comment by endgame** [comment]
There isn't, to my knowledge. This would also affect things like S3 buckets where the policy allows `"Principal": "*"`, so perhaps it's something worth looking at after 2.0?
