### ISSUE TITLE
Amazonka and Gogol Project Status Update

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#484]
Hi folks,

I just wanted to share an update about the status of open issues for both [amazonka](https://github.com/brendanhay/amazonka) and [gogol](https://github.com/brendanhay/gogol).

Since both projects have been lagging behind with regards to issue resolution and Hackage/Stackage releases, I will be spending the end of August and early September working full-time on both projects to get everything back in shape and the reported bugs ironed out, as well as adding support for any new APIs.

Thanks for your patience!

Related: brendanhay/gogol#110

**Comment by MichaelXavier** [comment]
@brendanhay thanks for the update! Also, would you be open to setting up any regular contributors with the ability to do releases and other project admin? Just looking to avoid having all the burden fall on you.

**Comment by jdreaver** [comment]
Thanks for all your hard work on `amazonka` @brendanhay! This library has been invaluable in so many projects for me.

I agree with @MichaelXavier. Increasing the bus factor of `amazonka` seems ideal given how many people rely on it. We've been fine so far just pinning old versions or using forks, but integrating fixes into the main `amazonka` codebase quicker would certainly make life simpler (for us and all other users!) :smile:

**Comment by LeifW** [comment]
Could other people be granted permission to merge PRs and also possibly publish releases to hackage?

**Comment by brendanhay** [comment]
@LeifW Sure. I'll contact interested parties out via email - if you'd like to put your name forward for Amazonka and/or Gogol - please contact me directly via my maintainer email in the `.cabal` file.

**Comment by asheshambasta** [comment]
I’m new to Haskell but I’d love to contribute. I haven’t really used these libraries but I’m sure I will somewhere in future.

**Comment by saurabhnanda** [comment]
Wrt https://www.reddit.com/r/haskell/comments/9uemnd/amazonka_gogol_help_with_maintenance/ let me know if you need help in maintaining the libraries. We're moderate-to-heavy users of `gogol` and already solved a few open issues in our fork/branch.

**Comment by jproyo** [comment]
Love to help to solve some issues if you want. Let me know.

**Comment by MichaelXavier** [comment]
@saurabhnanda I can't find where it was posted but Brendan mentioned if folks want to take a larger role to email him for access to the github. I got access myself but haven't had the free time to get a release out so if you are interested, I'd say go that route. I think what we need most right now is a review of the release project and to get the currennt version out, provided it is in good working order.
