### ISSUE TITLE
DynamoDB: seems impossible to determine "type" of AttributeValue for empty lists and maps

### ISSUE THREAD

**Issue by aztecrex** [brendanhay/amazonka#486]
AttributeValue provides access to its data members through lenses only. However, the lenses `avL` and `avM` view default values (`mempty`) if their corresponding data members, `_avL` and `_avM` equal `Nothing`.  All other lenses have attribute type `Maybe a` for the appropriate `a`.

Thus through the lenses,  it appears impossible to determine the difference between an uninitialized `AttributeValue`, one with an empty list value, and one with an empty map value.

The record access functions, `_avL` and `_avM` are not exported and their module is hidden.

I know it would break backward compatibility to change the lens behavior for those two lenses and make them the same shape as the others. Maybe a couple of additional lenses or even a detection function?

Most of the time, the context tells the story (e.g. there is an attribute name) but i have a case where it is user-defined data and I need to convert to an empty list or map depending on their intent and I am stuck with the existing schema.

Some workarounds for greenfield DBs are to wrap with a tagging map or to disallow empty lists or maps. But for existing data, this can be a hard problem unless I am missing some understanding of `AttributeValue` .

**Comment by colbyn** [comment]
I have the same problem trying to serialize the lens based version into an AST.
```
data DynamoIR
  = List [DynamoIR]
  | Map (HashMap Text DynamoIR)
  | Null
  | Number Text
  | String Text
  | Bool Bool
```

**Comment by colbyn** [comment]
Actually it just occurred to me that `AttributeValue` has Aeson and Generic instances…

**Comment by imuli** [comment]
> Actually it just occurred to me that `AttributeValue` has Aeson and Generic instances…

Yes, this is the route I eventually took. Convert to Aeson `Value`s, normalize that, and then use my target types `FromJSON` instances.

**Comment by endgame** [comment]
The version of `amazonka-dynamodb` currently in `develop` has an `AttributeValue` type with `Maybe` around all fields:

https://github.com/brendanhay/amazonka/blob/ffdbd4b50092fbb591619010d2e5efe8551c215d/amazonka-dynamodb/gen/Network/AWS/DynamoDB/Types/AttributeValue.hs#L36-L86

Once 2.0 is released, I could see scope for a library to convert between `amazonka-dynamodb`'s `AttributeValue` type and a lightweight AST. Possibly outside of `amazonka` itself.

**Comment by endgame** [comment]
It may also be possible to wrangle the way `amazonka-dynamodb` is generated to parse into a better AST, but that would be a new issue.
