### ISSUE TITLE
No explicit implementation for ‘generalBracket’

### ISSUE THREAD

**Issue by phadej** [brendanhay/amazonka#487]
`exceptions-0.10` added a `generalBracket` member to `MonadMask`.
(`exceptions-0.9` is not worth supporting - it has different and broken `generalBracket`).

```haskell
src/Control/Monad/Trans/AWS.hs:212:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘generalBracket’
    • In the instance declaration for ‘MonadMask (AWST' r m)’
    |
212 | instance MonadMask m => MonadMask (AWST' r m) where
```

https://github.com/brendanhay/amazonka/blob/248f7b2a7248222cc21cef6194cd1872ba99ac5d/amazonka/src/Control/Monad/Trans/AWS.hs#L212

Should be easy to fix.

**Comment by nhibberd** [comment]
> Should be easy to fix.

I'd recommend adding some CPP and put a PR up!
