### ISSUE TITLE
Open connections are leaking

### ISSUE THREAD

**Issue by neongreen** [brendanhay/amazonka#490]
I do a bunch of `SQS.deleteMessage`s in a loop, and experience long waits (5-10 seconds) after getting 99 open connections. This happens with https://github.com/iain/fake_sqs (I haven't tested with real SQS).

This behavior is introduced by a recent commit (made after 1.6.0 was released): https://github.com/brendanhay/amazonka/commit/2688190f659e4d87fd6862b52b04be706b17d251.

My guess is that in the absence of finalizers in conduit-1.3, nothing is closing connections open by `Response`s. The following diff fixes the behavior of `deleteMessage` for me:

```diff
diff --git a/core/src/Network/AWS/Response.hs b/core/src/Network/AWS/Response.hs
index 4791de6a3c..907b0faa05 100644
--- a/core/src/Network/AWS/Response.hs
+++ b/core/src/Network/AWS/Response.hs
@@ -45,8 +45,9 @@ receiveNull :: (MonadResource m, MonadThrow m)
             -> Proxy a
             -> ClientResponse
             -> m (Response a)
-receiveNull rs _ = stream $ \_ _ x ->
-    liftResourceT (x `connect` pure (Right rs))
+receiveNull rs _ = stream $ \_ _ x -> do
+    sinkLBS x
+    pure (Right rs)

 receiveEmpty :: (MonadResource m, MonadThrow m)
              => (Int -> ResponseHeaders -> () -> Either String (Rs a))
```

It's still slower than it used to be (I've no idea why), but at least it doesn't leak connections anymore and I get no stuck requests.

Other `receiveBlah` functions might also be affected.

**Comment by naushadh** [comment]
Perhaps [`sinkNull`](http://hackage.haskell.org/package/conduit-1.3.0.3/docs/Data-Conduit-Combinators.html#v:sinkNull) would be quicker?

**Comment by neongreen** [comment]
Perhaps. I didn't know it existed.

**Comment by LeifW** [comment]
Maybe related to https://github.com/brendanhay/amazonka/issues/475?
I was getting a memory leak because apparently things are not freed until you call `responseBody` on the response (or `runResourceT`) - and when the responses are just things like 202's or 204's (no content) `responseBody` is not called. I also talked about it some in the Amazonka gitter channel. My workaround was to just `runResourceT` on every request.

**Comment by neongreen** [comment]
> My workaround was to just runResourceT on every request.

This is basically what amazonka-1.6.0 is doing, but that's broken in the presence of streaming (connections are being closed too early): #466

**Comment by neongreen** [comment]
Thanks! I'm going to wait for a better fix though, since amazonka is used quite a bit at Wire and I'd rather not depend on nobody accidentally calling "bad" functions. But maybe this workaround will be useful to someone!

**Comment by neongreen** [comment]
@brendanhay I intend to make a pull-request for this, but I'd love if you (or somebody else) could look at the issue briefly and tell me whether just fixing the `receive*` family of functions (https://github.com/brendanhay/amazonka/blob/248f7b2a7248222cc21cef6194cd1872ba99ac5d/core/src/Network/AWS/Response.hs#L41-L105) would be enough or you anticipate that more functions would have to be fixed.
