### ISSUE TITLE
Should `Network.AWS.Internal.HTTP.retrier` log an error each time a request fails?

### ISSUE THREAD

**Issue by gridaphobe** [brendanhay/amazonka#501]
This is the current behavior, but it seems a bit severe. I usually try to reserve error-level logging for issues that someone needs to take a look at (generally with automated alerts). A request failing initially but succeeding later doesn't seem to rise to that level.

Perhaps it would make more sense to log only the final failure as an error, and the intermediate ones as info or warnings?

**Comment by endgame** [comment]
The other thing we could do is log the retrying failures at a noisier log level, but we've gotten this far without it so let's get 2.0 out first and think about this later.

**Comment by endgame** [comment]
#875 calls `logDebug` on all failures and `logError` on the final failure.
