### ISSUE TITLE
Handle new EC2 InstanceType t3

### ISSUE THREAD

**Issue by ianbamforth** [brendanhay/amazonka#503]
Amazon released a new family of instance types, `t3`, back in mid-August 2018. If you have one of these instances running, and attempt to use any `amazonka` function that parses the InstanceType, you get e.g. `Failure parsing InstanceType from value: 't3.large'. `

**Comment by nhibberd** [comment]
Similar conversation from https://github.com/brendanhay/amazonka/issues/418 and https://github.com/brendanhay/amazonka/issues/460

**Comment by ianbamforth** [comment]
Good spot @nhibberd , seems to have gone pretty quiet over there though. Handling unknown resource types would definitely be a huge step in making amazonka suitable for production environments.

**Comment by brendanhay** [comment]
I'll work on adding an `Other` constructor specifically for `InstanceType` as an immediate solution. I feel lukewarm about either of the solutions for unknown enumeration values outlined in #460, I'd suggest people with opinions have a look at that issue and add your voices there.

**Comment by ianbamforth** [comment]
@brendanhay the `Other` thing would be great as a stop-gap - I have no strong feelings about a more permanent solution, I'd just like to be able to use `amazonka` in production, and at the moment it's not possible! Do you plan to make a new release any time soon?

**Comment by kubek2k** [comment]
@brendanhay I think its similar issue with Runtime for Lambdas (which also change quite rapidly)

**Comment by endgame** [comment]
#597 has switched to using a newtype and pattern synonyms, so this can now be worked around.

https://github.com/brendanhay/amazonka/blob/0433ee599feabd747a164bbc4445a08ff5364603/amazonka-ec2/gen/Network/AWS/EC2/Types/InstanceType.hs#L420-L423
