### ISSUE TITLE
Network.AWS.RDS.RestoreDBInstanceFromDBSnapshot is missing VpcSecurityGroupIds.VpcSecurityGroupId.N

### ISSUE THREAD

**Issue by ChrisCoffey** [brendanhay/amazonka#508]
The ability to add additional security groups to a restored instance was added in October/November.

**Comment by endgame** [comment]
Looks like a regeneration has put these on latest `develop`. Closing:
https://github.com/brendanhay/amazonka/blob/0433ee599feabd747a164bbc4445a08ff5364603/amazonka-rds/gen/Network/AWS/RDS/RestoreDBInstanceFromDBSnapshot.hs#L176-L180
