### ISSUE TITLE
Amazon Textract support

### ISSUE THREAD

**Issue by alexanderkjeldaas** [brendanhay/amazonka#509]
https://aws.amazon.com/textract/

**Comment by endgame** [comment]
Crossing fingers that this is just "get service description, generate and go".

**Comment by ketzacoatl** [comment]
@endgame Given the position we're in, I would advocate for for new services being a separate 2.1 release or whatever. Eg, make the milestone for 2.0 about dire issues, release blockers, and stuff that must be done for the release. Let the rest fall into a follow-up release we make soon after. The sooner we get 2.0 out, the sooner we'll get a 2.1 and on. Just my 2c, feel free to ignore :)

**Comment by brendanhay** [comment]
Now part of `develop`.
