### ISSUE TITLE
Native AssumeRole credentials support

### ISSUE THREAD

**Issue by copumpkin** [brendanhay/amazonka#514]
Poking around the code a bit, the `Credentials` type feels a bit confusing to me. For example, it's unclear why `FromContainer` is an explicit option for getting temporary credentials the ECS way, but there's no equivalent `FromEc2Metadata` constructor for getting them the EC2 way, and you need to use the much more complicated `Discover` constructor for that, or manually retrieve them yourself and feed them into `FromSession`. The reason I bring this up is because factoring these out slightly differently could open up a neat possibility:

There's some nice support for an automatic expiration thread for those temporary credentials that could greatly benefit dynamic `AssumeRole` support, which I use extensively. What I'd like to be able to do, ideally, is `newEnv (Chain Discover [AssumeRole "arn:aws:iam::12345:role/foo" "mysession", AssumeRole "arn:aws:iam::23456:role/bar" "anothersessionid"])` and have amazonka automatically make the STS `AssumeRole` calls for me, as well as handling credential expiry threads for all three sets of temporary credentials.

Any thoughts? I could throw a version of it into a PR if anyone was interested, but I wanted to float the idea before putting effort into it.

**Comment by endgame** [comment]
This would be cool, and also a possible solution to the "are we on an EC2 instance?" question that we currently have to (imperfectly) answer (see #271). Definitely a post-2.0 question.

Ping @brendanhay in case he has thoughts and/or objections to a rethink of how we select credentials.
