### ISSUE TITLE
Update models

### ISSUE THREAD

**Issue by copumpkin** [brendanhay/amazonka#515]
A lot of neat stuff has come out since the latest Amazonka release, including updated APIs for existing services (for example Secrets Manager supports resource policies!) and a bunch of stuff from re:Invent. Is it easy to update the Amazonka APIs to match the latest JSON models from the official SDK?

**Comment by copumpkin** [comment]
@brendanhay have any thoughts on this?

**Comment by surt666** [comment]
Would like an update too, to get DynamoDb transactions. No idea how hard it is to update, but seems it auto generates from the models, so shouldn't be too hard if you know what you're doing. I unfortunately don't yet

**Comment by nhibberd** [comment]
Attempting to update existing models here ~ https://github.com/brendanhay/amazonka/pull/522

**Comment by endgame** [comment]
There's been at least one round of regenerated models since this issue was filed, so I'm going to close it.
