### ISSUE TITLE
Feature request: support for custom source type in OpsWorks AppSource

### ISSUE THREAD

**Issue by mossprescott** [brendanhay/amazonka#518]
This is probably a long shot, but I have run into a situation where it seems I am unable to use amazonka-opsworks's `describeApps`, because I have an unexpected value in the `AppSource:Type` property of some apps:

```
"AppSource": {
  "Type": "other", 
  "Revision": "1.0-circle3539"
}, 
```

This is not one of the four documented values for this property, but tools such as aws-cli seem to be unbothered by it. Furthermore, I'm able to use `updateApp` to change other properties of the app:

```haskell
  void . send $ OW.updateApp (T.unAppId resolvedAppId)
    & OW.uaAppSource ?~ (OW.source & OW.sRevision ?~ deployVersion)
```

In my new use case, I'm actually only interested in the `Name` and `Id` properties of the app, and won't be looking at `AppSource` at all, but `describeApps` fails with a SerializationError and it's not clear if it's possible to get around it:

```
SerializeError (SerializeError' {
_serializeAbbrev = Abbrev "OpsWorks",
_serializeStatus = Status {statusCode = 200, statusMessage = "OK"}, 
_serializeBody = Just "{\"Apps\":[{\"AppSource\":{\"Revision\":\"1.0-circle3539\",\"Type\":\"other\"}
...
}", 
_serializeMessage = "Error in $[0].AppSource.Type: Failed reading: Failure parsing SourceType from value: 'other'. Accepted values: archive, git, s3, svn"})
```

Leaving aside the question of whether this is a good idea (I acknowledge it probably is not), is there anything I can do to work around this issue so I can use `describeApp` to inspect the other properties of the app?

Possibilities I can think of: 

1. fork this repo and hack in an `Other` constructor for `SourceType`
2. somehow hook into the parsing of the response and maybe access the raw JSON value?
3. create my own `DescribeApps` request type with a different response type? 

I'm not sure if either of the latter two are actually possible, but I will look into it and follow up with anything I discover.

Thanks for any guidance.

**Comment by mossprescott** [comment]
Update: I was able to work around this by implementing an alternative `DescribeAppsMin` which only decodes `Name`, `Id`, and `StackId`. It's not a ton of code, so I think this is probably the solution I'll go with for now.

I'll leave this issue open for a bit in case anyone else cares to comment.

**Comment by endgame** [comment]
Seems like the #597 change has given you what you need, at least on `develop`:
https://github.com/brendanhay/amazonka/blob/0433ee599feabd747a164bbc4445a08ff5364603/amazonka-opsworks/gen/Network/AWS/OpsWorks/Types/SourceType.hs#L34-L37
