### ISSUE TITLE
Having problems sending synthesized text (Polly) to S3  

### ISSUE THREAD

**Issue by markosski** [brendanhay/amazonka#519]
Here's what I have so far. 
```
runResourceT . runAWST env $ do
        rs   <- view ssrsAudioStream `fmap` send req
        fout <- rs `sinkBody` CB.sinkFile "/tmp/synthed_file"
        fin  <- chunkedFile (1024*1024) "/tmp/synthed_file"
        void $ send $ putObject bucket key fin
```
How can I avoid writing to temporary file and pipe result of ssrsAudioStream directly to S3?

Any help appreciated.

**Comment by endgame** [comment]
I'd use https://hackage.haskell.org/package/amazonka-s3-streaming , which can accept a conduit directly and performs a multipart upload.
