### ISSUE TITLE
Add EU (Paris) region

### ISSUE THREAD

**Issue by k-bx** [brendanhay/amazonka#520]
And maybe others missing. Paris is for `eu-west-3`.

Thanks!

**Comment by MichaelXavier** [comment]
I think this may end up getting resolved by #522

**Comment by teto** [comment]
As there is no release so far, is there an escape hatch to be able to use Paris even with older versions ? like passing  "eu-west-3" ?

**Comment by k-bx** [comment]
My escape hatch is to fork, codegen amazonka there, actually commit and use that repo, but yeah, a release would be nice.
