### ISSUE TITLE
amazonka-gen notation parser

### ISSUE THREAD

**Issue by nhibberd** [brendanhay/amazonka#521]
Have been taking a look at regenerating the models and have been hitting issues around `model/data/ec2/`. Digging in a little deeper

```
# ec2/2016-11-15/paginators-1.json

    "DescribePublicIpv4Pools": {
      "input_token": "NextToken",
      "limit_key": "MaxResults",
      "output_token": "NextToken",
      "result_key": "PublicIpv4Pools"
    },
```

The `result_key` here is being parsed as:

```
> parseNotation "PublicIpv4Pools"
Right (Access (Key {fromKey = Id "PublicIpv" "PublicIPv"} :| []))
```

which is causing loop issues later on

Will take a look at fixing it but thought I would raise it here first

**Comment by nhibberd** [comment]
https://github.com/brendanhay/amazonka/commit/7c755337e52b3ce4b2beb676a44e686201713e0d

**Comment by endgame** [comment]
I've seen a generation bug with `Ipv` get marked as resolved, so I'm going to assume the generator has matured over the past couple of years.
