### ISSUE TITLE
Release versions of amazonka-* that can build with http-client-0.6.*

### ISSUE THREAD

**Issue by DanBurton** [brendanhay/amazonka#532]
This has keept amazonka out of the Stackage nightly build for nearly 4 months now; I'd like to see this addressed before we cut the next lts major series.

See also, the http-client changleog: http://hackage.haskell.org/package/http-client-0.6.4/changelog

**Comment by borsboom** [comment]
This could even be done with just a hackage metadata update, since supporting http-client-0.6.* doesn't require any code changes (see https://github.com/brendanhay/amazonka/pull/526#issuecomment-494595977).

**Comment by DanBurton** [comment]
Bump. Amazonka is currently omitted from lts-14; I would like to see it added back in if possible.

**Comment by newhoggy** [comment]
I'd also like to see this bumped.

**Comment by newhoggy** [comment]
Any updates on when the metadata can be update?

**Comment by gwils** [comment]
As a hackage trustee, I've made a metadata revision to allow the latest versions of amazonka and amazonka-core to build with http-cleint 0.6.*

**Comment by newhoggy** [comment]
Thanks!

**Comment by endgame** [comment]
Upper bounds for `http-client` in `develop` branch are `< 0.8`, so we should be good.
