### ISSUE TITLE
PutObject inserts empty Content-Encoding?

### ISSUE THREAD

**Issue by mgajda** [brendanhay/amazonka#536]
It seems that `PutObject` inserts empty `Content-Encoding: ` stance that may break some clients, since AWS S3 treats it as metadata.

Steps to replicate:
1. Run this snippet after changing bucket name:
```
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Network.AWS
import Network.AWS.S3
import Network.AWS.S3.PutObject
import Control.Lens

bucketName = "YOUR-BUCKET-NAME"

main = do
  env  <- newEnv Discover
  runResourceT $ runAWS env $
    within Frankfurt $ do
      content <- chunkedFile 8192 "public/index.html"
      send $ set poContentType     (Just "text/html")
               $ putObject bucketName (ObjectKey "index.html") content
```
2. Check metadata of new S3 object on AWS Console:
https://s3.console.aws.amazon.com/s3/object/YOUR-BUCKET-NAME/index.html?region=eu-west-1&tab=properties
![Metadata screenshot](https://user-images.githubusercontent.com/685529/62004426-4588a480-b125-11e9-8331-c4c5b133671c.png)

Note that one just cannot set `set poContentEncoding (Just "identity")` without breaking request signing:
```
*** Exception: ServiceError (ServiceError' {_serviceAbbrev = Abbrev "S3", _serviceStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, _serviceHeaders = [("x-amz-request-id","C211E7670B81BA51"),("x-amz-id-2","VdRQD1mnawJ2iXGc+CYJnPNsH8ZPtIiWcUqZUieBuOh4SBZXZNEjCSZnpQvXS7/UTElB3c68Qbw="),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Sun, 28 Jul 2019 08:50:02 GMT"),("Connection","close"),("Server","AmazonS3")], _serviceCode = ErrorCode "SignatureDoesNotMatch", _serviceMessage = Just (ErrorMessage "The request signature we calculated does not match the signature you provided. Check your key and signing method."), _serviceRequestId = Just (RequestId "C211E7670B81BA51")})
```

Since S3 metadata is sent to the client as a response header, this confuses client like Google Chrome that expects that this indicates some arcane encoding.

**Comment by mgajda** [comment]
There is workaround of not using `chunkedFile`:
```
  content <- toBody <$> Data.ByteString.Lazy.readaFile "public/index.html"
```
But this will only work for small files.

**Comment by endgame** [comment]
Possibly related (since they affect S3 request signing)? #547 #596

**Comment by endgame** [comment]
This appears to be fixed. I ran the following test code, which successfully uploaded `test_file.txt`:

```haskell
main :: IO ()
main = do
  let r = NorthVirginia
  lgr <- newLogger Trace stdout
  env <- newEnv Discover <&> set (field @"envLogger") lgr . set (field @"envRegion") r
  res <- runResourceT $ do
    body <- chunkedFile defaultChunkSize "test_file.txt"
    let req = newPutObject "bucket" "test_file.txt" body
          & field @"contentType" ?~ "text/plain"
    send env req
  print res
```

I then ran `aws s3api head-object --bucket bucket --key test_file.txt`, which produced:

```json
{
    "AcceptRanges": "bytes",
    "LastModified": "2021-10-13T02:00:06+00:00",
    "ContentLength": 40,
    "ETag": "\"ceba3879d9350ee44b6f9c5058e32cf7\"",
    "ContentType": "text/plain",
    "Metadata": {}
}
```

So it looks like we're no longer defaulting a `Content-Encoding` metadata. If I've misunderstood something, please reopen.

**Comment by endgame** [comment]
Correction: This is still broken, but needs to send multiple chunks. Minimal chunk size is 8192 bytes, so set that and use a larger file.
