### ISSUE TITLE
Requests sent to Application Autoscaling are not properly signed

### ISSUE THREAD

**Issue by axman6** [brendanhay/amazonka#539]
When running the following, I'm getting this exception:

```haskell
runResourceT . runAWS env . send $ describeScalableTargets Dynamodb
```
```haskell
*** Exception: ServiceError'
  { _serviceAbbrev = Abbrev "ApplicationAutoScaling"
  , _serviceStatus =
      Status { statusCode = 400 , statusMessage = "Bad Request" }
  , _serviceHeaders =
      [ ( "x-amzn-RequestId" , "<REMOVED>" )
      , ( "Content-Type" , "application/x-amz-json-1.1" )
      , ( "Content-Length" , "126" )
      , ( "Date" , "Tue, 30 Jul 2019 06:30:55 GMT" )
      , ( "Connection" , "close" )
      ]
  , _serviceCode = ErrorCode "InvalidSignature"
  , _serviceMessage =
      Just
        (ErrorMessage
           "Credential should be scoped to correct service: 'application-autoscaling'. ")
  , _serviceRequestId =
      Just (RequestId "<REMOVED>")
  }
```

I wonder if it's maybe related to this bug in the Go SDK: https://github.com/aws/aws-sdk-go-v2/issues/163

**Comment by axman6** [comment]
Looks like the fix is trivial:
```haskell
runResourceT 
. runAWS 
  (override (\s -> if _svcAbbrev s == "ApplicationAutoScaling" then s{_svcPrefix  =  "application-autoscaling"} else s) env) 
. send $ describeScalableTargets Dynamodb
```
I'll submit a PR momentarily.

**Comment by mgajda** [comment]
Outcome of PR discussion: this bug seems to apply to many more packages where `signingName` is ignored and `endpointPrefix` from `.json` metadata is used instead.

**Comment by axman6** [comment]
@mgajda Any plans to fix that any time soon? Also, a bit off topic, but it seems like there's a few people who're now working actively on Amazonka other than Brendan, are there any plans for a more regular release cycle? They seem to have slowed down quite a lot in the last year or two, which is a shame for such a fantastic project.

**Comment by mgajda** [comment]
@axman6 To make it easier for others to help you, you could provide a small, self-contained test example for this bug. Just like this repo: https://github.com/mgajda/aws-empty-content-encoding-issue.

As for organizing better support, I sent you an email.

**Comment by endgame** [comment]
@axman6 I now have collaborator access to the repo. Since #622 has been merged, can you test and see if this has been fixed?

**Comment by endgame** [comment]
I have successfully made the following request (which is the updated version of what's in the OP):

```
res <- runResourceT . send env $ newDescribeScalableTargets $ ServiceNamespace_Dynamodb
```
