### ISSUE TITLE
Can cognito-idp's ListUsers be made to have an AWSPager instance?

### ISSUE THREAD

**Issue by relrod** [brendanhay/amazonka#542]
Title. :)

Basically, this endpoint supports (requires?) pagination, but doesn't have an `AWSPager` instance it seems. Can it be made to have one somehow? I'm happy to send a PR if someone could point me in the right direction to get started.

**Comment by relrod** [comment]
(I assume that adding the instance manually somewhere isn't the correct solution and the correct solution requires more understanding of how things are generated from the upstream JSON files than I currently have; thus the call for help to get started before I try taking this on.)

**Comment by mgajda** [comment]
It seems that you need to fix `gen/vendor/botocore/botocore/data/cognito-idp/2016-04-18/paginators-1.json`. Can you check if adding the following snipped would fix it for you?
```json
 "ListUsers": {                                                                                                                                                                                                 
      "input_token": "NextToken",    
      "limit_key": "Limit",    
      "output_token": "NextToken",    
      "result_key": "Users"    
    }
```
_WARNING: I did not have time to check that it works. Obviously you need to regenerate your `cognito-idp` library._

**Comment by endgame** [comment]
Looks like AWS have fixed their service definitions, as `develop` has an `AWSPager` instance:

https://github.com/brendanhay/amazonka/blob/ffdbd4b50092fbb591619010d2e5efe8551c215d/amazonka-cognito-idp/gen/Network/AWS/CognitoIdentityProvider/ListUsers.hs#L279-L298
