### ISSUE TITLE
`hashedFileRange` results in `WrongRequestBodyStreamSize`

### ISSUE THREAD

**Issue by lehins** [brendanhay/amazonka#548]
While using `amazonka-s3-streaming` I started getting an error:
```
TransportError - WrongRequestBodyStreamSize 43626199 8388608
```
I could be wrong, but I suspect the error happens in `amazonka` itself cause `HashedStream` keeps the full file size rather than the stream size, causing `http-client` to explode:

```haskell
hashedFileRange :: MonadIO m
                => FilePath -- ^ The file path to read.
                -> Integer  -- ^ The byte offset at which to start reading.
                -> Integer  -- ^ The maximum number of bytes to read.
                -> m HashedBody
hashedFileRange path (Just -> offset) (Just -> len) =
    liftIO $ HashedStream
        <$> runResourceT (Conduit.sourceFileRange path offset len `connect` sinkSHA256)
        <*> getFileSize path -- < the full file size
        <*> pure (Conduit.sourceFileRange path offset len)
```
And here is the request creation:
```haskell
toRequestBody :: RqBody -> RequestBody
toRequestBody = \case
    Chunked x -> requestBodySourceChunked (_chunkedBody x)
    Hashed  x -> case x of
         HashedStream _ n f -> requestBodySource (fromIntegral n) f -- < problem here? n is the size of the whole file
         HashedBytes  _ b   -> RequestBodyBS b
```

**Comment by Kheldar** [comment]
May be related to #546

**Comment by domenkozar** [comment]
I'm using `HashedBytes` and getting the same error, so the problem must be somewhere further.

**Comment by endgame** [comment]
@axman6 Can you take a look at this and tell me whether `amazonka-s3-streaming` is doing anything silly?

**Comment by domenkozar** [comment]
I can confirm I saw these errors and with my fork of rewritten amazonka-s3-streaming they are gone.

**Comment by endgame** [comment]
@domenkozar is this because you're working around the way the body is constructed? The relevant code appears not to have changed in `amazonka` itself.

**Comment by domenkozar** [comment]
It changes the way hash is calculated in https://github.com/axman6/amazonka-s3-streaming/pull/22/files

I haven't spent time looking into where the bug exactly happened, because I rewrite essentially whole logic to also be concurrent, etc.

**Comment by endgame** [comment]
Thanks for the pointer. Looks like your fork is no longer using the function provided by `amazonka`.

**Comment by axman6-da** [comment]
@lehins FYI, @endgame and I spent a few hours yesterday updating `amazonka-s3-streaming` so that it's fully amazonka-2.0 compatible, and as part of that work we fixed this bug, and tested it using the `s3upload` demo app, and everything seems to working fine now. `master` on https://github.com/axman6/amazonka-s3-streaming should be ready ready to go.
