### ISSUE TITLE
Building amazonka-swf on ghc-8.8.1 takes too much memory

### ISSUE THREAD

**Issue by newhoggy** [brendanhay/amazonka#550]
More details here:

https://gitlab.haskell.org/ghc/ghc/issues/17317

**Comment by turboMaCk** [comment]
I'm experiencing similar behavior on ghc 8.8.3 as well.

**Comment by rossabaker** [comment]
I have something in our internal fork that splits up the Types modules, and it makes a huge difference on amazonka-ec2.  I'm fixing some fallout on the updated modules, but intend to have a PR soon.

**Comment by endgame** [comment]
Closing as dupe of #549 , which has more detailed comments of things we might be able to do.
