### ISSUE TITLE
Documentation: Haddock link not working

### ISSUE THREAD

**Issue by andys8** [brendanhay/amazonka#556]
![image](https://user-images.githubusercontent.com/13085980/73531176-30653900-441a-11ea-94a6-c8aee5f3341a.png)

links to http://brendanhay.nz/amazonka-doc

![image](https://user-images.githubusercontent.com/13085980/73531202-39560a80-441a-11ea-9d30-cbe32fdb31a1.png)

**Comment by endgame** [comment]
No longer an issue - current `develop` links directly to hackage.
