### ISSUE TITLE
not support Hong Kong

### ISSUE THREAD

**Issue by limengyu1990** [brendanhay/amazonka#558]
### error info(`core/src/Network/AWS/Types.hs`):
```haskell
user error (AesonException "Error in $.aws.region: Failed reading: Failure parsing Region from ap-east-1")
```

I noticed that `wire` used its own maintained` amazonka` branch and fixed 2 bugs (`important commits`).
I want to know if the `wire` team has time and plans to synchronize the`amazonka` branch of `wire` with the remote newest `amazonka` and then re-package an `archive` package? thanks.

### wire source code Comment
```haskell
# amazonka-1.6.0 is buggy: https://github.com/brendanhay/amazonka/issues/466
# amazonka-HEAD is also buggy: https://github.com/brendanhay/amazonka/issues/490
#
# Therefore we use our own fork of amazonka here. More precisely, we pull two libraries out of
# it: amazonka and amazonka-core. Other packages weren't changed between 1.6.0 and this
# commit, so we can use Stackage-supplied versions for them.
#
# The important commits for us are:
#
#   * https://github.com/brendanhay/amazonka/commit/2688190f
#   * https://github.com/brendanhay/amazonka/pull/493/files
#
# The archive corresponds to commit 52896fd46ef6812708e9e4d7456becc692698f6b.
- archive: https://github.com/wireapp/amazonka/archive/wire-2019-01-25.tar.gz
  subdirs:
  - amazonka
  - core
```

### amazonka
https://hackage.haskell.org/package/amazonka-1.6.1/docs/Control-Monad-Trans-AWS.html#t:Region
https://github.com/brendanhay/amazonka/blob/725340d92f8109bf5ea620a224fe613df9fba8f1/core/src/Network/AWS/Types.hs#Region

**Comment by mheinzel** [comment]
Most of your comment is specific to wire-server and should be discussed on [the wire-server issue](https://github.com/wireapp/wire-server/issues/955).

However, it seems like there is no release for amazonka that includes the update to available regions in [725340d9](https://github.com/brendanhay/amazonka/commit/725340d92f8109bf5ea620a224fe613df9fba8f1). Maybe it would be nice to cut a release at some point?

**Comment by endgame** [comment]
This is now on current `develop`: https://github.com/brendanhay/amazonka/blob/develop/core/src/Network/AWS/Types.hs#L126

Also it looks like we're getting close to seeing a 2.0 release of amazonka. @brendanhay do you prefer to close issues when they're merged to `develop` or when the fix is released to Hackage?

**Comment by endgame** [comment]
I checked awsregion.info and it looks like `develop` has everything listed there except govcloud secret and top secret, and I have no idea whether adding those region codes would be the beginning and end of necessary support (and I suppose the people who do know won't be able to say).

Therefore, I'll close this issue.
