### ISSUE TITLE
Fix needed for MonadUnliftIO changes

### ISSUE THREAD

**Issue by newhoggy** [brendanhay/amazonka#568]
I am currently getting an error when building with latest `amazonka`

```
src/Control/Monad/Trans/AWS.hs:245:5: error:
    ‘askUnliftIO’ is not a (visible) method of class ‘MonadUnliftIO’
    |
245 |     askUnliftIO = AWST' $ (\(UnliftIO f) -> UnliftIO $ f . unAWST)
    |     ^^^^^^^^^^^
```

Looks like there are some breaking changes in `unliftio-core-0.2-x`

**Comment by phadej** [comment]
I made a review https://hackage.haskell.org/package/amazonka-1.6.1/revisions/ (adding `unliftio-core <0.2` bound).

**Comment by newhoggy** [comment]
This PR also fix this problem:  https://github.com/brendanhay/amazonka/pull/572

**Comment by jchia** [comment]
I think the version upper bound for unliftio-core needs to be increased.

**Comment by brendanhay** [comment]
Yeah, thanks. The fix @newhoggy provided is now in `develop`.
