### ISSUE TITLE
Failure parsing ObjectStorageClass from value: 'intelligent_tiering'. Accepted values: glacier, reduced_redundancy, standard, standard_ia"

### ISSUE THREAD

**Issue by k-bx** [brendanhay/amazonka#569]
Got it while trying to list the common crawl news bucket `s3://commoncrawl/crawl-data/CC-NEWS/2020/03/`: `Failure parsing ObjectStorageClass from value: 'intelligent_tiering'. Accepted values: glacier, reduced_redundancy, standard, standard_ia"`

I guess we need to add the intelligent_tiering somewhere.

**Comment by dustin** [comment]
Also, `onezone_ia`

    Failure parsing ObjectStorageClass from value: 'onezone_ia'. Accepted values: glacier, reduced_redundancy, standard, standard_ia"})

**Comment by endgame** [comment]
Closing as dupe of #609
