### ISSUE TITLE
New hackage release

### ISSUE THREAD

**Issue by jchia** [brendanhay/amazonka#574]
It has been a year and many commits since the last release. It would be good for a new release version to be uploaded to Hackage especially now that there is GHC 8.10 and issues like #546 have been fixed.

**Comment by domenkozar** [comment]
cc @brendanhay @MichaelXavier

**Comment by brendanhay** [comment]
@domenkozar Somewhat ironically setting up cachix for amazonka/gogol now in an effort to unfuck CI and move from Travis to GH Actions.

**Comment by domenkozar** [comment]
That's great to hear - happy to help if needed!

**Comment by endgame** [comment]
@brendanhay This is exciting news. Anything an internet rando can help with? I speak pretty fluent nix.

**Comment by gwils** [comment]
Hi @brendanhay - This is great news! How are you going with this?

**Comment by RobertFischer** [comment]
I'm very willing to help -- I write/integrate/manage GitHub Actions professionally, so I'm happy to bang through those things in order to get a new release.  Even just bumping dependencies would be great.

**Comment by gwils** [comment]
@brendanhay Maybe Robert and/or endgame could help you with this? A new hackage release would be great.

**Comment by awgn** [comment]
Since stack TLS 17 is based on ghc-8.10.2 (to date) and given the MonadUnliftIO issue (fixed in 43ddd87b1ebd6af755b166e16336259ec025b337), it's not trivial to use amazonka as the base package does not compile (and it is not yet available under stack).

*A new release would be very appreciated!*

**Comment by mbj** [comment]
me2 issues do not help @brendanhay as much. Instead I'd happily sponsor this library. @brendanhay Is there an option to support your work, financially? I can only send small amounts, but if we'd all do this the situation can improve significantly for you.

**Comment by RobertFischer** [comment]
@brendanhay As I said before, I'm happy to help: just let me know what you need.  Like @mbj, I'd pitch you some money for a new release, too.

**Comment by RobertFischer** [comment]
See #617

**Comment by dciug** [comment]
Can we get an approximate date for a Hackage release? It's been another year.

**Comment by emilypi** [comment]
Just fork it already, he clearly doesn't have the time to maintain this package.

**Comment by mbj** [comment]
@emilypi there has been lots of activity in the `develop` branch. Effectively amazonka-2, improving a lot of the previous state.

**Comment by RobertFischer** [comment]
But if it's not getting released, who cares how much work is done?

**Comment by mbj** [comment]
I've been in the position of the author here before, and I do not think any form of pressurement helps him to find the time.

I use git sources for the time being and am not dependent on a release. I recommend to think about the same, and provide feedback.

**Comment by brendanhay** [comment]
> But if it's not getting released, who cares how much work is done?

Why are you even using open source software?

**Comment by endgame** [comment]
@brendanhay what's needed to get this over the line? There's an agreed-upon goal of a [2.0RC for testing](https://github.com/brendanhay/amazonka/pull/617#issuecomment-830606997), but we haven't got there yet. `amazonka` is an incredibly useful package; please don't let it languish. We want to help you. Please, let us help you.

What are the blockers on the 2.0 release candidate [you outlined on github](https://github.com/brendanhay/amazonka/pull/617#issuecomment-830606997)? If it's your time, can you set out a roadmap and appoint maintainers? If it's the open issue/PR list, can you give someone power to triage issues so we know what needs to get in for 2.0? If it's funding, can you set something up so we can get this sponsored?

**Comment by brendanhay** [comment]
@mbj  If you (or anyone else) is using the latest git sources it'd be great if you could confirm it works as expected (or not) and what services you've tried and optionally a very brief experience report about how integrating any of the new changes (ie. `generic-lens`) went, if you had an existing codebase you needed to update.

@endgame FWIW the last outstanding open PR has been merged today - while I'd like to get some of the other issues mentioned in the [issue](https://github.com/brendanhay/amazonka/pull/617) completed, there's too many changes already to sanely test without introducing more breakage.

> What are the blockers on the 2.0 release candidate you outlined on github? 

The only blocker is writing the CHANGELOG as a continuation of #580. A number of S3 related-errors are still outstanding that would be "nice" to resolve: #610 #628 #630. If anyone can jump on those, that'd be helpful.

The documentation sucks - but, Haskell lyfe. I don't think it should block things at this point.

> If it's your time, can you set out a roadmap and appoint maintainers? 

I'm happy to add you as a collaborator if you want to continue handling things, you've done a great job with the issue triage and your work is appreciated despite the lack (or, prevention) of communication on my end.

> can you set something up so we can get this sponsored?

A sponsor button is already on the repository (bottom of this page, for instance.) I appreciate it if companies donate but if you're an individual wanting to make a gesture then perhaps gift a game that you enjoyed via [Steam](https://steamcommunity.com/id/brendanhay), as this avoids it all disappearing to tax and consequently Finanzamt employees enjoying more Weißwuascht und Milchkaffee.

**Comment by endgame** [comment]
@brendanhay I'm happy to take on collaborator access; let's get this done.

**Comment by endgame** [comment]
Right. I stuck a "needs triage" label on every issue and PR in the repo, then went through and dealt with a lot of the low-hanging fruit.

If you use [this search](https://github.com/brendanhay/amazonka/issues?q=is%3Aopen+is%3Aissue+label%3A%22needs+triage%22), you'll see which issues I haven't had a chance to think hard about yet. If you see something you understand, please comment with your thoughts, and a recommendation for including it in the 2.0 RC or sticking it with the "post 2.0" label.

I want to write a "master issue" describing the goals for the 2.0 release and collecting the folklore in this issue and the comments of #617 and go over the `develop` history to bring changelog up to date (closing #580 ). From there it's going to be about working through the [milestone issues](https://github.com/brendanhay/amazonka/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.0+RC+1%22), testing that they're actually still broken and seeing if the fix is easy enough to ship now.

**Comment by ketzacoatl** [comment]
> I want to write a "master issue" describing the goals for the 2.0 release and collecting the folklore in this issue and the comments of #617 and go over the develop history to bring changelog up to date (closing #580 ). From there it's going to be about working through the milestone issues, testing that they're actually still broken and seeing if the fix is easy enough to ship now.

Outstanding! Thank you @brendanhay, thank you @endgame, thank you to all others who have helped get us this far!

I use amazonka but am not always capable or experienced enough to understand the inner workings.. I tried using the latest git sources, but had a hard time figuring out what I needed to update in my code to get it working. Is there an existing migration doc, or notes on the topic, or a TODO in release's milestone? I'd be happy to help compile that doc from notes, or comments in issues, or whatever guidance there is, I just lack the haskell-chops to figure it all out on my own.

**Comment by endgame** [comment]
See #650 for an up-to-date changelog, highlighting how the structure of the API has changed.

I'm going to close this issue, as #643 has the plan for how things will get out the door. It's actively moving, but will be done when it's done. If you'd like that day to come sooner, please look at either issues/PRs with the "needs triage" label or issues with the "2.0 RC1" milestone.
