### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by rossabaker** [brendanhay/amazonka#581]
Starting to think about how to get the CI into better shape.

## Library code

It would be nice to test the library projects on multiple versions of GHC.  GitHub Actions currently comes with 8.6.5, 8.8.3, and 8.10.1, which seem like a reasonable target in May 2020.

I've been experimenting with GitHub Actions.  Building all the packages in a single job for one GHC took 2 hours and 15 minutes.  There are 84 new AWS services available in the next model refresh, and AWS is always adding, so that will keep getting heavier.  GitHub Actions have a limit of six hours, and it would be nice to be much faster.

The existing Travis CI job runs a job per service.  On #577, that's 142 jobs, before testing any alternate GHC versions.  Multiplying that by 3 GHCs would be absurd, and GitHub Actions imposes a limit of 256 jobs in the matrix.  We currently handpick a few "priority" libraries to build on all GHC, and then all the libraries on one GHC.  Even then, we could find ourselves bumping up against the limit.   The extra parallelism could make things faster, but we also end up recompiling core a lot in this approach.

A compromise that groups multiple services into tens (not hundreds) of jobs is plausible, but totally arbitrary.

Caching is desired in either scenario.  A GitHub Actions cache is not incremental. Most builds hash the cache key on the contents of the cabal file(s).  If that caching doesn't work well, we could consider haskell.nix + cachix, which is working well for us at Earnest Research, but is a bit more radical.

## Generated code

We can run scheduled jobs in GitHub Actions.  These could refresh the model, run the generator, compile, and commit back on success.  Boto updates every weekday, and we could conceivably do the same.  This level of automation would require git write access from Actions.

The work done here would be roughly a superset of the work we do on pull requests, so it would also benefit from caching.

**Comment by peterbecich** [comment]
Regarding 8.8.3 please see https://github.com/brendanhay/amazonka/pull/593

**Comment by endgame** [comment]
Now that there's a GH-actions-based CI using haskell.nix, and a corresponding cachix, should this be closed?

**Comment by brendanhay** [comment]
Thanks @rossabaker - we've followed through on this with 8.8.4 and 8.10.4 support on GitHub Actions. The `develop` branch now uses Haskell.nix/Cachix and build times seem somewhat tenable if out-of-band cache priming  is done for any significant changes such as bumping the Haskell.nix version.

No scheduled jobs for code (re)generation have yet been attempted.
