### ISSUE TITLE
SQS.sendMessage allows empty MessageBody

### ISSUE THREAD

**Issue by lrworth** [brendanhay/amazonka#587]
```
AWS.runResourceT $ AWS.runAWS awsEnv $ AWS.send $ SQS.sendMessage myQueueUrl ""
```
compiles, but causes SQS to respond:
```
The request must contain the parameter MessageBody.
```
(which is misleading, because amazonka does send `Action=SendMessage&MessageBody=&QueueUrl=https....`).

It would be nice if amazonka discouraged this kind of thing somehow, perhaps through a non-empty string type.

**Comment by endgame** [comment]
I suppose this depends on whether or not the service definitions specify that the parameter must not be empty, and whether the generator can emit Haskell that exposes that fact. But this isn't important enough for 2.0 RC.

**Comment by endgame** [comment]
Unlike `Data.List.NonEmpty.NonEmpty`, there's not really any canonical non-empty text type in or near `base`. Supporting one would require finding and committing to such a type, and then adding overrides each time something like this gets noticed. I think that this isn't worth the amount of maintenance overhead it would induce given amazonka's role - being autogenerated bindings to all the services.

I could totally see such type-level guarantees being a good part of some higher-level library that does its work through `amazonka-sqs`, however.

Closing, but @brendanhay should reopen if he disagrees.
