### ISSUE TITLE
"Basic Example" in docs fails when using `chunkedFile`; works when using `hashedFile`

### ISSUE THREAD

**Issue by mmport80** [brendanhay/amazonka#596]
I received an error (below) when running the basic [example](https://hackage.haskell.org/package/amazonka-1.6.1/docs/Network-AWS.html#g:16). Using `hashedFile` instead works fine.

```
ServiceError] {
  service    = S3
  status     = 403 Forbidden
  code       = SignatureDoesNotMatch
  message    = Just The request signature we calculated does not match the signature you provided. Check your key and signing method.
  request-id = Just DD9AFEDDAB839A1C
}
```

**Comment by samueldple** [comment]
Could this be related to #594?

**Comment by endgame** [comment]
#547 may have fixed this; need to check.

**Comment by ketzacoatl** [comment]
@endgame can we add a `needs-testing` or similar tag to the issues like this that need testing before closing?
