### ISSUE TITLE
amazonka should use AWS_DEFAULT_REGION and not AWS_REGION

### ISSUE THREAD

**Issue by Fuuzetsu** [brendanhay/amazonka#603]
AWS_REGION used to potentially be a thing before but now the AWS CLI and SDKs use AWS_DEFAULT_REGION.

https://github.com/aws/aws-cli/issues/735

**Comment by Fuuzetsu** [comment]
Having said that, I _also_ see AWS_REGION defined on EKS for service account IAM role via OIDC. Still, all SDKs and documentations seem to use AWS_DEFAULT_REGION so this might break at some point.

**Comment by endgame** [comment]
Perhaps the thing to do is look at `AWS_DEFAULT_REGION` first, then `AWS_REGION` if that doesn't exist? I'll add this to the 2.0RC milestone but won't lose sleep if it doesn't get in.

**Comment by ketzacoatl** [comment]
> Perhaps the thing to do is look at AWS_DEFAULT_REGION first, then AWS_REGION if that doesn't exist?

That would be nice for backwards compatibility.

This looks like the primary place this is defined: https://github.com/brendanhay/amazonka/blob/0433ee599feabd747a164bbc4445a08ff5364603/amazonka/src/Network/AWS/Auth.hs#L115-L119

Do we want that to be a sumtype, or should this be done differently? I'd be happy to help with this, but would need a little guidance.

There are also other mentions of this envvar, but I don't understand what they are for. Here is an example: https://github.com/brendanhay/amazonka/blob/0433ee599feabd747a164bbc4445a08ff5364603/amazonka-config/gen/Network/AWS/Config/Types/ConfigRuleComplianceSummaryGroupKey.hs#L60-L64

**Comment by ketzacoatl** [comment]
My 2c: Is it easy to support both, or a PITA? If it's easy, might as well. If it's not easy, might as well punt.
