### ISSUE TITLE
Ensure all current S3 storage classes are supported

### ISSUE THREAD

**Issue by dustin** [brendanhay/amazonka#609]
I have some data stored in "deep archive" which seems to break some things.

    _serializeMessage = "Failed reading: Failure parsing StorageClass from value: 'deep_archive'. Accepted values: onezone_ia, reduced_redundancy, standard, standard_ia"}

**Comment by dustin** [comment]
I also had one in "glacier"

**Comment by endgame** [comment]
I've seen other issues about other storage classes like `onezone_ia` and `intelligent_tiering`. Let's do a pass over the S3 storage class code and make sure all current storage classes are present.

**Comment by endgame** [comment]
The other issue was #569 which gives us `s3://commoncrawl/crawl-data/CC-NEWS/2020/03/` as a thing to list for test cases.

**Comment by endgame** [comment]
According to https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html , current storage classes are: `STANDARD | REDUCED_REDUNDANCY | STANDARD_IA | ONEZONE_IA | INTELLIGENT_TIERING | GLACIER | DEEP_ARCHIVE | OUTPOSTS`. All are present in https://github.com/brendanhay/amazonka/blob/736e261cdb2c9d61b8015d950d2481ddd8876422/amazonka-s3/gen/Network/AWS/S3/Types/StorageClass.hs#L23-L30 .
