### ISSUE TITLE
mws (amazon marketplace) support

### ISSUE THREAD

**Issue by ibotty** [brendanhay/amazonka#61]
Hi,

It would be great, to have auto-generated mws bindings via amazonka.

Afaict mws also has an amazon service model (`com.amazonservices.mws`). I did not look into how the other amazonka bindings get generated, so I am not sure it's all that is needed, though. I am willing to invest time and code in it, but only have very limited time. Pointers welcome.

**Comment by brendanhay** [comment]
I'll happily add it if the service description exists - but it seems to be missing from all of the official bindings Amazon supplies for Java, JavaScript, Python, Ruby, and .NET.

Until they publish the `.json` service description I cannot generate the bindings, I will contact them and see what the status/roadmap is if any, in regards to MWS.

**Comment by ibotty** [comment]
aha, that's why i could not find it. thank you for responding and even asking them.

**Comment by RayRacine** [comment]
Literally started following this project last night with the intent of asking this very question.  Hopefully Amazon can provide the description files.  If unavailable, I'd be willing to assist in in manually crowd sourcing a set.

**Comment by brendanhay** [comment]
I've reached out. Once I have a response I'll let you know.

**Comment by brendanhay** [comment]
So the preliminary response from Amazon is [it's probably going to be the same as the Product Advertising API](https://github.com/aws/aws-sdk-js/issues/326), from the `aws-sdk-js` repository:

> Unfortunately, we cannot accept this feature request. The Amazon Product Advertising API is not an AWS service; it's separately owned and offered by the Amazon Associates Program. The goal of AWS SDKs is to help customers use AWS services, and we will continue to maintain our focus on improving the customer experience for the officially supported AWS services.

We could potentially look at parsing or creating a model for MWS but at a cursory glance it appears to differ too much from the actual AWS services behaviour to justify going into the same code base.

I'll continue to have a think/investigate what some options might be, but no promises that something can be done. I'll leave this issue open until a decision is reached.

**Comment by bluepuma77** [comment]
+1
