### ISSUE TITLE
amazonka-sts logs secret access key at `Debug` level

### ISSUE THREAD

**Issue by akrmn** [brendanhay/amazonka#635]
We recently had an incident where we noticed that the `[Raw Response Body]` of an STS [`Network.AWS.STS.AssumeRole .AssumeRoleRequest`](https://github.com/brendanhay/amazonka/blob/develop/amazonka-sts/gen/Network/AWS/STS/AssumeRole.hs#L846) gets logged at the `Debug` level, potentially compromising these credentials. 

I'm not sure if there's a way to modify the [`Network.AWS.Response.deserialise`](https://github.com/brendanhay/amazonka/blob/develop/amazonka/src/Network/AWS/Response.hs#L122) function to selectively log some responses to the [`Trace`](https://hackage.haskell.org/package/amazonka-core-1.6.1/docs/Network-AWS-Types.html#t:LogLevel) level ("Includes potentially sensitive signing metadata, and non-streaming response bodies") instead of `Debug` ("Useful debug information + info + error levels").

**Comment by brendanhay** [comment]
Thanks for reporting the issue - I'd  say the only correct fix for this is to change `deserialise` to only log at the `Debug` level.

None of the logging functions have access to any semantic knowledge about the response payloads so we'll have to assume there could be something sensitive in contained therein, which violates the `Debug` vs `Trace` documentation.

**Comment by akrmn** [comment]
Thanks for your response @brendanhay! 

Right, I figured some semantics might be lost by the point `deserialise` gets called.

One thing, `deserialise` currently logs at the `Debug` level, I believe the fix would be for it to log at `Trace`.

**Comment by brendanhay** [comment]
> One thing, deserialise currently logs at the Debug level, I believe the fix would be for it to log at Trace.

Oops, I intended to say `Trace`, so yes - the fix would be to change it to only emit on `Trace` as you say.
