### ISSUE TITLE
`Seconds` type is too coarse

### ISSUE THREAD

**Issue by endgame** [brendanhay/amazonka#638]
Some services (example: DynamoDB) generally respond really quickly (<10ms is normal, IME), and occasionally take much longer. A DynamoDB specialist advised us to give up on slow requests and retry them instead of waiting, but the `Seconds` type can only hold an integral number of seconds.

Replace it with either more granular integral type, or a type that can handle decimals?

**Comment by brendanhay** [comment]
Probably should switch to using [DiffTime](https://hackage.haskell.org/package/time-1.12/docs/Data-Time-Clock.html#t:DiffTime) (or [Pico](https://hackage.haskell.org/package/base-4.14.1.0/docs/Data-Fixed.html) directly.)

**Comment by endgame** [comment]
`DiffTime` sounds good, as it's a type about time, but will need to see what `http-client` is prepared to accept. But will think about that later.
