### ISSUE TITLE
Amazonka 2.0 RC

### ISSUE THREAD

**Issue by endgame** [brendanhay/amazonka#643]
We are actively working towards a 2.0 RC. The goals for this release are:

* Make the consolidated work currently available to people to test and upgrade their code, by providing `source-repository-package` and/or `extra-deps` stanzas.
* Fix open critical and/or easily-fixed issues
* Maybe upload package candidates to Hackage?

Once we have an RC, we'll probably want to announce it (Haskell Discourse, mailing lists, reddit) and have a stabilisation period of 4-6 weeks for people to raise bugs, after which we upload the new versions of everything to Hackage for real.

Useful links:

* List of [issues/PRs for the RC milestone](https://github.com/brendanhay/amazonka/milestone/2)
* List of [untriaged issues/PRs](https://github.com/brendanhay/amazonka/labels/needs%20triage)

**Comment by brendanhay** [comment]
Sounds good, thanks!

**Comment by endgame** [comment]
Triage is now complete. I've read every issue and PR in this repo and either assigned them to the 2.0 RC milestone or "later". Once that's done, we should be good to announce the release for people to hammer on.

I think that once we cut RC, we should just tell people to use `source-repository-package` or `extra-deps`. i expect that we'll have a fair amount of churn as people hit things that are broken, and I don't want to push a large number of bad versions onto Hackage.

**Comment by endgame** [comment]
Draft release announcement, @brendanhay LMK your thoughts:

*****

We are proud to announce the first release candidate of Amazonka 2.0, the comprehensive AWS SDK for Haskell. This release collects the past few years' worth of bug fixes and AWS service releases, and also includes some fairly major changes to repository organisation and conventions. You can read a high-level overview of the changes in the [Amazonka CHANGELOG.md](https://github.com/brendanhay/amazonka/blob/main/lib/amazonka/CHANGELOG.md).

Because of the size of the release, we are now entering a stabilisation period. During this period, we'd greatly appreciate people testing `amazonka` against their projects, and reporting issues against the [2.0 milestone](https://github.com/brendanhay/amazonka/milestone/3). We are aiming for a four-week stabilisation period, but may shorten or lengthen this depending on the volume of issues raised.

To test the release, you will need to add a [`source-repository-package`](https://cabal.readthedocs.io/en/3.4/cabal-project.html#specifying-packages-from-remote-version-control-locations) section to your `cabal.project` file for `amazonka` itself, as well as for any service libraries you use:

```
-- For amazonka
source-repository-package
    type: git
    location: https://github.com/brendanhay/amazonka
    tag: <current revision of the `main` branch>
    subdir: lib/amazonka

-- For each service library
source-repository-package
    type: git
    location: https://github.com/brendanhay/amazonka
    tag: <current revision of the `main` branch>
    subdir: lib/services/amazonka-<servicename>
```

Stack users should use an [`extra-deps:`](https://docs.haskellstack.org/en/stable/pantry/) stanza like this:
```yaml
extra-deps:
- github: brendanhay/amazonka
  commit: <current revision of the `main` branch>
  subdirs:
  - lib/amazonka
  - lib/services/amazonka-<servicename>
```

**Comment by brendanhay** [comment]
LGTM!

The multiple `source-repository-package` stanzas is an annoyance, if someone is using Cabal `>3` ([I think?](https://github.com/EggBaconAndSpam/cabal/commit/17f4e42d18d097f7cd8bdf2ba188929343ffe4c0)) they can use a single stanza with `subdir: lib/amazonka lib/amazonka-<service> ...`

**Comment by istathar** [comment]
fwiw I would like to encourage you to release 2.0.0 to Hackage at well, anytime, starting now. Right now we're all building off of the code you have generously made available on GitHub which is great. Not having the Haddock documentation online is proving challenging, however. 2.0.0.0 is a major bump and I woudn't think anyone would expect it to stabilize until at least 2.0.5.77 :) ... but perhaps we could help by trying to use it from Hackage and seeing what works and what doesn't from more projects.

Thank you so much for your amazing and sustained efforts on **amazonka**.

**Comment by endgame** [comment]
@brendanhay I know you're hacking on some stuff for amazonka-core. Is that to go into the RC? If not, I think we have everything we need - should we tag it and get it out there, and work on the other stuff in parallel?

**Comment by myShoggoth** [comment]
Please let me know when you do your announcements so I can amplify!

**Comment by ysangkok** [comment]
I see there is [a `2.0.0-rc1` tag](https://github.com/brendanhay/amazonka/tree/2.0.0-rc1). Is this a release candidate? I am puzzled it wasn't announced here.

**Comment by brendanhay** [comment]
The tag went up today, I'm in the process of trying to get the documentation updated so we can announce.

**Comment by endgame** [comment]
This is awesome news, thanks so much for your hard work. BTW: the release date in the changelog is not correct; you may want to re-push the tag.

**Comment by brendanhay** [comment]
@endgame Thanks - the tag has been recreated with an updated date/link.

**Comment by endgame** [comment]
@myShoggoth Direct link to the release announcement: https://github.com/brendanhay/amazonka/discussions/716
