### ISSUE TITLE
Post-release: Deprecate amazonka-core on hackage?

### ISSUE THREAD

**Issue by endgame** [brendanhay/amazonka#656]
It doesn't seem to exist any more.

**Comment by brendanhay** [comment]
Deprecation is probably the way to go but I'll document an alternative here for posterity.

> We could introduce an empty `amazonka-core` package that potentially re-exports analogues from `amazonka` where possible. This probably won't be a drop in replacement and pushes errors further from package/repo-subdir doesn't exist to module doesn't exist.

Also, prior to 2.0 the application dependency graph was:

```
application      <- (amazonka, amazonka-ec2, amazonka-s3, amazonka-core)
amazonka         <- (amazonka-core)
amazonka-service <- (amazonka-core)
```

When writing an application you typically also ended up depending on `amazonka-core` directly to get access to serialisation classes/primitives.

Now, with `amazonka` + `amazonka-core` merged:

```
application      <- (amazonka, amazonka-ec2, amazonka-s3)
amazonka-service <- (amazonka)
```

**Comment by endgame** [comment]
If nothing depends on `amazonka-core` except a downstream project using `amazonka`, I think cabal will happily solve for `amazonka-2.0` and `amazonka-core-1.6.1`. From there, I'd expect compilation failures of the form "multiple packages provide this module, which one do you want?", and it should be pretty obvious that dropping `amazonka-core` is the right move.

**Comment by brendanhay** [comment]
Closing this due to the `amazonka-sts` related changes, now that the `amazonka-core` separation actually has a use/place.
