### ISSUE TITLE
Read instances on most datatypes

### ISSUE THREAD

**Issue by ryantrinkle** [brendanhay/amazonka#67]
It would be great to have Read instances on a lot of these datatypes, especially enumerations such as `Network.AWS.S3.Types.ObjectStorageClass`.

**Comment by brendanhay** [comment]
For parsing the enumerations I'd suggest using the `FromText` instances from `Network.AWS.Data` in `amazonka-core`. These should be considerably more efficient and are the same underlying de/serialisation routines that the underlying library uses, for example:

```haskell
Network.AWS.Data.fromText "GLACIER" :: Either String ObjectStorageClass
```

I will also add the `Read` instances for convenience, where possible.

**Comment by brendanhay** [comment]
I should also point out that the `FromText` instances for most enumerations are case insensitive, this may not be what you expect/want.

**Comment by ryantrinkle** [comment]
Absolutely.  However, it's really convenient to have a Read instance corresponding to the Show instance for GHCi-based debugging.  Being partial/slow/etc. isn't really a concern in that situation.
