### ISSUE TITLE
Documentation exceeds GitHub pages maximum (100MiB) size

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#679]
When building Haddock documentation the combined index + assets size totals around 111MiB, resulting in remote pushes to `gh-pages` branch being refused. As a workaround I'll prune everything except `amazonka*` libraries from the index - but this will result in broken hyperlinks everywhere.

**Comment by endgame** [comment]
The other option might be pushing haddocks to a separate git repo, like git_lab_ pages.

Oh, but I see you've closed this.
