### ISSUE TITLE
Regenerate docs

### ISSUE THREAD

**Issue by endgame** [brendanhay/amazonka#697]
After #692 and #696 are done, we'll need up-to-date docs for the site. I've updated the draft release announcement in #643 to point to amazonka.brendanhay.nz.

**Comment by endgame** [comment]
@brendanhay Are we good to release? If so, this is a step that only you can do.

**Comment by brendanhay** [comment]
Am aware. Outage at work and dealing with fallout, will try to get to this early this week.

**Comment by endgame** [comment]
All right. I'll get off your back then. Godspeed.

**Comment by brendanhay** [comment]
The 2.0.0-rc1 docs have been built  + pushed to https://amazonka.brendanhay.nz manually.
