### ISSUE TITLE
Turn on branch protection for main

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#709]
I literally just face palmed by pushing some changes (`amazonka-core`) that were supposed to be on a branch, directly to `main`.

**Comment by endgame** [comment]
Seems legit, but I think you're the only one with that power.

**Comment by endgame** [comment]
This should be easy, let's do it.

**Comment by endgame** [comment]
@brendanhay did you get a chance to do this?

**Comment by endgame** [comment]
@brendanhay did you get a chance to do this?

**Comment by endgame** [comment]
@brendanhay This is done, right? Also, if you're not about, I get stalled because I can no longer merge my own PRs: #759 for example.

**Comment by endgame** [comment]
Appears to be done. Reopen if not.
