### ISSUE TITLE
Investigate generating Hashable/NFData instances

### ISSUE THREAD

**Issue by endgame** [brendanhay/amazonka#719]
@phadej says:

> You may further speed up compilation of amazonka service libs by generating `Hashable` and `NFData` instances (and not relying on Generic-based defaults). Especially if there are bigger product types (= a lot of fields) the speedup can be actually noticeable. Given the code is generated anyway, I don't think that would be a big change.

**Comment by jhrcek** [comment]
Can this be considered resolved if the service libs haven't actually been regenerated?
I'd be very interested what impact this change has on compilation speed :)

**Comment by endgame** [comment]
Generally we do regeneration in a separate PR to make the actual changes visible. If you want to try this out before that happens, you can use `nix-shell` and `scripts/generate` to regenerate the service libs you're interested in.

**Comment by brendanhay** [comment]
See #722
