### ISSUE TITLE
amazonka-evidently: generate

### ISSUE THREAD

**Issue by alexbiehl** [brendanhay/amazonka#727]
It would be great to support this recent addition to AWS.

Thanks, amazonka is a great set of libraries!

**Comment by endgame** [comment]
Do you have a use case in mind? It is easier to generate and test a service definition if there's someone using it who can point out what breaks. If you want to have a play, there are instructions in the readme on how to update the botocore pin and pull in new service definitions.

**Comment by alexbiehl** [comment]
🤔we’ve just introduced a nice abstraction for feature flags in our system, it might make a good case for experimentation. Let me see what I can do and hopefully come up with a list of APIs that are required.

**Comment by endgame** [comment]
Don't worry about enumerating endpoints, it won't be worth your time as the generators emit every API endpoint in the botocore service definition file. Is there a list of new services anywhere?

I see a service definition for Evidently in botocore already, so hopefully this is one we can turn the handle on - I know there are some that don't work with the current generator.

**Comment by endgame** [comment]
Rough plan: get the `Hashable`/`NFData` fixes in #726 approved and merged, then we regenerate everything currently configured and get that wave of spam out of the way (probably with a force push over #722), then we look at picking up any new services that are easy to configure.

@brendanhay if you're able to look over #726 I can pick up some of this work.
