### ISSUE TITLE
Performance of request signing

### ISSUE THREAD

**Issue by ethercrow** [brendanhay/amazonka#742]
While profiling a service I've seen Amazonka request signing featured prominently.

From a quick look at https://github.com/brendanhay/amazonka/blob/main/lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs my first suspect would be bytestring operations like `<>` and `BS8.intercalate` which contain `malloc` inside and having too many of those is usually not great.

It would be great to have a benchmark for request signing, I'd imagine it would be useful for every user of Amazonka if the signing was efficient.

**Comment by endgame** [comment]
It would indeed be great, but a release is a higher priority. That said, I'd certainly look at a PR if you had time to write one (even if only adding a benchmark).

**Comment by endgame** [comment]
Thoughts, after discussion with @axman6 :

* Replace uses of chained `(<>)` with `ByteString.concat`,
* `canonicalHeaders` might be better if it used a `Builder`,
* `BS8.intercalate s = concat . intersperse s`, and `concat` is smart (it computes the destination length and allocates a single buffer)

Do you have a benchmark case? It would be good to know if changes actually improve things.

**Comment by endgame** [comment]
And fix the FIXME about using an ordered map.
