### ISSUE TITLE
Streaming file from S3 through Servant (using Amazonka)

### ISSUE THREAD

**Issue by aveltras** [brendanhay/amazonka#750]
Hi,

I'm currently trying to achieve file streaming from AWS S3 (using Amazonka) through a Servant endpoint.

I have setup a minimal reproducible example at https://github.com/aveltras/amazonka-servant-streaming.

I can make it work if I first download the file from s3 in the handler and then send it to the client but I would like to stream it with no intermediary file as it is suboptimal.

It doesn't work currently as I'm encountering "Connection closed" errors during the handler processing.

I'm not sure in the problem lies in Servant, Amazonka or the way I use them.

Would appreciate if anyone could shed some light on this.

I have also opened an [issue ](https://github.com/haskell-servant/servant/issues/1515)on Servant repo

Thanks

**Comment by endgame** [comment]
I'm pretty sure the problem isn't in amazonka. What I think is going on is that the amazonka connections are getting closed when you exit this `runResourceT` block:

https://github.com/aveltras/amazonka-servant-streaming/blob/411c5c69bc6b1eaf85dc551d45ce7e5ac1a48180/src/Main.hs#L47-L50

If you look at the [`servant-streaming-amazonka`](https://github.com/domenkozar/servant-streaming-amazonka/blob/master/src/Servant/Streaming/Example.hs) example, you can see that it's calling `createInternalState`/`runInternalState`/`closeInternalState` to run the `ResourceT`.

Try this PR: https://github.com/aveltras/amazonka-servant-streaming/pull/1

FYI @domenkozar , who I've seen working in this space, and may be interested in an amazonka-2.0 take on what he was doing.

My only reservation is that if the conduit itself throws an exception during the streaming to the client, I don't see how we get to do our cleanup.

Feel free to ping me and/or reopen if this doesn't solve your issue. Thanks for the interesting question.

**Comment by aveltras** [comment]
Thanks for the quick answer. Your PR works like a charm !

**Comment by jhrcek** [comment]
FYI I was dealing with similar issue and found this, what seems like more exception safe solution:

https://github.com/jhrcek/servant-amazonka-s3-stream/pull/2/files

The main idea is to lift amazonka's `send` call into ConduitT monad transformer and creating "composite conduit" which both sends the requests and streams the response before it is finalized by `runResourceT` within servant's ToSourceIO instance of ConduitT: https://hackage.haskell.org/package/servant-conduit-0.16/docs/src/Servant.Conduit.html#line-42
