### ISSUE TITLE
amazonka-iot: Regenerate

### ISSUE THREAD

**Issue by debug-ito** [brendanhay/amazonka#751]
amazonka-iot-1.6.1 doesn't have [RegisterCertificateWithoutCA method](https://docs.aws.amazon.com/iot/latest/apireference/API_RegisterCertificateWithoutCA.html). Is there any plan to add this?

**Comment by endgame** [comment]
I was about to say "we need to regenerate the service bindings", but it already exists in latest `main`:

https://github.com/brendanhay/amazonka/blob/d3a4e0933fbaa46fa99533bcfb328676ea87bba9/lib/services/amazonka-iot/gen/Amazonka/IoT/RegisterCertificateWithoutCA.hs#L71

The amazonka currently on Hackage is at least 3 years out-of-date. We've put out a 2.0 RC for people to test with; instructions for adding it to your cabal or stack project are in [the release announcement](https://github.com/brendanhay/amazonka/discussions/716). My work (among other places) are using it in production, and at this point I would consider it a much better choice than what's on Hackage.

The examples have been updated, so you should look at them if you need further guidance. If you are having specific trouble with amazonka-2.0, please open a new issue.

**Comment by debug-ito** [comment]
Thanks a lot! I'll try the 2.0 RC.
