### ISSUE TITLE
Remove underscores from amazonka/amazonka-core record fields

### ISSUE THREAD

**Issue by endgame** [brendanhay/amazonka#752]
In general we are moving to supporting generic-lens/generic-optics and allowing the users to choose the optic lib that they prefer. So make the hand-written records in the two main amazonka libraries have unprefixed field names.

Should go in before 2.0 just because it's another minor breaking change.

**Comment by bsaul** [comment]
I see underscores in record field names in:

* `IdentityDocument` in `Amazonka.EC2.Metadata` 
*  several records in `Amazonka.Types`
* `Waiter` in `Amazonka.Waiter`

Are these the ones to address?

**Comment by endgame** [comment]
Yes, that's right. There shouldn't be any in the generated service bindings, so you'll only be looking for ones in `lib/amazonka` and `lib/amazonka-core`. You should hopefully also be able to drop any prefixes from them, like the `_serializeError` prefixes in https://github.com/brendanhay/amazonka/blob/4be74644af107d67bc19230826b64595095384b8/lib/amazonka-core/src/Amazonka/Types.hs#L241-L246

I hope this means that the manual lenses like `serializeAbbrev` can also go away too, but this may get a bit gnarly. Not sure about the `AsError` typeclass either.

**Comment by bsaul** [comment]
Opened up #778 to start work towards this.
