### ISSUE TITLE
Pinpoint toJSON methods are being generated incorrectly

### ISSUE THREAD

**Issue by newmana** [brendanhay/amazonka#765]
Hi, we've had our own internal fork of the old Amazonka. It had a bug where the toJSON for various calls were incorrect - it's adding an extra key when it should be flat). It looks like 2.0 has the same issue.

For example:
* https://github.com/brendanhay/amazonka/blob/29e4888f847797533c968a855804990ecf8660dd/lib/services/amazonka-pinpoint/gen/Amazonka/Pinpoint/UpdateEndpoint.hs#L147
* https://github.com/brendanhay/amazonka/blob/29e4888f847797533c968a855804990ecf8660dd/lib/services/amazonka-pinpoint/gen/Amazonka/Pinpoint/UpdateSegment.hs#L145
* https://github.com/brendanhay/amazonka/blob/29e4888f847797533c968a855804990ecf8660dd/lib/services/amazonka-pinpoint/gen/Amazonka/Pinpoint/SendMessages.hs#L124

```instance Core.ToJSON UpdateEndpoint where
  toJSON UpdateEndpoint' {..} =
    Core.object
      ( Prelude.catMaybes
          [ Prelude.Just
              ("EndpointRequest" Core..= endpointRequest)
          ]
      )
```

The "EndpointRequest" should be removed (something like):

```
instance Core.ToJSON UpdateEndpoint where
  toJSON UpdateEndpoint' {..} = Core.toJSON endpointRequest
```

The error you get back from AWS (the pertinent bit is "Unrecognized field "EndpointRequest"):
```
Left (ServiceError (ServiceError' {_serviceErrorAbbrev = Abbrev {fromAbbrev = "Pinpoint"}, _serviceErrorStatus = Status {statusCode = 400, statusMessage = "Bad Request"}, _serviceErrorHeaders = [("Content-Type","application/json"),("Content-Length","260"),("Connection","keep-alive"),("Date","Tue, 05 Apr 2022 04:36:40 GMT"),("x-amzn-RequestId","21d60202-29e8-4df2-8f0f-2ed5f7504e95"),("Access-Control-Allow-Origin","*"),("x-amzn-ErrorType","BadRequestException"),("x-amz-apigw-id","QFwV0G-3SwMFXNg="),("Cache-Control","no-store"),("X-Amzn-Trace-Id","Root=1-624bc758-05e2608a66a7952a043beb65"),("X-Cache","Error from cloudfront"),("Via","1.1 4cc1cef5b7e8e0c2a1020c88ce286fbc.cloudfront.net (CloudFront)"),("X-Amz-Cf-Pop","SYD4-C1"),("X-Amz-Cf-Id","OjLJ0IXAhU_DZywSM7-7V1FaAlzVWCzNrfNSDGJdHnDN3ELG7TTwkQ==")], _serviceErrorCode = ErrorCode "BadRequest", _serviceErrorMessage = Just (ErrorMessage {fromErrorMessage = "Unrecognized field \"EndpointRequest\" (11 known properties: \"Metrics\", \"Address\", \"Location\", \"EndpointStatus\", \"RequestId\", \"OptOut\", \"ChannelType\", \"Demographic\", \"Attributes\", \"User\", \"EffectiveDate\"])\nLine 1, column 21"}), _serviceErrorRequestId = Just (RequestId {fromRequestId = "21d60202-29e8-4df2-8f0f-2ed5f7504e95"})}))
```

You can see how they're supposed to be structured:

* [Endpoint Schemas](https://docs.aws.amazon.com/pinpoint/latest/apireference/apps-application-id-endpoints-endpoint-id.html#apps-application-id-endpoints-endpoint-id-schemas)
* [Segment Schemas](https://docs.aws.amazon.com/pinpoint/latest/apireference/apps-application-id-segments-segment-id.html#apps-application-id-segments-segment-id-schemas)
* [Messages Schema](https://docs.aws.amazon.com/pinpoint/latest/apireference/apps-application-id-messages.html#apps-application-id-messages-schemas)

**Comment by endgame** [comment]
I believe I have found a bug in the generator, and #790 should fix that.

I have regenerated `amazonka-pinpoint` on a new branch https://github.com/endgame/amazonka/tree/regenerate-pinpoint-for-newmana . Can you please help me by testing this branch and seeing whether it solves your problem? I'm hoping to regenerate all services soon, and I'd like for this to make it in.

**Comment by newmana** [comment]
Hi, I gave it a go and haven't got back to it I got this compiler error ```amazonka-pinpoint             ../amazonka-pinpoint-2.0/gen/Amazonka/Pinpoint/TagResource.hs:113:30: error:
amazonka-pinpoint             >     Not in scope: data constructor ‘Core.ToJSON’
amazonka-pinpoint             >     Perhaps you meant variable ‘Core.toJSON’ (imported from Amazonka.Core)
amazonka-pinpoint             >     Module ‘Amazonka.Core’ does not export ‘ToJSON’.
amazonka-pinpoint             >     |
amazonka-pinpoint             > 113 |   toJSON TagResource' {..} = Core.ToJSON tagsModel
amazonka-pinpoint             >     |                              ^^^^^^^^^^^
amazonka-pinpoint             >```

**Comment by endgame** [comment]
Bah, I know exactly what typo I've done. I'll have a new version for you to try soon. Thanks very much.

**Comment by endgame** [comment]
Pushed a version which actually compiles, can you please try that?

**Comment by newmana** [comment]
Yes this compiles and (being Haskell - LOL) works!

**Comment by endgame** [comment]
Excellent. Have you had any problems on the deserialisation side which I should look at before regenerating everything?

**Comment by newmana** [comment]
We only do updates - so can't tell you if there's a problem there.

**Comment by endgame** [comment]
OK, just wanted to make sure you weren't getting deseralisation errors in the responses to these API calls. Thanks, I will proceed.

**Comment by newmana** [comment]
Yeah, we didn't really do anything with the responses and just happy path testing.

I found some requests to test the error handling coming back and I also turned the logging on. These all worked fine.
