### ISSUE TITLE
What should we expect for GHC 9.2 support?

### ISSUE THREAD

**Issue by chrisdone-artificial** [brendanhay/amazonka#773]
Hi, 

We're using amazonka at Artificial Labs, we've been tracking gradual movement of packages to move over to GHC 9.2 with the latest stackage nightly, and the package remaining in our dependency tree that isn't supported is amazonka. Should we expect a GHC 9.2 release, or is that being punted to 9.4, or some other plan? 

We're not pushing for any particular plan, just researching the feasibility. 

Cheers!

**Comment by endgame** [comment]
I intend for Amazonka 2.0 to support the latest GHC that its dependencies allow. Can you tell me more about how Artificial is using Amazonka - are you pulling the latest `main` via `extra-deps` or what?

**Comment by endgame** [comment]
We released an RC for 2.0 last November and the [release announcement](https://github.com/brendanhay/amazonka/discussions/716) has instructions for adding it to `stack.yaml`. I would strongly recommend you give that a go.

Are you using `haskell.nix` or some other Nix framework?
