### ISSUE TITLE
amazonka-dynamodb: Serialization Failure

### ISSUE THREAD

**Issue by RobertFischer** [brendanhay/amazonka#774]
Using commit 27322ea0db68712e1c331be4124080144c975750

When fetching data (paginated, so using conduits) from my DynamoDB, I get the following error: 
```
Error in $[2].subtleApps[0].active: parsing Base64 failed, expected String, but encountered Boolean
```

The `$[2]` is because that's the first returned item that has a non-empty `subtleApps` list (`$[0]` and `$[1]` both have `\"subtleApps\":{\"L\":[]}`).

The offending item has the following field:
```
\"subtleApps\":{\"L\":[{\"M\":{\"active\":{\"BOOL\":true},\"expiration\":{\"S\":\"12/01/2022\"},\"renewalFreqInDays\":{\"N\":\"15\"},\"appId\":{\"S\":\"3000\"}}}]}
```

Seems like perfectly reasonable JSON to me, so I'm curious why it's expecting a string....

**Comment by endgame** [comment]
Pretty sure this is just me being dumb. Can you see if #775 fixes this for you?

**Comment by RobertFischer** [comment]
@endgame It's not you being dumb: it's the shitty API tripping you up.

Thanks for the quick fix. I'm testing it now.
