### ISSUE TITLE
Core depends on unordered-containers >0.2.3

### ISSUE THREAD

**Issue by tathougies** [brendanhay/amazonka#79]
amazonka-core depends on unordered-containers >0.2.3 but undordered-containers before 0.2.5 does not have a Read instance for HashMap. This Read instance is needed to instantiate Read for Network.Internal.AWS.Data.Internal.Map.

**Comment by brendanhay** [comment]
I've released your fix as part of [0.3.0](http://hackage.haskell.org/package/amazonka-core), hope that helps.

**Comment by tathougies** [comment]
Thanks for the quick turnaround. It helps a lot!

Travis
