### ISSUE TITLE
amazonka-core won't build on ghc-9.2.2

### ISSUE THREAD

**Issue by scurtis142** [brendanhay/amazonka#800]
We are using ghc-9.2.2 which is [tied to version](https://downloads.haskell.org/ghc/9.2.2/docs/html/users_guide/9.2.2-notes.html#included-libraries) 2.18.0.0 of template-haskell. 

Since amazonka requires `aeson (>=0.8 && <1.6)` and aeson-1.5.6.0 (the last version before 1.6) requires template-haskell < 2.18, I believe that it's impossible to build amazonka on ghc-9.2.2 (or greater).

Bumping your aeson version to 2.1.0.0 would fix this, but will require you to move to aeson's in-build map data structure.

**Comment by endgame** [comment]
Latest `main` has fixes for this, and much more. You should switch your project over to it, as the amazonka on Hackage is many years out of date. Work is progressing towards a release.

Instructions are here: https://github.com/brendanhay/amazonka/discussions/716

**Comment by scurtis142** [comment]
Ah cheers, I'll take a look. :)

**Comment by endgame** [comment]
Great. If you run into trouble with something on `main`, please open an issue.

**Comment by scurtis142** [comment]
Ok, will do. Seems to be building great for me now. Thanks.

**Comment by hasufell** [comment]
When will this be released? Several packages on hackage are broken due to this and the resolver can't figure out a build plan.

**Comment by hasufell** [comment]
You can just backport the 9.2.2 patch. Supporting recent GHC versions shouldn't be tied to milestones.
