### ISSUE TITLE
Which commit is recommended, `main` or 2.0.0-rc1?

### ISSUE THREAD

**Issue by ysangkok** [brendanhay/amazonka#819]
I think some users may perceive a release candidate to be more stable than the latest commit from `main` at some arbitrary point in time. Which is considered more stable? I see a couple of users saying that they have tested a recent Amazonka in production, but I am not sure whether that is the release candidate or the latest `main`.

Would be nice to have this documented, such that people are not missing out on potential important bugfixes that have occurred since 2.0.0-rc1. Or the reverse, if experimental changes have occurred, and it is better to stay on 2.0.0-rc1.

**Comment by endgame** [comment]
Best to follow `main`. I try very hard not to push experimental things there, and work uses it as well so at least the core libraries and the services we use are reasonably well-tested.
