### ISSUE TITLE
bucket url is wrong when you use minio

### ISSUE THREAD

**Issue by silky** [brendanhay/amazonka#841]
when you set your own endpoint, the latest version of amazonka drops, i believe, the bucket name, perhaps because without setting the endpoint it attempts to put it in the domain itself?

you can see this with something like:

```
let ourS3 = setEndpoint False "localhost" 9000 defaultService
env' <- newEnv Discover <&> configure ourS3
...
```

**Comment by endgame** [comment]
Fixed a couple of weeks back in #832 - you need to set the S3 addressing style in your overridden service.
