### ISSUE TITLE
Break lens dependency

### ISSUE THREAD

**Issue by endgame** [brendanhay/amazonka#845]
Since `amazonka` and `amazonka-*` service bindings have all moved to using unprefixed records, `Generic` instances, and a strong recommendation to use one of `generic-lens`/`generic-optics`/`-XOverloadedRecordDot`, we should look at breaking the `lens` dependency in `amazonka-2.1`.

This means providing Van Laarhoven optics without depending on any particular optics package.

Most of this is pretty trivial, but we will have to degrade `Amazonka.S3.Internal.keyComponents :: Delimiter -> IndexedTraversal' Int ObjectKey Text` to `keyComponents :: Delimeter -> Traversal' ObjectKey Text`. Given that `Control.Lens.Indexed.indexing` exists, this is probably not too bad.

**Comment by wolverian** [comment]
I'm very interested in using Amazonka without lenses, but I'm not sure how to work with e.g. in amazonka-s3 where a `Bucket` has a `name :: BucketName`, where `BucketName` is a `newtype BucketName = BucketName Text`. I can reach the BucketName with `bucket.name` easily enough, but then I still have the newtype wrapper to get through if I want the actual text. I might be just missing something obvious here.

**Comment by endgame** [comment]
You can use the constructor in a pattern binding e.g., the LHS of a `let`:
```haskell
let BucketName bn = bucket.name in ...
```
But it's a good point — we'll probably want most `newtype`s to have a selector declared.

**Comment by wolverian** [comment]
Actually, `bucket.name` gives me:

```haskell
• No instance for ‘GHC.Records.HasField
                     "name" S3.Bucket S3.BucketName’
    arising from selecting the field ‘name’
• In the expression: bucket.name
  In a pattern binding: S3.BucketName name = bucket.name
```

**Comment by endgame** [comment]
Yes, it won't solve `HasField` constraints [unless the field selector is in scope](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/hasfield.html#solving-hasfield-constraints). Import it from `Amazonka.S3.Types`, viz:

```haskell
import Amazonka.S3
-- The top-level module does not export accessors
import Amazonka.S3.Types (Bucket (..))
import Data.Coerce (coerce)
import Data.Text (Text)

-- Pick whichever you prefer
bucketName :: Bucket -> Text
bucketName b = case b.name of
  BucketName n -> n

bucketName' :: Bucket -> Text
bucketName' b = let BucketName n = b.name in n

bucketName'' :: Bucket -> Text
bucketName'' b = coerce b.name
```
