### ISSUE TITLE
Relax time dependency constraint

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#85]
The `aeson == 0.8.*` and `time >= 1.5` constraints have caused build issues for a number of people.

Ideally I'd like to support time dependency constraints of `>= 1.5`, and `< 1.5` if possible, otherwise supporting the most common case of `< 1.5`.

CC: @dysinger, @intractable

**Comment by dysinger** [comment]
Yay! Thanks @brendanhay
