### ISSUE TITLE
Add amazonka to stackage.org

### ISSUE THREAD

**Issue by dysinger** [brendanhay/amazonka#87]
I would like to request that we get these libraries up on Stackage.org.  This is such a useful set of libraries.  I'm excited about it as it opens automation (in Haskell) on AWS. No more Python/Ruby/JS/Java for AWS & it's so much more complete than other AWS libs we have in haskell.

Stackage.org is a set of haskell packages that have all been through CI & known to work together.  The  entire stack is built nightly.  There are stable long term support releases too.  It's pretty slick & exposes the code to a wider audience.

It doesn't take much work to set up.  http://www.stackage.org/authors

**Comment by brendanhay** [comment]
I'm familiar with stackage but haven't really taken the plunge primarily because amazonka's current state (lacking documentation, examples, streaming-lib agnosticism, etc.) isn't what I'd consider stable/1.0 release material. The other elephant in the room is many of the APIs have not been exercised by myself or users, so it feels a bit overconfident to add them to any sort of long term release.

If it does help alot with any build and installation issues then I'll investigate adding it to stackage anyway.

**Comment by dysinger** [comment]
stackage doesn't promise that every library is bug free or in it's 4.0.0 series.  It only verifies that things compile together.  but I understand.  I would also be happy to help.

**Comment by snoyberg** [comment]
Many people add just-released libraries to Stackage, quality and documentation isn't an issue. The advantages of having your libraries in Stackage are:

* You'll get a message when your code no longer compiles with dependencies
* Users of curated systems will be able to get your libraries automatically

In other words, by adding to Stackage, you're increasing your userbase and ensuring that interested users will have an easier time getting your software.

**Comment by proger** [comment]
:+1: Yes please!

**Comment by brendanhay** [comment]
OK, you guys win. I'll overcome my stage-fright and add it to Stackage sometime this week.

**Comment by proger** [comment]
![](http://media.giphy.com/media/a3IWyhkEC0p32/giphy.gif)

**Comment by brendanhay** [comment]
I've kicked off Stackage integration with fpco/stackage#489, lets' see how it goes!

**Comment by brendanhay** [comment]
There are a few constraint/bounds failures across the packages I submitted due to my use of newer `transformers` and `mtl` due to `ExceptT` availability. I'm currently working on adding `*-compat` packages to be able to relax the lower bounds.

**Comment by brendanhay** [comment]
[0.3.3](http://hackage.haskell.org/package/amazonka-0.3.3) (and future versions) should now be available on [Stackage](http://www.stackage.org/package/amazonka) subject to the nightly snapshot being made.

**Comment by snoyberg** [comment]
Thanks again! I'm running a build now to see if there are any issues, if
so, I'll open up tickets.

**Comment by brendanhay** [comment]
Thanks @snoyberg.

**Comment by dysinger** [comment]
Yay!
