### ISSUE TITLE
Item in GetItemResponse is not optional

### ISSUE THREAD

**Issue by kokobd** [brendanhay/amazonka#895]
The item in `GetItemResponse` is declared as
```
item :: Prelude.HashMap Prelude.Text AttributeValue
```

But the [AWS Doc](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_GetItem.html) says:
> If there is no matching item, GetItem does not return any data and there will be no Item element in the response.

Currently when an item is not found, I need to use `resp ^. #item == mempty` to check for that. Will it be better to use `Maybe`, or document this behavior?

**Comment by endgame** [comment]
We have limited control over the documentation because it is generated from service definitions, and not worth overriding in configs. See https://github.com/brendanhay/amazonka/issues/739 for how to resolve spurious Maybes in requests/responses.

**Comment by endgame** [comment]
Adding to 2.0 because it should be a quick fix.
