### ISSUE TITLE
S3 getObject: The request signature we calculated does not match the signature you provided. Check your key and signing method. (SignatureDoesNotMatch)

### ISSUE THREAD

**Issue by dimchansky** [brendanhay/amazonka#90]
Trying get object using this code from `runAWST`:
```haskell
getObjectSource bucket key =
  unRsBody . view gorBody <$> send (getObject bucket key)
  where unRsBody (RsBody source) = source
```
Got error: 

> Left (ServiceError "S3" (Status {statusCode = 403, statusMessage = "Forbidden"}) "RESTError {_restRequestId = \"****************\", _restType = Nothing, _restCode = ErrorCode \"SignatureDoesNotMatch\", _restMessage = \"The request signature we calculated does not match the signature you provided. Check your key and signing method.\"}")

`listObjects` works perfect with the same credentials.

**Comment by brendanhay** [comment]
Hi @dimchansky, 

Can you please tell me the versions of `amazonka`, `amazonka-core`, and `amazonka-s3` you are using?

**Comment by brendanhay** [comment]
I've used a quick test in the form of #3f70a3a with the latest version (`amazonka-*-0.3.3` + `amazonka-0.3.3.1`) and it seems to work as expected.

**Comment by dimchansky** [comment]
Hm.. As I see from my cabal.config I've tried it with the 
amazonka-0.3.3.1   
amazonka-core-0.3.3
amazonka-s3-0.3.3
Can't reproduce now, because I rewrote the S3 module with aws package.

**Comment by brendanhay** [comment]
OK, I'll close the issue. If you feel like reproducing it sometime in the future feel free to reopen with more information.

**Comment by qxjit** [comment]
I ran into this same issue when I passed a leading '/' on the s3 object key. When I removed the '/' I was able to get the object without a problem.

**Comment by brendanhay** [comment]
Thanks for the headsup @qxjit. That should really transparently done in the serialisation for the `ObjectKey`. I'll see about adding a case to handle.
