### ISSUE TITLE
Looking for a way to specify a region other than the AWS ones

### ISSUE THREAD

**Issue by newhoggy** [brendanhay/amazonka#905]
For example to support non-AWS cloud services.

See https://github.com/haskell-works/cabal-cache/issues/230#issuecomment-1528864536

**Comment by endgame** [comment]
In Amazonka 2.0, which should hopefully get its second RC soon™, `Region` is a `newtype` over `Text` and its constructor is exported. (This is also true for EC2 instance types and other sum types in service bindings.)

https://github.com/brendanhay/amazonka/blob/2dc498fe75ff47db2db3ee63e042b1aa3da57c0f/lib/amazonka-core/src/Amazonka/Types.hs#L823

**Comment by endgame** [comment]
P.S. Instructions for getting `amazonka` libraries from latest `main` are available at: https://github.com/brendanhay/amazonka/discussions/716
