### ISSUE TITLE
GHC 9.6

### ISSUE THREAD

**Issue by endgame** [brendanhay/amazonka#908]
It would be cool if we could support GHC 9.6, since `amazonka-core` and `amazonka` both build with `--allow-newer=cryptohash-sha1:base,cryptohash-md5:base,haddock-library:base`.

PR the upstream libraries and ask for a bounds revision either by the maintainers or trustees, as appropriate:

- [ ] `cryptohash-md5`
- [ ] `cryptohash-sha1`
- [ ] `haddock-library`

**Comment by ysangkok** [comment]
I think this can be closed, all those libraries were updated.

- https://hackage.haskell.org/package/haddock-library-1.11.0/revisions/
- https://hackage.haskell.org/package/cryptohash-md5-0.11.101.0/revisions/
- https://hackage.haskell.org/package/cryptohash-sha1-0.11.101.0/revisions/

**Comment by endgame** [comment]
Agreed. Thanks for the prod.
