### ISSUE TITLE
describeInstances does not return data for non us-east-1 regions

### ISSUE THREAD

**Issue by geraud** [brendanhay/amazonka#91]
Hi, I have written a little tool on top of your library, and it seems that I cannot get data for non-east regions. I am sure I have instances running, but the API call returns no results.
The code for the call is located at:
https://github.com/geraud/access/blob/master/library/Access/AWS.hs

**Comment by brendanhay** [comment]
Seems very unusual, considering I'm running similar calls in `eu-west-1` and `eu-central-1` with frequency.

I'm away from the keyboard for most of the weekend but will try to look into your issue + code at the earliest possible convenience.

**Comment by brendanhay** [comment]
Just off the top of my head - can you set the `Env`'s logger to `Trace` and ensure that everything about the call looks OK? There should also be some response content you can use to verify the response is in fact empty or not.

**Comment by brendanhay** [comment]
Is this fixed via your recent [pull request](#92)?

**Comment by geraud** [comment]
Yes, it was the fix for my problem.
