### ISSUE TITLE
Support `crypton`

### ISSUE THREAD

**Issue by endgame** [brendanhay/amazonka#912]
`cryptonite` has been forked to `crypton` for ongoing maintenance. We should support it with a flag, defaulting to `crypton` and falling back to `cryptonite`.

**Comment by mbj** [comment]
Why the flag? Context: I'd be happy to send a PR to do the change but would be interested to know why we'd want the flag?

**Comment by endgame** [comment]
That was an initial guess, before I saw which way things were going to go in the community. I haven't had time to think much about this; are people writing their packages to support both `cryptonite` and `crypton`, or has everyone just moved over to `crypton`?

**Comment by mbj** [comment]
So far I've seen just moves to crypton and issues that just ask to move to crypton.

* https://github.com/snoyberg/conduit/pull/506
* https://github.com/yesodweb/wai/pull/931
* https://github.com/haskell-servant/servant/pull/1686
* https://github.com/snoyberg/http-client/pull/506

none of these have so far AFAIK used a flag. (there are some more PRs unmerged as of yet).

**Comment by endgame** [comment]
If those projects beneath us in the depgraph don't use a flag then there's no point us doing so either. The PR should be pretty straightforward, then. Only subtlety is you might need to change the `cabal.ede` template and (in a separate PR, targeting your main PR) run `scripts/generate --commit` to rebuild the service bindings.
