### ISSUE TITLE
Unable to derive Typeable of AWSRequest

### ISSUE THREAD

**Issue by rickeyski** [brendanhay/amazonka#913]
Hi All,

I have an issue trying to upgrade some code. I am stuck trying to figure out why the wrappers around `send` and `await` are failing to compile.

I am using Stackage `lts-20.24`, GHC `9.2.7`,  and Amazonka `main` rev `83fef97319628d24395805c1f13fb010c821a751`

I have created a minimal reproducer of my issue in this [gist](https://gist.github.com/rickeyski/8c49d0c00a3fed5397bb816d29a665a8#file-s3-hs-L41).

The below is the stack trace.
```
 src/S3.hs:41:35: error:
    • Could not deduce (base-4.16.4.0:Data.Typeable.Internal.Typeable r)
        arising from a use of ‘send’
      from the context: AWSRequest r
        bound by the type signature for:
                   genericSend :: forall r.
                                  AWSRequest r =>
                                  Env -> r -> IO (AWSResponse r)
        at src/S3.hs:40:1-61
    • In the second argument of ‘(.)’, namely ‘send env’
      In the expression: runResourceT . send env
      In an equation for ‘genericSend’:
          genericSend env = runResourceT . send env
   |
41 | genericSend env =  runResourceT . send env
   |                                   ^^^^
```

Thanks in advance,
Rickey

**Comment by rickeyski** [comment]
Additionally, the reproducer generates the same error using the nix development shell for `.#ghc92`

**Comment by endgame** [comment]
Thanks for the report and the reproducer. Can you try adding `(Typeable r)` to your constraints at [line 40](https://gist.github.com/rickeyski/8c49d0c00a3fed5397bb816d29a665a8#file-s3-hs-L40)?

**Comment by rickeyski** [comment]
Thanks! That did it. The working type signature is
``` haskell
genericSend :: (AWSRequest r, Typeable r, Typeable (AWSResponse r)) => Region -> r -> IO (AWSResponse r)
```
