### ISSUE TITLE
Support for Google Storage

### ISSUE THREAD

**Issue by phunehehe** [brendanhay/amazonka#94]
AFAIU Boto has it, so it should be in the specs somewhere http://boto.readthedocs.org/en/latest/ref/gs.html
Beside the possible branding conflict, what's your thought about this?

**Comment by phunehehe** [comment]
A bit more about GS...
It's almost similar to S3 (and thus is useful if you want to back up S3 buckets), with mostly the same API (I think only a change in endpoint is required, though there are some optional arguments here and there).
I looked but didn't find any specs in botocore for GS, so I'm not sure anymore. The enabling bit seems to be [provider.py](https://github.com/boto/boto/blob/develop/boto/provider.py), among other things.

**Comment by brendanhay** [comment]
Unfortunately botocore (and by extension [boto3](https://github.com/boto/boto3)) only supports AWS services and the service definitions botocore is based on are developed and made available from an internal at Amazon, making it unlikely that botocore will support any of the Google services.

The Google Storage support in boto2 is hand-rolled, so it would make more sense to create a separate Haskell SDK for the Google services in a similar fashion.

**Comment by phunehehe** [comment]
Okay, I guess the next stop is to ask Google to provide such a team. If only we could contact humans at Google :)
