### ISSUE TITLE
amazonka-test not uploaded to hackage

### ISSUE THREAD

**Issue by ysangkok** [brendanhay/amazonka#949]
I am trying to add amazonka back into hackage and I noticed that packages depend on amazonka-test, for example see [cloudformation.cabal](https://hackage.haskell.org/package/amazonka-cloudformation-2.0/src/amazonka-cloudformation.cabal).

But [amazonka-test](https://hackage.haskell.org/package/amazonka-test) is still pre-2.0 on Hackage.

I'll disable the tests for now.

**Comment by brendanhay** [comment]
Should be available now - apologies for the fumble.
