### ISSUE TITLE
crypton-0.34 could be accepted with revision

### ISSUE THREAD

**Issue by ysangkok** [brendanhay/amazonka#966]
According to

* https://github.com/commercialhaskell/stackage/issues/7175

it seems like since the package doesn't follow PVP, amazonka unnecessarily rejects the new version, even though it is compatible.

**Comment by endgame** [comment]
To be clear: this is a relaxation of the upper bound in `amazonka-core` and `amazonka-s3-encryption` to `<0.35, right? Would you mind preparing a PR? I can do the Hackage revision.
