### ISSUE TITLE
Compilation failures with GHC 9.8

### ISSUE THREAD

**Issue by ysangkok** [brendanhay/amazonka#969]
Amazonka packages were thrown out of Stackage Nightly, there must have been some kinda of incompatibility with the compiler or newer libraries: [see build-constraints.yaml](https://github.com/commercialhaskell/stackage/commit/9d04eeeb3e408db255ec31a65beb7a1dc26b7f47#diff-9949098b9af80e5fcef9a718fdda416f3fa8272ca8add4d67ae65fe892990939R1974-R1998)

**Comment by ysangkok** [comment]
Error message is available:

* https://github.com/commercialhaskell/stackage/issues/7261

**Comment by endgame** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/24317

**Comment by ysangkok** [comment]
Fixed by https://github.com/brendanhay/amazonka/commit/c604b8f282785f41977f234d33e2bae10773ece2

**Comment by ysangkok** [comment]
@endgame Would it be possible to fix this just by amending `default-extensions`? Then it wouldn't be necessary to reupload everything, a revision would do.

**Comment by endgame** [comment]
No, I tried to preview a change like that, and Hackage only allows revisions which change dependency information.
