### ISSUE TITLE
amazonka-sqs example out of date

### ISSUE THREAD

**Issue by tmcgilchrist** [brendanhay/amazonka#99]
The example of how to use amazonka-sqs seems to be out of data, in particular the lines to ack/delete messages. The functions `^!?` and `act` don't seem to be defined anywhere.

```haskell
         forM_ ms $ \m -> do
            say "Acking " (m ^. mReceiptHandle)
            m ^!? mReceiptHandle
                . _Just
                . act (send . deleteMessage url)
```
https://github.com/brendanhay/amazonka/blob/52c8a04a63fb5e92adc0fcc49e21612748838423/amazonka-sqs/examples/src/Examples.hs#L69-L73

**Comment by brendanhay** [comment]
Apologies, the `lens` dependency has been updated and the functions previously located under `Control.Lens.Action` and re-exported via `Control.Lens`, have been split off into a separate package named `lens-action`.

I'll update the example shortly.

**Comment by tmcgilchrist** [comment]
thanks, much appreciated

**Comment by tmcgilchrist** [comment]
BTW I had luck with adding Control.Lens.Action and changing the code to use `^!!`
```haskell
        -- Ack!
        forM_ ms $ \m -> do
            say "Acking " (m ^. mReceiptHandle)
            m ^!! mReceiptHandle
                . _Just
                . act (send . deleteMessage url)
```

**Comment by tmcgilchrist** [comment]
@brendanhay I wanted to raise as well, using this example code I don't seem to be able to receive messages. i.e. the code adds messages I can see in the web UI but the code cannot receive them.

I'll attach a minimal working example shortly.

**Comment by brendanhay** [comment]
Apologies - the code above completely flew under my radar. Is this still the case? There have just recently been a large number of (possibly breaking) changes merged to `develop` as part of work torwards a `1.0` release.

**Comment by tmcgilchrist** [comment]
I'll have a look at it today. I imagine we'll be having a good look at the
new release at work. Thanks.

**Comment by brendanhay** [comment]
Added your example above to the project in d3e0cda - seems to be working as expected in a number of regions in this hemisphere.

Going to close as WFM, feel free to reopen if you experience issues.
